import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

describe('dashboard data boundary guards', () => {
  it('does not load message dashboard rows with select star', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/Messages.tsx'), 'utf8');
    const serviceSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/messages/messageService.ts'), 'utf8');
    const viewPropsSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/messages/buildMessageDashboardViewProps.ts'), 'utf8');
    const derivedStateSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/messages/buildMessageDashboardDerivedState.ts'), 'utf8');
    const uiStateSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/messages/useMessageDashboardUiState.ts'), 'utf8');
    const billingActionsSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/messages/useMessageBillingActions.ts'), 'utf8');
    const dataHookSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/messages/useMessageDashboardData.ts'), 'utf8');
    const deliveryHookSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/messages/useMessageDeliveryActions.ts'), 'utf8');
    const composeHookSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/messages/useMessageComposeActions.ts'), 'utf8');
    const continuityHookSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/messages/useMessageDashboardContinuitySync.ts'), 'utf8');
    const draftHookSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/messages/useMessageComposerDraftActions.ts'), 'utf8');
    const historyHookSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/messages/useMessageComposerHistoryActions.ts'), 'utf8');
    const prefillHookSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/messages/useMessageDashboardPrefillSync.ts'), 'utf8');

    expect(serviceSource).toContain('const MESSAGE_SELECT = [');
    expect(serviceSource).toContain('.select(MESSAGE_SELECT)');
    expect(serviceSource).toContain('createDashboardMessage');
    expect(serviceSource).toContain('export async function getMessageAccessToken()');
    expect(serviceSource).toContain('export async function triggerDashboardBulkSend(messageId: string)');
    expect(serviceSource).toContain('export async function triggerScheduledMessageDispatch(limit = 10)');
    expect(serviceSource).toContain('supabase.auth.getSession()');
    expect(deliveryHookSource).toContain('await triggerDashboardBulkSend(message.id)');
    expect(deliveryHookSource).toContain('const result = await triggerScheduledMessageDispatch(10)');
    expect(source).toContain('<MessageDashboardRouteView');
    expect(source).toContain('useMessageDashboardData({');
    expect(source).toContain('useMessageDeliveryActions({');
    expect(source).toContain('useMessageComposeActions({');
    expect(source).toContain('useMessageDashboardContinuitySync({');
    expect(source).toContain('useMessageComposerDraftActions({');
    expect(source).toContain('useMessageComposerHistoryActions({');
    expect(source).toContain('useMessageDashboardPrefillSync({');
    expect(source).toContain('buildMessageDashboardDerivedState({');
    expect(source).toContain('buildMessageDashboardViewProps({');
    expect(source).toContain('useMessageBillingActions({');
    expect(source).toContain('useMessageDashboardUiState()');
    expect(source).not.toContain("from '../../lib/supabase'");
    expect(source).not.toContain("supabase.from('messages').insert(payload)");
    expect(source).not.toContain('supabase.auth.getSession()');
    expect(source).not.toContain('fetch(BULK_SEND_URL, {');
    expect(source).not.toContain('const result = await triggerScheduledMessageDispatch(10)');
    expect(source).not.toContain('triggerDashboardBulkSend(inserted.id)');
    expect(source).not.toContain('insertDashboardMessageMinimal({');
    expect(source).not.toContain('updateDashboardMessage(editingMessageId, {');
    expect(source).not.toContain(".from('messages')\n        .select('*')");
    expect(source).not.toContain('.from("messages")\n        .select("*")');
    expect(source).not.toContain('<MessageDashboardView');
    expect(source).not.toContain('<MessageComposerCard');
    expect(source).not.toContain('<MessageGuestFlowCard');
    expect(source).not.toContain('<MessageHistoryCard');
    expect(source).not.toContain('<MessageReachSnapshotCard');
    expect(source).not.toContain('<MessageSavedTemplatesCard');
    expect(source).not.toContain('<MessageSendingDetailsPanel');
    expect(source).not.toContain('<MessageStartingPointsCard');
    expect(source).not.toContain('<MessageDetailModal');
    expect(source).not.toContain('<ToastList');
    expect(source).not.toContain('<DashboardPageHero');
    expect(source).not.toContain('<DashboardStateBlock');
    expect(source).not.toContain('MessageComposerLanguagePreviewPanel');
    expect(source).not.toContain('MessageComposerSchedulePanel');
    expect(source).not.toContain('MessageComposerRecipientPreviewPanel');
    expect(source).not.toContain('MessageComposerPreflightPanel');
    expect(dataHookSource).toContain('const { activeSite, weddingSite: loadedWeddingSite } = await loadMessagesActiveSite(userId);');
    expect(dataHookSource).toContain('setMessages(await loadDashboardMessages(weddingSite.id));');
    expect(dataHookSource).toContain('const data = await loadMessageDeliveries(messageIds);');
    expect(dataHookSource).toContain('const { options, guestIdsByEvent } = await loadMessageItineraryAudience(weddingSite.id);');
    expect(dataHookSource).toContain('const { expiringSoon, transactions } = await loadSmsCreditPreview(weddingSite.id, cutoff);');
    expect(dataHookSource).not.toContain("from '../../lib/supabase'");
    expect(viewPropsSource).toContain('const detailModalProps = args.viewingMessage');
    expect(viewPropsSource).toContain('composerProps: {');
    expect(viewPropsSource).toContain('historyProps: {');
    expect(viewPropsSource).toContain('reachSnapshotProps: {');
    expect(viewPropsSource).not.toContain("from '../../lib/supabase'");
    expect(derivedStateSource).toContain('const filteredHistory = filterMessageHistory({');
    expect(derivedStateSource).toContain('const campaignThreads = buildCampaignThreads(messages, deliveries);');
    expect(derivedStateSource).toContain('const activeCampaignThread = getActiveCampaignThread({ campaignThreads, historyCampaignFilter, historySearch });');
    expect(derivedStateSource).toContain('const providerTelemetry = buildProviderTelemetry(messages, deliveries);');
    expect(derivedStateSource).not.toContain("from '../../lib/supabase'");
    expect(uiStateSource).toContain('const [savedTemplates, setSavedTemplates] = useState<SavedComposerTemplate[]>([]);');
    expect(uiStateSource).toContain("const [showSendingDetails, setShowSendingDetails] = useState(() => new URLSearchParams(window.location.search).get('details') === '1');");
    expect(uiStateSource).toContain("const raw = readPlannerAccessRole('messages', weddingSite.id);");
    expect(uiStateSource).toContain("writePlannerAccessRole('messages', weddingSite.id, messagesRole);");
    expect(uiStateSource).not.toContain("from '../../lib/supabase'");
    expect(billingActionsSource).toContain('const url = await createSmsCreditsSession(weddingSite.id, success, cancel, pack);');
    expect(billingActionsSource).toContain("type: 'sms_credits_checkout_started'");
    expect(billingActionsSource).toContain('toast(safeMessagesError(err,');
    expect(billingActionsSource).not.toContain("from '../../lib/supabase'");
    expect(composeHookSource).toContain('insertDashboardMessageMinimal({');
    expect(composeHookSource).toContain('await updateDashboardMessage(editingMessageId, {');
    expect(composeHookSource).toContain('const result = await triggerDashboardBulkSend(inserted.id)');
    expect(composeHookSource).not.toContain("from '../../lib/supabase'");
    expect(continuityHookSource).toContain("window.addEventListener('focus', refreshGuestMessageContinuity)");
    expect(continuityHookSource).toContain("window.addEventListener(RSVP_CONTINUITY_EVENT, handleRsvpContinuityUpdate)");
    expect(continuityHookSource).toContain("document.addEventListener('visibilitychange', handleVisibilityChange)");
    expect(continuityHookSource).not.toContain("from '../../lib/supabase'");
    expect(draftHookSource).toContain('await createDashboardMessage(payload)');
    expect(draftHookSource).toContain('writeSavedComposerTemplates(updated)');
    expect(draftHookSource).toContain("applyComposerTemplate('save-the-date', {");
    expect(draftHookSource).not.toContain("from '../../lib/supabase'");
    expect(historyHookSource).toContain('const scheduledInputValue = toScheduleInputValue(message.scheduled_for)');
    expect(historyHookSource).toContain("applyComposerTemplate('rsvp-reminder', {");
    expect(historyHookSource).toContain('formatScheduledMessageDateTime(scheduledIso)');
    expect(historyHookSource).not.toContain("from '../../lib/supabase'");
    expect(prefillHookSource).toContain("const requestedTemplate = templateKey && COMPOSER_TEMPLATES.some((template) => template.key === templateKey) ? templateKey : null");
    expect(prefillHookSource).toContain("toast('Text credit purchase complete. Refreshing your balance now.', 'success')");
    expect(prefillHookSource).toContain("cleanedParams.delete('smsCredits')");
    expect(prefillHookSource).not.toContain("from '../../lib/supabase'");
  });

  it('keeps legacy public site repository reads out of private gate internals', () => {
    const source = readFileSync(join(process.cwd(), 'src/data/siteRepository.ts'), 'utf8');
    const fetchPublicSiteBody = source.match(/async fetchPublicSiteBySlug[\s\S]*?async fetchPublicSiteTranslation/)?.[0] ?? '';

    expect(fetchPublicSiteBody).not.toContain("'privacy_mode'");
    expect(fetchPublicSiteBody).not.toContain("'hide_from_search'");
    expect(fetchPublicSiteBody).not.toContain('.ilike(');
    expect(fetchPublicSiteBody).toContain('buildSiteUrlLookupCandidates(slug)');
  });

  it('loads persisted builder/public sections with an explicit section projection', () => {
    const source = readFileSync(join(process.cwd(), 'src/data/siteRepository.ts'), 'utf8');

    expect(source).toContain('const PERSISTED_SECTION_SELECT = ');
    expect(source).toContain('.select(PERSISTED_SECTION_SELECT)');
    expect(source).not.toContain(".from('sections')\n      .select('*')");
    expect(source).not.toContain(".from('sections')\n      .upsert({ ...rest, updated_at: new Date().toISOString() })\n      .select()\n      .single()");
    expect(source).not.toContain(".from('sections')\n      .insert({ ...section, site_id: siteId, created_at: now, updated_at: now })\n      .select()\n      .single()");
  });

  it('loads guest dashboard guest and RSVP rows with explicit projections', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/Guests.tsx'), 'utf8');
    const service = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/guestService.ts'), 'utf8');
    const campaignHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/useGuestDashboardCampaignActions.ts'), 'utf8');
    const clipboardHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/useGuestDashboardClipboardActions.ts'), 'utf8');
    const csvImportHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/useGuestDashboardCsvImport.ts'), 'utf8');
    const viewPropsHelper = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/buildGuestDashboardViewProps.ts'), 'utf8');
    const overlayActionsHelper = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/buildGuestDashboardOverlayActions.ts'), 'utf8');
    const dataHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/useGuestDashboardData.ts'), 'utf8');
    const followUpHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/useGuestDashboardFollowUpActions.ts'), 'utf8');
    const checkInsHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/useGuestDashboardCheckIns.ts'), 'utf8');
    const crudHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/useGuestDashboardCrudActions.ts'), 'utf8');
    const conflictHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/useGuestDashboardConflictActions.ts'), 'utf8');
    const derivedStateHelper = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/buildGuestDashboardDerivedState.ts'), 'utf8');
    const detailHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/useGuestDashboardGuestDetailActions.ts'), 'utf8');
    const opsHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/useGuestDashboardOpsActions.ts'), 'utf8');
    const routeActionsHelper = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/buildGuestDashboardRouteActions.tsx'), 'utf8');
    const rsvpConfigHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/useGuestDashboardRsvpConfigActions.ts'), 'utf8');
    const uiStateHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/guests/useGuestDashboardUiState.ts'), 'utf8');

    expect(source).not.toContain("from '../../lib/supabase'");
    expect(source).toContain('useGuestDashboardData({');
    expect(source).toContain('useGuestDashboardClipboardActions({');
    expect(source).toContain('useGuestDashboardCsvImport({');
    expect(source).toContain('useGuestDashboardFollowUpActions({');
    expect(source).toContain('useGuestDashboardCheckIns({');
    expect(source).toContain('useGuestDashboardCrudActions({');
    expect(source).toContain('useGuestDashboardConflictActions({');
    expect(source).toContain('useGuestDashboardGuestDetailActions({');
    expect(source).toContain('useGuestDashboardOpsActions({');
    expect(source).toContain('useGuestDashboardRsvpConfigActions({');
    expect(source).toContain('useGuestDashboardUiState()');
    expect(source).toContain('buildGuestDashboardDerivedState({');
    expect(source).toContain('buildGuestDashboardRouteActions({');
    expect(source).toContain('buildGuestDashboardViewProps({');
    expect(source).toContain('buildGuestDashboardOverlayActions({');
    expect(source).toContain('loadPublicSlug: loadGuestDashboardPublicSlug');
    expect(source).toContain('loadSiteSlug: loadGuestDashboardSiteSlug');
    expect(source).toContain('useGuestDashboardCampaignActions({');
    expect(source).toContain('buildGuestDashboardOverlayProps({');
    expect(source).toContain('<GuestDashboardRouteView');
    expect(source).not.toContain('<GuestDashboardOpsView');
    expect(source).not.toContain('<GuestRsvpSettingsView');
    expect(source).not.toContain('<GuestDashboardOverlays');
    expect(source).not.toContain('<GuestDashboardHeader');
    expect(source).not.toContain('<GuestDashboardContent');
    expect(source).not.toContain('<GuestDashboardWorkspace');
    expect(source).not.toContain('<GuestSnapshotInsightsPanel');
    expect(source).not.toContain('<GuestRsvpConflictPanels');
    expect(source).not.toContain('<GuestOpsSummaryPanel');
    expect(source).not.toContain('<GuestEngagementControlsPanel');
    expect(source).not.toContain('<GuestListDisplaySwitcher');
    expect(source).not.toContain('const guestEngagementProps = {');
    expect(source).not.toContain('const guestDashboardOpsViewProps = {');
    expect(source).not.toContain('const guestRsvpConfigViewProps = {');
    expect(source).not.toContain('const handleCopyOpsSummary = async () => {');
    expect(source).not.toContain('const handleCopyExceptionChecklist = async () => {');
    expect(source).not.toContain('const handleCopyMissingMealChecklist = async () => {');
    expect(source).not.toContain('const handleCopyNoContactChecklist = async () => {');
    expect(source).not.toContain('const handleCopyFilteredEmails = async () => {');
    expect(source).not.toContain('const saveCurrentSegment = () => {');
    expect(source).not.toContain('const addFollowUpTask = (text: string) => {');
    expect(source).not.toContain('const generateChecklistTasks = () => {');
    expect(source).not.toContain('const handleUndoLastCheckIn = async () => {');
    expect(source).not.toContain('const handleMarkThankYouSent = async (guest: GuestWithRSVP) => {');
    expect(source).not.toContain('const handleMarkAllDueThankYous = async () => {');
    expect(source).not.toContain('const handleClearAllCheckIns = async () => {');
    expect(source).not.toContain('await resolveGuestDashboardConflict(conflictId, resolvedAt);');
    expect(source).not.toContain('await resolveGuestDashboardConflicts(ids, resolvedAt);');
    expect(source).not.toContain('const resolveConflict = useCallback(async (conflictId: string) => {');
    expect(source).not.toContain('const resolveAllVisibleConflicts = useCallback(async () => {');
    expect(source).not.toContain("await persistGuestReminderSettings(weddingSiteId, patch);");
    expect(source).not.toContain('const handleDeleteAllGuests = async () => {');
    expect(source).not.toContain('const selectFilteredGuests = () => {');
    expect(source).not.toContain('const clearGuestSelection = () => {');
    expect(source).not.toContain('const keepOnlyVisibleSelection = () => {');
    expect(source).not.toContain('const selectUnresolvedGuests = () => {');
    expect(source).not.toContain('const getStatusBadge = (status: string) => {');
    expect(source).not.toContain('const [campaignPreset, setCampaignPreset] = useState');
    expect(source).not.toContain('const [campaignLog, setCampaignLog] = useState');
    expect(source).not.toContain('readStoredCampaignPreset()');
    expect(source).not.toContain('writeStoredCampaignPreset(campaignPreset)');
    expect(source).not.toContain('onCloseAddModal: () => {');
    expect(source).not.toContain('onCloseEditModal: () => {');
    expect(source).not.toContain('onCloseItineraryDrawer: () => {');
    expect(source).not.toContain('onSubmitAddGuest: (event) => { void handleAddGuest(event); },');
    expect(source).not.toContain('onSubmitEditGuest: (event) => { void handleEditGuest(event, editingGuest); },');
    expect(source).not.toContain('const filteredGuests = guests.filter((guest) => {');
    expect(source).not.toContain('const stats = {');
    expect(source).not.toContain('const eventReport = effectiveItineraryEvents.map((event) => {');
    expect(source).not.toContain('const dueReminderCandidatesGlobal = guests.filter((g) => !!g.email && !!g.invite_token && isDueReminder(g));');
    expect(source).not.toContain('loadGuestDashboardSiteSettings(user.id)');
    expect(source).not.toContain('loadGuestDashboardSnapshot(weddingSiteId)');
    expect(source).not.toContain('loadGuestDashboardItineraryFilters(weddingSiteId)');
    expect(source).not.toContain('loadGuestDashboardRsvpAuditFeed(weddingSiteId)');
    expect(source).not.toContain('buildGuestImportPreview({');
    expect(source).not.toContain('readGuestImportRows(file)');
    expect(source).not.toContain('insertImportedGuests(guestRows)');
    expect(source).not.toContain('loadGuestItineraryDrawerSnapshot(weddingSiteId, guest.id)');
    expect(source).not.toContain('removeGuestEventInvitation(eventId, itineraryDrawerGuest.id)');
    expect(source).not.toContain('addGuestEventInvitation(eventId, itineraryDrawerGuest.id)');
    expect(source).not.toContain('saveAssistedGuestRsvp({');
    expect(source).not.toContain('const addRsvpQuestionTemplate = useCallback((template: RsvpQuestionTemplate) => {');
    expect(source).not.toContain('const handleSaveRsvpConfig = async () => {');
    expect(source).not.toContain('writeStoredDemoRsvpConfig({ questions: cleanedQuestions, mealEnabled: rsvpMealEnabled, mealOptions });');
    expect(source).not.toContain('await persistGuestDashboardRsvpConfig({');
    expect(source).toContain('useGuestDashboardExports({');
    expect(service).toContain('export const GUEST_SITE_SETTINGS_SELECT = ');
    expect(service).toContain('export const GUEST_DASHBOARD_RSVP_SELECT = ');
    expect(service).toContain('export const GUEST_CONFLICT_SELECT = ');
    expect(service).toContain('export const GUEST_ITINERARY_EVENT_SELECT = ');
    expect(service).toContain('export const GUEST_ITINERARY_SITE_SELECT = ');
    expect(service).toContain('export const GUEST_EVENT_INVITATION_SELECT = ');
    expect(service).toContain('export const GUEST_AUDIT_SELECT = ');
    expect(service).toContain('export async function loadGuestDashboardSiteSettings(userId: string)');
    expect(service).toContain('export async function loadGuestDashboardSnapshot(weddingSiteId: string)');
    expect(service).toContain('export async function loadGuestDashboardItineraryFilters(weddingSiteId: string)');
    expect(service).toContain('export async function loadGuestDashboardRsvpAuditFeed(weddingSiteId: string)');
    expect(service).toContain('export async function loadGuestItineraryDrawerSnapshot(weddingSiteId: string, guestId: string)');
    expect(service).toContain('export async function addGuestEventInvitation(eventId: string, guestId: string): Promise<void>');
    expect(service).toContain('export async function removeGuestEventInvitation(eventId: string, guestId: string): Promise<void>');
    expect(service).toContain('export async function saveAssistedGuestRsvp(input: SaveAssistedGuestRsvpInput): Promise<SaveAssistedGuestRsvpResult>');
    expect(service).toContain('export async function resolveGuestDashboardSiteId(userId: string): Promise<string | null>');
    expect(service).toContain('export async function loadGuestDashboardSiteSlug(weddingSiteId: string): Promise<string | null>');
    expect(service).toContain('export async function loadGuestDashboardPublicSlug(weddingSiteId: string): Promise<string | null>');
    expect(service).toContain('export async function updateGuestCheckInForSite(');
    expect(service).toContain('export async function updateGuestThankYouSentForSite(');
    expect(service).toContain('export async function markGuestsThankYouSentForSite(');
    expect(service).toContain('export async function persistGuestDashboardRsvpConfig(input: PersistGuestDashboardRsvpConfigInput): Promise<void>');
    expect(service).toContain('export async function markGuestInvitationSentForSite(');
    expect(service).toContain('export async function markGuestInvitationAndReminderSentForSite(');
    expect(service).toContain('export async function markGuestReminderSentForSite(');
    expect(campaignHook).toContain('await sendGuestInvitationEmail({ guest, weddingSiteId, weddingSiteInfo })');
    expect(campaignHook).toContain('await markGuestInvitationSentForSite(weddingSiteId, guest.id, new Date().toISOString())');
    expect(campaignHook).toContain('await markGuestInvitationAndReminderSentForSite(weddingSiteId, guest.id, sentAtIso)');
    expect(campaignHook).toContain('await markGuestReminderSentForSite(weddingSiteId, guest.id, new Date().toISOString())');
    expect(clipboardHook).toContain('const handleCopyOpsSummary = async () => {');
    expect(clipboardHook).toContain('const handleCopyExceptionChecklist = async () => {');
    expect(clipboardHook).toContain('const handleCopyMissingMealChecklist = async () => {');
    expect(clipboardHook).toContain('const handleCopyNoContactChecklist = async () => {');
    expect(clipboardHook).toContain('const handleCopyFilteredEmails = async () => {');
    expect(clipboardHook).toContain('const handleCopyChecklist = async () => {');
    expect(clipboardHook).toContain('const handleCopyCampaignDryRun = async () => {');
    expect(clipboardHook).toContain('copyTextOrDownload(');
    expect(clipboardHook).not.toContain("from '../../../lib/supabase'");
    expect(followUpHook).toContain('const saveCurrentSegment = () => {');
    expect(followUpHook).toContain('const addFollowUpTask = (text: string) => {');
    expect(followUpHook).toContain('const generateChecklistTasks = () => {');
    expect(followUpHook).toContain('buildSavedSegment({');
    expect(followUpHook).toContain('buildFollowUpTask({ now: new Date(), text })');
    expect(followUpHook).toContain('buildGeneratedFollowUpTasks({ now: new Date(), rsvpOps, contactStats })');
    expect(followUpHook).not.toContain("from '../../../lib/supabase'");
    expect(checkInsHook).toContain('const handleUndoLastCheckIn = async () => {');
    expect(checkInsHook).toContain('const handleMarkThankYouSent = async (guest: GuestWithRSVP) => {');
    expect(checkInsHook).toContain('const handleMarkAllDueThankYous = async () => {');
    expect(checkInsHook).toContain('const handleClearAllCheckIns = async () => {');
    expect(checkInsHook).toContain('await updateGuestForSite(weddingSiteId, lastCheckIn.guestId, { checked_in_at: null });');
    expect(checkInsHook).toContain('await updateGuestForSite(weddingSiteId, guest.id, { thank_you_sent_at: nextValue });');
    expect(checkInsHook).toContain('await updateGuestsForSite(weddingSiteId, ids, { thank_you_sent_at: new Date().toISOString() });');
    expect(checkInsHook).toContain('await clearGuestCheckInsForSite(weddingSiteId);');
    expect(checkInsHook).not.toContain("from '../../../lib/supabase'");
    expect(conflictHook).toContain('const visibleRsvpConflicts = useMemo(');
    expect(conflictHook).toContain('const rsvpConflictStats = useMemo<RsvpConflictStats>(() => {');
    expect(conflictHook).toContain('await resolveGuestDashboardConflict(conflictId, resolvedAt);');
    expect(conflictHook).toContain('await resolveGuestDashboardConflicts(ids, resolvedAt);');
    expect(conflictHook).toContain("toast('RSVP item marked done', 'success');");
    expect(conflictHook).not.toContain("from '../../../lib/supabase'");
    expect(derivedStateHelper).toContain('const filteredGuests = guests.filter((guest) => {');
    expect(derivedStateHelper).toContain('const stats = {');
    expect(derivedStateHelper).toContain('const eventReport = effectiveItineraryEvents.map((event) => {');
    expect(derivedStateHelper).toContain('const dueReminderCandidatesGlobal = guests.filter((guest) => !!guest.email && !!guest.invite_token && isDueReminder(guest));');
    expect(derivedStateHelper).toContain('const reminderCandidates = emailableFilteredGuests.filter((guest) => {');
    expect(derivedStateHelper).not.toContain("from '../../../lib/supabase'");
    expect(routeActionsHelper).toContain('const selectUnresolvedGuests = () => {');
    expect(routeActionsHelper).toContain('const getStatusBadge = (status: string) => {');
    expect(routeActionsHelper).toContain("await args.persistReminderSettingsForSite({ auto_reminders_enabled: next });");
    expect(routeActionsHelper).toContain("args.setFilterStatus('no-contact');");
    expect(routeActionsHelper).toContain('onSendSelectedInvitations: () => { void args.handleSendSelectedInvitations(); },');
    expect(routeActionsHelper).not.toContain("from '../../../lib/supabase'");
    expect(uiStateHook).toContain('const [campaignLog, setCampaignLog] = useState<RsvpCampaignLogEntry[]>([]);');
    expect(uiStateHook).toContain('const [campaignPreset, setCampaignPreset] = useState<RsvpCampaignPreset>(\'pending\');');
    expect(uiStateHook).toContain('writeStoredCampaignPreset(campaignPreset);');
    expect(uiStateHook).toContain('writeStoredCampaignLog(campaignLog);');
    expect(uiStateHook).not.toContain("from '../../../lib/supabase'");
    expect(opsHook).toContain('const applyCampaignPreset = useCallback((preset:');
    expect(opsHook).toContain('await persistGuestReminderSettings(weddingSiteId, patch);');
    expect(opsHook).toContain('const handleDeleteAllGuests = useCallback(async () => {');
    expect(opsHook).toContain('const selectFilteredGuests = useCallback(() => {');
    expect(opsHook).toContain('const clearGuestSelection = useCallback(() => {');
    expect(opsHook).toContain('const keepOnlyVisibleSelection = useCallback(() => {');
    expect(opsHook).toContain('await deleteAllGuestsForSite(weddingSiteId);');
    expect(opsHook).not.toContain("from '../../../lib/supabase'");
    expect(crudHook).toContain('const resetForm = () => {');
    expect(crudHook).toContain('const openEditModal = (guest: GuestWithRSVP) => {');
    expect(crudHook).toContain('const handleAddGuest = async (event: FormEvent) => {');
    expect(crudHook).toContain('const handleEditGuest = async (event: FormEvent, editingGuest: GuestWithRSVP | null) => {');
    expect(crudHook).toContain('const handleDeleteGuest = async (guestId: string, confirmDeleteId: string | null) => {');
    expect(crudHook).toContain('await generateSecureGuestInviteToken()');
    expect(crudHook).toContain('await createGuest({');
    expect(crudHook).toContain('await insertEventInvitations(toEventInvitationRows(createdGuestId, realEventIds));');
    expect(crudHook).toContain('const { invitationCount } = await deleteGuestWithDependencies(guestId);');
    expect(crudHook).not.toContain("from '../../../lib/supabase'");
    expect(csvImportHook).toContain('const result = buildGuestImportPreview({');
    expect(csvImportHook).toContain('const { headers, dataRows, samples } = await readGuestImportRows(file);');
    expect(csvImportHook).toContain('const inserted = await insertImportedGuests(guestRows);');
    expect(csvImportHook).toContain('await updateHouseholdGuestIds(ids[0], ids);');
    expect(csvImportHook).toContain('await replaceImportedGuestRsvps(rsvpRows);');
    expect(csvImportHook).toContain('toast(safeGuestImportReadError(err), \'error\')');
    expect(csvImportHook).toContain('resolvedSiteId = userId ? await resolveGuestDashboardSiteId(userId) : null;');
    expect(csvImportHook).not.toContain("from '../../../lib/supabase'");
    expect(viewPropsHelper).toContain('const guestEngagementProps = {');
    expect(viewPropsHelper).toContain('const guestDashboardOpsViewProps = {');
    expect(viewPropsHelper).toContain('const guestRsvpConfigViewProps = {');
    expect(viewPropsHelper).toContain('return {');
    expect(viewPropsHelper).not.toContain("from '../../../lib/supabase'");
    expect(overlayActionsHelper).toContain('onCloseAddModal: () => {');
    expect(overlayActionsHelper).toContain('onCloseEditModal: () => {');
    expect(overlayActionsHelper).toContain('onCloseItineraryDrawer: () => {');
    expect(overlayActionsHelper).toContain("import type { FormEvent } from 'react';");
    expect(overlayActionsHelper).toContain('onSubmitAddGuest: (event: FormEvent<Element>) => { void args.handleAddGuest(event); },');
    expect(overlayActionsHelper).toContain('onSubmitEditGuest: (event: FormEvent<Element>) => { void args.handleEditGuest(event, args.editingGuest); },');
    expect(overlayActionsHelper).not.toContain("from '../../../lib/supabase'");
    expect(dataHook).toContain('const snapshot = await loadGuestDashboardSiteSettings(userId);');
    expect(dataHook).toContain('const snapshot = await loadGuestDashboardSnapshot(weddingSiteId);');
    expect(dataHook).toContain('const snapshot = await loadGuestDashboardItineraryFilters(weddingSiteId);');
    expect(dataHook).toContain('const feed = await loadGuestDashboardRsvpAuditFeed(weddingSiteId);');
    expect(dataHook).toContain('setRsvpQuestions(demoRsvpConfig.questions);');
    expect(dataHook).toContain('setGuests(snapshot.guests);');
    expect(dataHook).toContain('setItineraryEvents(snapshot.itineraryEvents);');
    expect(dataHook).toContain('setRsvpAuditFeed(feed);');
    expect(dataHook).not.toContain("from '../../../lib/supabase'");
    expect(detailHook).toContain('const snapshot = await loadGuestItineraryDrawerSnapshot(weddingSiteId, guest.id);');
    expect(detailHook).toContain('await removeGuestEventInvitation(eventId, itineraryDrawerGuest.id);');
    expect(detailHook).toContain('await addGuestEventInvitation(eventId, itineraryDrawerGuest.id);');
    expect(detailHook).toContain('await saveAssistedGuestRsvp({');
    expect(detailHook).toContain('await refreshGuestDashboardSession();');
    expect(detailHook).toContain('await assignGuestsToHouseholdForSite(weddingSiteId, ids, householdId);');
    expect(detailHook).toContain('await updateGuestHouseholdForSite(weddingSiteId, guestId, null);');
    expect(detailHook).not.toContain("from '../../../lib/supabase'");
    expect(rsvpConfigHook).toContain('const addRsvpQuestionTemplate = useCallback((template: RsvpQuestionTemplate) => {');
    expect(rsvpConfigHook).toContain('const handleSaveRsvpConfig = useCallback(async () => {');
    expect(rsvpConfigHook).toContain('writeStoredDemoRsvpConfig({ questions: cleanedQuestions, mealEnabled: rsvpMealEnabled, mealOptions });');
    expect(rsvpConfigHook).toContain('await persistGuestDashboardRsvpConfig({');
    expect(rsvpConfigHook).toContain('autoSaveTimer.current = window.setTimeout(() => {');
    expect(rsvpConfigHook).not.toContain("from '../../../lib/supabase'");
    expect(service).toContain('export async function assignGuestsToHouseholdForSite(');
    expect(service).toContain('export async function updateGuestHouseholdForSite(');
    expect(service).toContain('export async function persistGuestReminderSettings(');
    expect(service).toContain('resolveActiveSiteForUser(userId)');
    expect(service).toContain('.select(GUEST_SITE_SETTINGS_SELECT)');
    expect(service).toContain(".from('guests')");
    expect(service).toContain('.select(GUEST_DASHBOARD_RSVP_SELECT)');
    expect(service).toContain('.select(GUEST_CONFLICT_SELECT)');
    expect(service).toContain('.select(GUEST_ITINERARY_EVENT_SELECT)');
    expect(service).toContain('.select(GUEST_ITINERARY_SITE_SELECT)');
    expect(service).toContain('.select(GUEST_EVENT_INVITATION_SELECT)');
    expect(service).toContain('.select(GUEST_AUDIT_SELECT)');
    expect(service).toContain('deleteGuestWithDependencies');
    expect(service).toContain('deleteAllGuestsForSite');
    expect(service).toContain('insertImportedGuests');
    expect(source).not.toContain(".from('guests')\n        .select('*')");
    expect(source).not.toContain(".from('wedding_sites')\n        .select('id, couple_name_1, couple_name_2");
    expect(source).not.toContain("supabase.from('rsvps').select('*')");
    expect(source).not.toContain('placeholder="Search guests..."');
    expect(source).not.toContain('placeholder=\"Search guests...\"');
    expect(source).not.toContain('No guests in this segment right now.');
    expect(source).not.toContain('<DashboardPageHero');
    expect(source).not.toContain('Snapshot & RSVP insights');
    expect(source).not.toContain('Campaign insights & reminders');
    expect(source).not.toContain('Recommended next action:');
    expect(source).not.toContain('RSVP follow-up list');
    expect(source).not.toContain(".from('itinerary_events')\n            .select('id, event_name, event_date, start_time, location_name')");
    expect(source).not.toContain(".from('guest_audit_logs')\n          .select('id, guest_id, action, changed_at, changed_by, old_data, new_data')");
    expect(source).not.toContain(".from('event_invitations')\n          .select('id')");
    expect(source).not.toContain(".from('event_invitations')\n          .delete()");
    expect(source).not.toContain(".from('event_invitations')\n          .insert({ event_id: eventId, guest_id: itineraryDrawerGuest.id })");
    expect(source).not.toContain(".from('guests')\n        .update({ rsvp_status: assistedRsvpStatus, rsvp_received_at: recordedAt, notes: nextNotes })");
    expect(source).not.toContain(".from('rsvps')\n        .select('id, notes')");
    expect(source).not.toContain(".from('rsvps')\n          .update(assistedRsvpPayload)");
    expect(source).not.toContain(".from('rsvps')\n          .insert({");
    expect(source).not.toContain('<GuestImportMapperModal');
    expect(source).not.toContain('<GuestImportReviewModal');
    expect(source).not.toContain('renderGuestFormModal');
    expect(source).not.toContain('Record RSVP for guest');
    expect(source).not.toContain(".from('wedding_sites')\n      .select('site_slug')");
    expect(source).not.toContain(".from('wedding_sites')\n      .select('id, site_slug, site_url')");
    expect(source).not.toContain('Match columns');
    expect(source).not.toContain('Review Import');
    expect(source).not.toContain(".from('wedding_sites')\n        .update({ rsvp_custom_questions: cleanedQuestions, rsvp_meal_config: { enabled: rsvpMealEnabled, options: mealOptions } })");
    expect(source).not.toContain(".from('guests')\n        .update({ checked_in_at: null })");
    expect(source).not.toContain(".from('guests')\n        .update({ thank_you_sent_at: nextValue })");
    expect(source).not.toContain(".from('guests')\n        .update({ invitation_sent_at: new Date().toISOString() })");
    expect(source).not.toContain(".from('guests')\n            .update({ invitation_sent_at: sentAtIso, reminder_last_sent_at: sentAtIso })");
    expect(source).not.toContain(".from('guests')\n            .update({ reminder_last_sent_at: new Date().toISOString() })");
    expect(source).not.toContain(".from('guests')\n        .update({ household_id: householdId })");
    expect(source).not.toContain(".from('wedding_sites')\n      .update(patch)");
    expect(source).not.toContain('const exportCSV = (rowsSource: GuestWithRSVP[] = guests, suffix = \'guests\') => {');
    expect(source).not.toContain('const exportEventAttendanceCSV = () => {');
    expect(source).not.toContain('async function copyContactRequestLink() {');
    expect(source).not.toContain('const copySmsRsvpLinksForFiltered = async () => {');
    expect(source).not.toContain('await sendWeddingInvitation({');
    expect(source).not.toContain('<GuestOpsToolbar');
    expect(source).not.toContain('<GuestCampaignReminderPanel');
    expect(source).not.toContain('<GuestSegmentControlsPanel');
    expect(source).not.toContain('Active segment: <span className="font-semibold text-text-primary">');
    expect(source).not.toContain('Some guests have RSVP details that are worth reviewing personally.');
    expect(source).not.toContain('These guests have no email or phone. Add contact info before reminder campaigns.');
    expect(source).not.toContain('Check-in mode active ·');
    expect(source).not.toContain('await resolveActiveSiteForUser(user.id)');
    expect(source).not.toContain("supabase.from('event_invitations').insert(rows)");
    expect(source).not.toContain("supabase.from('event_invitations').insert(eventInviteRows)");
    expect(source).not.toContain("supabase.from('rsvps').insert(rsvpRows)");
    expect(source).not.toContain("supabase.from('guests').delete().eq('id', createdGuestId)");
    expect(source).not.toContain(".from('rsvp_conflicts')\n          .update({ resolved: true, resolved_at: new Date().toISOString() })");
  });

  it('loads itinerary events and event guest picker rows with explicit projections', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/Itinerary.tsx'), 'utf8');
    const service = readFileSync(join(process.cwd(), 'src/pages/dashboard/itineraryService.ts'), 'utf8');
    const actions = readFileSync(join(process.cwd(), 'src/pages/dashboard/useItineraryTimelineActions.ts'), 'utf8');
    const guestManager = readFileSync(join(process.cwd(), 'src/pages/dashboard/EventGuestManagerModal.tsx'), 'utf8');

    expect(source).toContain('<ItineraryDashboardRouteView');
    expect(source).toContain('<EventGuestManagerModal');
    expect(source).toContain('useItineraryTimelineActions({');
    expect(source).not.toContain("from '../../lib/supabase'");
    expect(source).toContain('loadItineraryDashboardEvents(hasEventRsvpsTable)');
    expect(source).toContain('syncItineraryScheduleMirror(siteId, eventList)');
    expect(guestManager).toContain('loadItineraryEventGuestManagerSnapshot(eventId)');
    expect(guestManager).toContain('removeItineraryEventGuestInvitation(eventId, guestId)');
    expect(guestManager).toContain('addItineraryEventGuestInvitation(eventId, guestId)');
    expect(guestManager).toContain('inviteAllGuestsToItineraryEvent(eventId, uninvited.map((guest) => guest.id))');
    expect(guestManager).toContain('removeAllGuestsFromItineraryEvent(eventId)');
    expect(source).not.toContain('supabase.auth.getUser()');
    expect(source).not.toContain("supabase.from('itinerary_events').insert(newEvents.map");
    expect(source).not.toContain(".from('wedding_sites')\n        .select('wedding_data')");
    expect(source).not.toContain(".from('sections')\n        .select('id,data')");
    expect(source).not.toContain('const EVENT_GUEST_PICKER_SELECT = ');
    expect(source).not.toContain("invokeFunctionOrThrow(supabase, 'photo-album-create'");
    expect(source).not.toContain(".from('wedding_sites')\n        .select('id')");
    expect(source).not.toContain(".from('itinerary_events')\n        .select(ITINERARY_EVENT_SELECT)");
    expect(source).not.toContain(".from('event_invitations')\n            .select('id')");
    expect(source).not.toContain(".from('event_rsvps')\n              .select('attending')");
    expect(source).not.toContain(".from('guests')\n        .select(ITINERARY_EVENT_GUEST_PICKER_SELECT)");
    expect(source).not.toContain(".from('event_invitations')\n    .select('guest_id')");
    expect(source).not.toContain(".from('event_invitations')\n    .select('id')");
    expect(source).not.toContain(".from('event_invitations')\n    .upsert([{ event_id: eventId, guest_id: guestId }], { onConflict: 'event_id,guest_id' })");
    expect(source).not.toContain(".from('event_invitations')\n    .delete()");
    expect(source).not.toContain(".from('itinerary_events')\n            .update(updatePayload)");
    expect(source).not.toContain(".from('itinerary_events')\n            .insert([");
    expect(source).not.toContain(".from('itinerary_events')\n        .delete()");
    expect(source).not.toContain(".from('itinerary_events')\n        .update({\n          event_date: event.event_date,");
    expect(source).not.toContain('<DashboardLayout');
    expect(actions).toContain('await saveItineraryEvent({');
    expect(actions).toContain('await deleteItineraryEvent(eventId)');
    expect(actions).toContain('await persistItineraryTimeline(nextEvents)');
    expect(actions).toContain('const siteId = await resolveItinerarySiteId()');
    expect(actions).toContain('await createItineraryTemplateEvents(siteId, newEvents)');
    expect(source).not.toContain('await saveItineraryEvent({');
    expect(source).not.toContain('await deleteItineraryEvent(eventId)');
    expect(source).not.toContain('await persistItineraryTimeline(nextEvents)');
    expect(source).not.toContain('const siteId = await resolveItinerarySiteId()');
    expect(source).not.toContain('await createItineraryTemplateEvents(siteId, newEvents)');
    expect(source).not.toContain('loadItineraryEventGuestManagerSnapshot(eventId)');
    expect(source).not.toContain('removeItineraryEventGuestInvitation(eventId, guestId)');
    expect(source).not.toContain('addItineraryEventGuestInvitation(eventId, guestId)');
    expect(source).not.toContain('inviteAllGuestsToItineraryEvent(eventId, uninvited.map((guest) => guest.id))');
    expect(source).not.toContain('removeAllGuestsFromItineraryEvent(eventId)');
    expect(service).toContain('buildItineraryTemplateInsertRows(weddingSiteId, events)');
    expect(service).toContain('export async function resolveItinerarySiteId()');
    expect(service).toContain("const ITINERARY_EVENT_MANAGER_SITE_SELECT = 'id'");
    expect(service).toContain("const ITINERARY_EVENT_MUTATION_SITE_SELECT = 'id'");
    expect(service).toContain("const ITINERARY_EVENT_LIST_SITE_SELECT = 'id'");
    expect(service).toContain("export const ITINERARY_EVENT_SELECT = 'id, event_name, title, description, event_date, start_time, end_time, location_name, location_address, dress_code, notes, display_order, sort_order, is_visible' as const;");
    expect(service).toContain('export async function loadItineraryDashboardEvents(');
    expect(service).toContain(".select(ITINERARY_EVENT_SELECT)");
    expect(service).toContain("export const ITINERARY_EVENT_GUEST_PICKER_SELECT = 'id, name, first_name, last_name, email' as const;");
    expect(service).toContain('export async function saveItineraryEvent(');
    expect(service).toContain('export async function deleteItineraryEvent(');
    expect(service).toContain('export async function persistItineraryTimeline(');
    expect(service).toContain('export async function loadItineraryEventGuestManagerSnapshot(');
    expect(service).toContain('export async function addItineraryEventGuestInvitation(');
    expect(service).toContain('export async function removeItineraryEventGuestInvitation(');
    expect(service).toContain('export async function inviteAllGuestsToItineraryEvent(');
    expect(service).toContain('export async function removeAllGuestsFromItineraryEvent(');
    expect(service).toContain("const ITINERARY_SCHEDULE_MIRROR_SITE_SELECT = 'wedding_data'");
    expect(service).toContain("const ITINERARY_SCHEDULE_SECTION_SELECT = 'id,data'");
    expect(service).toContain('buildScheduleSectionEvents(eventList)');
    expect(service).toContain('buildWeddingSchedule(eventList)');
    expect(service).toContain('supabase.auth.getUser()');
    expect(source).not.toContain(".from('itinerary_events')\n        .select('*')");
    expect(source).not.toContain(".from('guests')\n        .select('*')");
    expect(guestManager).not.toContain("from '../../lib/supabase'");
  });

  it('loads registry service items with an explicit projection', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/registry/registryService.ts'), 'utf8');

    expect(source).toContain('const REGISTRY_ITEM_SELECT = ');
    expect(source).toContain('.select(REGISTRY_ITEM_SELECT)');
    expect(source).not.toContain(".from('registry_items')\n    .select('*')");
  });

  it('routes registry dashboard bootstrap through a dedicated data hook', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/Registry.tsx'), 'utf8');
    const hookSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/registry/useRegistryDashboardData.ts'), 'utf8');
    const routeContent = readFileSync(join(process.cwd(), 'src/pages/dashboard/registry/RegistryDashboardRouteContent.tsx'), 'utf8');

    expect(source).toContain('useRegistryDashboardData({');
    expect(source).toContain('<RegistryDashboardRouteContent');
    expect(source).not.toContain('const loadItems = useCallback(async (siteId: string) => {');
    expect(source).not.toContain('const site = await loadRegistryDashboardSite(user.id);');
    expect(source).not.toContain('setWeddingSiteId(demoWeddingSite.id);');
    expect(source).not.toContain('setItems(demoRegistryItems.map(toDemoRegistryItem));');
    expect(source).not.toContain('const loadedCap = site.registry_monthly_refresh_cap ?? 100;');
    expect(source).not.toContain('<DashboardPageHero');
    expect(source).not.toContain('Keep gifts helpful, optional, and easy for guests.');
    expect(hookSource).toContain('const [weddingSiteId, setWeddingSiteId] = useState<string | null>(null);');
    expect(hookSource).toContain('const loadItems = useCallback(async (siteId: string) => {');
    expect(hookSource).toContain('const site = await loadRegistryDashboardSite(userId);');
    expect(hookSource).toContain('setWeddingSiteId(demoWeddingSite.id);');
    expect(hookSource).toContain('setItems(demoRegistryItems.map(toDemoRegistryItem));');
    expect(hookSource).toContain('const loadedCap = site.registry_monthly_refresh_cap ?? 100;');
    expect(hookSource).not.toContain("from '../../../lib/supabase'");
    expect(routeContent).toContain('<DashboardPageHero');
    expect(routeContent).toContain('Keep gifts helpful, optional, and easy for guests.');
    expect(routeContent).not.toContain("from '../../../lib/supabase'");
  });

  it('routes registry dashboard derived state through a dedicated helper', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/Registry.tsx'), 'utf8');
    const helperSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/registry/buildRegistryDashboardDerivedState.ts'), 'utf8');

    expect(source).toContain('buildRegistryDashboardDerivedState({');
    expect(source).not.toContain('const counts = {');
    expect(source).not.toContain('const fundStats = normalizedItems.reduce(');
    expect(source).not.toContain('const recentActivity = [...normalizedItems]');
    expect(source).not.toContain('const registryInsights = buildRegistryInsights(');
    expect(source).not.toContain('const alertCounts = {');
    expect(source).not.toContain('const filtered = normalizedItems.filter(item => {');
    expect(helperSource).toContain('const counts = {');
    expect(helperSource).toContain('const fundStats = items.reduce(');
    expect(helperSource).toContain('const recentActivity = [...items]');
    expect(helperSource).toContain('const registryInsights = buildRegistryInsights(');
    expect(helperSource).toContain('const alertCounts = {');
    expect(helperSource).toContain('const filtered = items.filter((item) => {');
    expect(helperSource).not.toContain("from '../../../lib/supabase'");
  });

  it('routes registry maintenance actions through a dedicated hook', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/Registry.tsx'), 'utf8');
    const hookSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/registry/useRegistryMaintenanceActions.ts'), 'utf8');

    expect(source).toContain('useRegistryMaintenanceActions({');
    expect(source).not.toContain('async function handleRefetchMetadata(item: RegistryItem, silent = false, replaceExisting = false) {');
    expect(source).not.toContain('async function handleRefreshImageIssues() {');
    expect(source).not.toContain('async function handleCopyDuplicateReviewList() {');
    expect(source).not.toContain('async function handleRepairBadImports() {');
    expect(source).not.toContain('async function handleAutoRefreshStale(silent = false, alertsOnly = false) {');
    expect(source).not.toContain('async function handleBulkImport() {');
    expect(hookSource).toContain('async function handleRefetchMetadata(item: RegistryItem, silent = false, replaceExisting = false) {');
    expect(hookSource).toContain('async function handleRefreshImageIssues() {');
    expect(hookSource).toContain('async function handleCopyDuplicateReviewList() {');
    expect(hookSource).toContain('async function handleRepairBadImports() {');
    expect(hookSource).toContain('async function handleAutoRefreshStale(silent = false, alertsOnly = false) {');
    expect(hookSource).toContain('async function handleBulkImport(bulkUrls: string) {');
    expect(hookSource).not.toContain("from '../../../lib/supabase'");
  });

  it('routes registry item actions through a dedicated hook', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/Registry.tsx'), 'utf8');
    const hookSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/registry/useRegistryItemActions.ts'), 'utf8');

    expect(source).toContain('useRegistryItemActions({');
    expect(source).not.toContain('async function handleSave(draft: RegistryItemDraft) {');
    expect(source).not.toContain('async function handleDelete(id: string) {');
    expect(source).not.toContain('async function handleMarkPurchased(item: RegistryItem, qty: number) {');
    expect(hookSource).toContain('async function handleSave(draft: RegistryItemDraft) {');
    expect(hookSource).toContain('async function handleDelete(id: string) {');
    expect(hookSource).toContain('async function handleMarkPurchased(item: RegistryItem, qty: number) {');
    expect(hookSource).toContain("toast('Image URL must be a direct image file link");
    expect(hookSource).not.toContain("from '../../../lib/supabase'");
  });

  it('routes registry refresh policy actions through a dedicated hook', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/Registry.tsx'), 'utf8');
    const hookSource = readFileSync(join(process.cwd(), 'src/pages/dashboard/registry/useRegistryRefreshPolicyActions.ts'), 'utf8');

    expect(source).toContain('useRegistryRefreshPolicyActions({');
    expect(source).not.toContain('async function handleSaveRefreshPolicy() {');
    expect(source).not.toContain("function setDefaultRefreshWindowFromWedding() {");
    expect(source).not.toContain("function applyRefreshPreset(preset: 'lean' | 'balanced' | 'aggressive') {");
    expect(source).not.toContain('async function handleResetMonthlyBudgetCounter() {');
    expect(hookSource).toContain('async function handleSaveRefreshPolicy() {');
    expect(hookSource).toContain("function setDefaultRefreshWindowFromWedding() {");
    expect(hookSource).toContain("function applyRefreshPreset(preset: 'lean' | 'balanced' | 'aggressive') {");
    expect(hookSource).toContain('async function handleResetMonthlyBudgetCounter() {');
    expect(hookSource).toContain("toast('Refresh policy saved.')");
    expect(hookSource).not.toContain("from '../../../lib/supabase'");
  });

  it('loads planning service rows with explicit projections', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/planning/planningService.ts'), 'utf8');
    const page = readFileSync(join(process.cwd(), 'src/pages/dashboard/Planning.tsx'), 'utf8');
    const addressTab = readFileSync(join(process.cwd(), 'src/pages/dashboard/planning/AddressCollectionTab.tsx'), 'utf8');
    const songTab = readFileSync(join(process.cwd(), 'src/pages/dashboard/planning/SongRequestsTab.tsx'), 'utf8');

    expect(source).toContain('const PLANNING_TASK_SELECT = ');
    expect(source).toContain('const PLANNING_VENDOR_SELECT = ');
    expect(source).toContain('const PLANNING_BUDGET_ITEM_SELECT = ');
    expect(source).toContain('const PLANNING_SITE_META_SELECT = ');
    expect(source).toContain('const PLANNING_TOTAL_BUDGET_SELECT = ');
    expect(source).toContain('const SEATING_READINESS_EVENT_SELECT = ');
    expect(source).toContain('const ADDRESS_COLLECTION_SITE_SELECT = ');
    expect(source).toContain('const ADDRESS_COLLECTION_GUEST_SELECT = ');
    expect(source).toContain('const SONG_REQUEST_SITE_SELECT = ');
    expect(source).toContain('const SONG_REQUEST_RSVP_SELECT = ');
    expect(source).toContain('.select(PLANNING_TASK_SELECT)');
    expect(source).toContain('const { data, error } = await query(PLANNING_VENDOR_SELECT)');
    expect(source).toContain('const fallback = await query(PLANNING_VENDOR_LEGACY_SELECT)');
    expect(source).toContain('.select(PLANNING_BUDGET_ITEM_SELECT)');
    expect(source).toContain('.select(PLANNING_SITE_META_SELECT)');
    expect(source).toContain('.select(PLANNING_TOTAL_BUDGET_SELECT)');
    expect(source).toContain('.select(SEATING_READINESS_EVENT_SELECT)');
    expect(source).toContain('.select(ADDRESS_COLLECTION_SITE_SELECT)');
    expect(source).toContain('.select(ADDRESS_COLLECTION_GUEST_SELECT)');
    expect(source).toContain('.select(SONG_REQUEST_SITE_SELECT)');
    expect(source).toContain('.select(SONG_REQUEST_RSVP_SELECT)');
    expect(source).not.toContain(".from('planning_tasks')\n    .select('*')");
    expect(source).not.toContain(".from('planning_vendors')\n    .select('*')");
    expect(source).not.toContain(".from('planning_budget_items')\n    .select('*')");
    expect(source).not.toContain('.insert(mutablePayload).select().single()');
    expect(page).toContain('<PlanningDashboardShell');
    expect(page).not.toContain("supabase.from('wedding_sites')");
    expect(page).not.toContain("supabase.from('guests')");
    expect(page).not.toContain("supabase\n        .from('wedding_sites')");
    expect(page).not.toContain('<DashboardLayout');
    expect(page).not.toContain('<DashboardPageHero');
    expect(addressTab).not.toContain("from '../../../lib/supabase'");
    expect(addressTab).not.toContain("supabase.from('wedding_sites')");
    expect(addressTab).not.toContain(".from('guests')");
    expect(songTab).not.toContain("from '../../../lib/supabase'");
    expect(songTab).not.toContain("supabase.from('wedding_sites')");
    expect(songTab).not.toContain(".from('rsvps')");
  });

  it('loads builder editor and media rows with explicit projections', () => {
    const builderProjectSource = readFileSync(join(process.cwd(), 'src/builder/services/builderProjectService.ts'), 'utf8');
    const mediaSource = readFileSync(join(process.cwd(), 'src/builder/services/mediaRepository.ts'), 'utf8');
    const builderPageSource = readFileSync(join(process.cwd(), 'src/builder/BuilderPage.tsx'), 'utf8');

    expect(builderProjectSource).toContain('const BUILDER_PROJECT_SITE_SELECT = ');
    expect(builderProjectSource).toContain('const BUILDER_WEDDING_DATA_SITE_SELECT = ');
    expect(builderProjectSource).toContain('const BUILDER_ENTRY_SITE_SELECT = ');
    expect(builderProjectSource).toContain('.select(BUILDER_PROJECT_SITE_SELECT)');
    expect(builderProjectSource).toContain('.select(BUILDER_WEDDING_DATA_SITE_SELECT)');
    expect(builderProjectSource).toContain('.select(BUILDER_ENTRY_SITE_SELECT)');
    expect(mediaSource).toContain('const BUILDER_MEDIA_ASSET_SELECT = ');
    expect(mediaSource).toContain('.select(BUILDER_MEDIA_ASSET_SELECT)');
    expect(builderPageSource).toContain('builderProjectService.loadEntrySite(activeSite?.id ?? \'\')');
    expect(builderProjectSource).not.toContain(".from('wedding_sites')\n      .select('*')");
    expect(mediaSource).not.toContain(".from('builder_media_assets')\n      .select('*')");
    expect(builderPageSource).not.toContain(".from('wedding_sites')\n        .select('*')");
  });

  it('loads vendor profile rows with an explicit public profile projection', () => {
    const source = readFileSync(join(process.cwd(), 'src/lib/vendorProfiles.ts'), 'utf8');

    expect(source).toContain('const VENDOR_PROFILE_SELECT = ');
    expect(source).toContain('.select(VENDOR_PROFILE_SELECT)');
    expect(source).not.toContain(".from('vendor_profiles')\n      .select('*')");
    expect(source).not.toContain(".from('vendor_profiles')\n    .select('*')");
  });

  it('loads seating service rows with explicit projections', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/seating/seatingService.ts'), 'utf8');
    const page = readFileSync(join(process.cwd(), 'src/pages/dashboard/Seating.tsx'), 'utf8');
    const lookupPage = readFileSync(join(process.cwd(), 'src/pages/dashboard/SeatingLookup.tsx'), 'utf8');
    const dataHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/seating/useSeatingDashboardData.ts'), 'utf8');
    const derivedState = readFileSync(join(process.cwd(), 'src/pages/dashboard/seating/buildSeatingDashboardDerivedState.ts'), 'utf8');
    const artifactsHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/seating/useSeatingDashboardArtifacts.ts'), 'utf8');
    const actionsHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/seating/useSeatingDashboardActions.ts'), 'utf8');
    const interactionHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/seating/useSeatingDashboardInteractionState.ts'), 'utf8');
    const routeContent = readFileSync(join(process.cwd(), 'src/pages/dashboard/seating/SeatingDashboardRouteContent.tsx'), 'utf8');

    expect(source).toContain('const SEATING_EVENT_SELECT = ');
    expect(source).toContain('const SEATING_TABLE_SELECT = ');
    expect(source).toContain('const SEATING_ASSIGNMENT_SELECT = ');
    expect(source).toContain('const SEATING_ELIGIBLE_GUEST_SELECT = ');
    expect(source).toContain('const SEATING_LAYOUT_VERSION_SELECT = ');
    expect(source).toContain('const SEATING_LOOKUP_EVENT_SELECT = ');
    expect(source).toContain('const SEATING_LOOKUP_ASSIGNMENT_SELECT = ');
    expect(source).toContain('const SEATING_LOOKUP_TABLE_SELECT = ');
    expect(source).toContain('const SEATING_LOOKUP_GUEST_SELECT = ');
    expect(source).toContain('.select(SEATING_EVENT_SELECT)');
    expect(source).toContain('.select(SEATING_TABLE_SELECT)');
    expect(source).toContain('.select(SEATING_ASSIGNMENT_SELECT)');
    expect(source).toContain('.select(SEATING_ELIGIBLE_GUEST_SELECT)');
    expect(source).toContain('.select(SEATING_LAYOUT_VERSION_SELECT)');
    expect(source).toContain('.select(SEATING_LOOKUP_EVENT_SELECT)');
    expect(source).toContain('.select(SEATING_LOOKUP_ASSIGNMENT_SELECT)');
    expect(source).toContain('.select(SEATING_LOOKUP_TABLE_SELECT)');
    expect(source).toContain('.select(SEATING_LOOKUP_GUEST_SELECT)');
    expect(source).toContain('export async function refreshSeatingSession()');
    expect(source).toContain('supabase.auth.refreshSession()');
    expect(source).not.toContain(".from('seating_events')\n    .select('*')");
    expect(source).not.toContain(".from('seating_tables')\n    .select('*')");
    expect(source).not.toContain(".from('seating_assignments')\n    .select('*')");
    expect(source).not.toContain(".from('seating_tables')\n    .insert(tables)\n    .select()");
    expect(source).not.toContain(".from('seating_assignments')\n    .upsert(assignments, { onConflict: 'seating_event_id,guest_id' })\n    .select()");
    expect(source).not.toContain(".from('guests')\n    .select('*')");
    expect(source).not.toContain(".from('seating_layout_versions')\n    .select('*')");
    expect(page).toContain('useSeatingDashboardData({ isDemoMode, toast })');
    expect(page).toContain('buildSeatingDashboardDerivedState({');
    expect(page).toContain('useSeatingDashboardArtifacts({');
    expect(page).toContain('useSeatingDashboardActions({');
    expect(page).toContain('useSeatingDashboardInteractionState({');
    expect(page).toContain('<SeatingDashboardRouteContent');
    expect(page).not.toContain("from '../../lib/supabase'");
    expect(page).not.toContain('supabase.auth.refreshSession()');
    expect(page).not.toContain('async function loadInitial()');
    expect(page).not.toContain('async function loadSeatingData()');
    expect(page).not.toContain('const arrivedGuestIds = buildArrivedGuestIdSet(assignments);');
    expect(page).not.toContain('const cateringPacket = buildSeatingCateringPacket({ guests: allGuests, tables, assignments });');
    expect(page).not.toContain('async function handleSaveVersion()');
    expect(page).not.toContain('async function handleRestoreVersion(version: SeatingLayoutVersion)');
    expect(page).not.toContain('function handleExportPDF()');
    expect(page).not.toContain('function handleExportImage()');
    expect(page).not.toContain("const [checkInMode, setCheckInMode] = useState(false);");
    expect(page).not.toContain("const [canvasZoom, setCanvasZoom] = useState(1);");
    expect(page).not.toContain("const [confirmDialog, setConfirmDialog] = useState<null | Omit<ConfirmDialogProps, 'open'>>(null);");
    expect(page).not.toContain('const requestConfirmation = (options: Pick<ConfirmDialogProps,');
    expect(page).not.toContain('const sensors = useSensors(');
    expect(page).not.toContain("const [seatPicker, setSeatPicker] = useState<{ tableId: string; seatIndex: number } | null>(null);");
    expect(page).not.toContain('<DashboardPageHero');
    expect(page).not.toContain('Place guests at tables without losing the room.');
    expect(page).not.toContain('<DndContext');
    expect(page).not.toContain('async function handleCheckDrift()');
    expect(page).not.toContain('async function handleToggleCheckIn(guestId: string, checkedIn: boolean)');
    expect(page).not.toContain('async function handleBulkCheckIn(guestIds: string[], checkedIn: boolean)');
    expect(page).not.toContain('async function handleAutoSeat()');
    expect(page).not.toContain('async function handleAutoCreateTables()');
    expect(page).not.toContain('async function handleReset()');
    expect(dataHook).toContain('const id = await getWeddingSiteId();');
    expect(dataHook).toContain('const events = await loadItineraryEvents(id);');
    expect(dataHook).toContain('const se = await getOrCreateSeatingEvent(siteId, selectedEventId);');
    expect(dataHook).toContain('loadTables(se.id)');
    expect(dataHook).toContain('loadAssignments(se.id)');
    expect(dataHook).toContain('getEligibleGuests(siteId, selectedEventId)');
    expect(dataHook).toContain('await getEventCounters(siteId, selectedEventId, se.id)');
    expect(dataHook).toContain('loadSeatingVersions(se.id)');
    expect(dataHook).toContain('writeDemoSeatingState(selectedEventId, tables, assignments);');
    expect(dataHook).not.toContain("from '../../../lib/supabase'");
    expect(derivedState).toContain('const unassignedGuests = getUnassignedAttendingGuests(args.allGuests, args.assignments);');
    expect(derivedState).toContain('const arrivedGuestIds = buildArrivedGuestIdSet(args.assignments);');
    expect(derivedState).toContain('const checkInCandidates = getCheckInCandidates({');
    expect(derivedState).toContain('const cateringPacket = buildSeatingCateringPacket({');
    expect(derivedState).toContain('const cateringHandoffReview = buildSeatingCateringHandoffReview(cateringPacket);');
    expect(artifactsHook).toContain('async function handleSaveVersion()');
    expect(artifactsHook).toContain('async function handleRestoreVersion(version: SeatingLayoutVersion)');
    expect(artifactsHook).toContain('function handleExportPDF()');
    expect(artifactsHook).toContain('function handleExportImage()');
    expect(artifactsHook).toContain('writeSeatingVersions(allVersions);');
    expect(artifactsHook).toContain('await markSeatingVersionRestored(version.id);');
    expect(interactionHook).toContain("const [checkInMode, setCheckInMode] = useState(false);");
    expect(interactionHook).toContain("const [canvasZoom, setCanvasZoom] = useState(1);");
    expect(interactionHook).toContain("const [confirmDialog, setConfirmDialog] = useState<null | Omit<ConfirmDialogProps, 'open'>>(null);");
    expect(interactionHook).toContain('const requestConfirmation = useCallback((options: Pick<ConfirmDialogProps,');
    expect(interactionHook).toContain('const sensors = useSensors(');
    expect(interactionHook).toContain("const [seatPicker, setSeatPicker] = useState<{ tableId: string; seatIndex: number } | null>(null);");
    expect(interactionHook).toContain('const handleCanvasWheelZoom = useCallback((event: React.WheelEvent<HTMLDivElement>) => {');
    expect(interactionHook).toContain('const openSeatPicker = useCallback((tableId: string, seatIndex: number) => {');
    expect(routeContent).toContain('<DashboardPageHero');
    expect(routeContent).toContain('Place guests at tables without losing the room.');
    expect(routeContent).toContain('<DndContext sensors={props.sensors} onDragStart={props.handleDragStart} onDragEnd={props.handleDragEnd}>');
    expect(routeContent).not.toContain("from '../../lib/supabase'");
    expect(actionsHook).toContain('const clearSeatAssignment = useCallback(async (tableId: string, seatIndex: number) => {');
    expect(actionsHook).toContain('const assignGuestToSeatDirect = useCallback(async (guestId: string, targetTableId: string, targetSeatIndex?: number) => {');
    expect(actionsHook).toContain('async function handleCheckDrift()');
    expect(actionsHook).toContain('await invalidateDriftedAssignments(args.seatingEvent.id, args.selectedEventId, args.siteId);');
    expect(actionsHook).toContain('await refreshSeatingSession();');
    expect(actionsHook).toContain('async function handleBulkCheckIn(guestIds: string[], checkedIn: boolean)');
    expect(lookupPage).not.toContain("from '../../lib/supabase'");
    expect(lookupPage).not.toContain("from '../../lib/activeSite'");
    expect(lookupPage).not.toContain("supabase.from(");
  });

  it('keeps coordinator mode dashboard reads and writes behind its service', () => {
    const page = readFileSync(join(process.cwd(), 'src/pages/dashboard/CoordinatorMode.tsx'), 'utf8');
    const service = readFileSync(join(process.cwd(), 'src/pages/dashboard/coordinator/coordinatorService.ts'), 'utf8');
    const dataHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/coordinator/useCoordinatorDashboardData.ts'), 'utf8');
    const focusActions = readFileSync(join(process.cwd(), 'src/pages/dashboard/coordinator/buildCoordinatorDashboardFocusActions.ts'), 'utf8');
    const boardActions = readFileSync(join(process.cwd(), 'src/pages/dashboard/coordinator/buildCoordinatorDashboardBoardActions.ts'), 'utf8');
    const cueLifecycle = readFileSync(join(process.cwd(), 'src/pages/dashboard/coordinator/useCoordinatorDashboardCueLifecycle.ts'), 'utf8');
    const derivedState = readFileSync(join(process.cwd(), 'src/pages/dashboard/coordinator/buildCoordinatorDashboardDerivedState.ts'), 'utf8');
    const panels = readFileSync(join(process.cwd(), 'src/pages/dashboard/coordinator/CoordinatorModePanels.tsx'), 'utf8');
    const actionsHook = readFileSync(join(process.cwd(), 'src/pages/dashboard/coordinator/useCoordinatorDashboardActions.ts'), 'utf8');

    expect(service).toContain('const COORDINATOR_GUEST_SELECT = ');
    expect(service).toContain('const COORDINATOR_EVENT_SELECT = ');
    expect(service).toContain('const COORDINATOR_EVENT_INVITATION_SELECT = ');
    expect(service).toContain('const COORDINATOR_QNA_SELECT = ');
    expect(service).toContain('const COORDINATOR_QNA_INSERT_SELECT = ');
    expect(service).toContain('.select(COORDINATOR_GUEST_SELECT)');
    expect(service).toContain('.select(COORDINATOR_EVENT_SELECT)');
    expect(service).toContain('.select(COORDINATOR_EVENT_INVITATION_SELECT)');
    expect(service).toContain('.select(COORDINATOR_QNA_SELECT)');
    expect(service).toContain('.select(COORDINATOR_QNA_INSERT_SELECT)');
    expect(service).not.toContain(".from('guests')\n      .select('*')");
    expect(service).not.toContain(".from('itinerary_events')\n      .select('*')");
    expect(service).not.toContain(".from('guest_qna_items')\n      .select('*')");
    expect(page).toContain('useCoordinatorDashboardData({');
    expect(page).toContain('buildCoordinatorDashboardFocusActions({');
    expect(page).toContain('buildCoordinatorDashboardBoardActions({');
    expect(page).toContain('buildCoordinatorDashboardDerivedState({');
    expect(page).toContain('useCoordinatorDashboardActions({');
    expect(page).toContain('useCoordinatorDashboardCueLifecycle({');
    expect(page).toContain('<CoordinatorQnaPanel');
    expect(page).not.toContain('const bootstrap = await loadCoordinatorBootstrapData(user.id);');
    expect(page).not.toContain('const storedTimelineState = readStoredCoordinatorTimelineState(siteId);');
    expect(page).not.toContain("const jumpToOpsSnapshotLane = (key: 'check-in' | 'timeline' | 'qna' | 'alerting') => {");
    expect(page).not.toContain('const clearCoordinatorTransientState = () => {');
    expect(page).not.toContain('const runPrimaryAction = () => {');
    expect(page).not.toContain('const runTimelineAction = (eventId: string, nextState: TimelineState | null) => {');
    expect(page).not.toContain('const runEscalationIssue = (item: (typeof liveIssues)[number]) => {');
    expect(page).not.toContain('const sortedGuests = sortCoordinatorGuests(args.guests);');
    expect(page).not.toContain('const alertStats = {');
    expect(page).not.toContain('const standingPromptMode = getCoordinatorStandingPromptMode(Boolean(summaryDisplayCue));');
    expect(page).not.toContain('No guest questions match this triage view right now.');
    expect(page).not.toContain('placeholder="Add a guest question"');
    expect(page).not.toContain('const toggleCheckIn = async (guest: GuestLiteForCoordinator) => {');
    expect(page).not.toContain('const sendDayOfAlert = async () => {');
    expect(page).not.toContain('const addQnaItem = async () => {');
    expect(page).not.toContain('if (shouldResetCoordinatorCommandJumpLabel({');
    expect(page).not.toContain('const timer = window.setTimeout(() => {');
    expect(dataHook).toContain('const bootstrap = await loadCoordinatorBootstrapData(args.userId);');
    expect(dataHook).toContain('const storedTimelineState = readStoredCoordinatorTimelineState(siteId);');
    expect(dataHook).toContain("writeStoredCoordinatorSessionState(siteId, {");
    expect(dataHook).toContain("writePlannerAccessRole('coordinator', siteId, coordinatorRole);");
    expect(focusActions).toContain('export function buildCoordinatorDashboardFocusActions(');
    expect(focusActions).toContain("const jumpToOpsSnapshotLane = (key: 'check-in' | 'timeline' | 'qna' | 'alerting') => {");
    expect(focusActions).toContain("args.setQnaInput(buildCoordinatorDoorEscalationPrompt(guest));");
    expect(focusActions).toContain("args.setAlertForm((prev) => applyCoordinatorAlertSuggestion({ form: prev, suggestion: args.preferredAlertSuggestion! }));");
    expect(boardActions).toContain('export function buildCoordinatorDashboardBoardActions(');
    expect(boardActions).toContain('const runPrimaryAction = () => {');
    expect(boardActions).toContain("args.setTimelineState((prev) => setCoordinatorEventTimelineState(prev, eventId, nextState));");
    expect(boardActions).toContain("await args.updateCoordinatorQnaAnswer(id, nextItem);");
    expect(derivedState).toContain('export function buildCoordinatorDashboardDerivedState(args: Args)');
    expect(derivedState).toContain('const sortedGuests = sortCoordinatorGuests(args.guests);');
    expect(derivedState).toContain('const alertStats = {');
    expect(derivedState).toContain('const standingPromptMode: \'full\' | \'secondary\' = getCoordinatorStandingPromptMode(Boolean(summaryDisplayCue));');
    expect(derivedState).toContain('const filteredAlertLogView = buildCoordinatorAlertLogView(filteredAlertLog);');
    expect(panels).toContain('export function CoordinatorQnaPanel(');
    expect(panels).toContain("placeholder=\"Add a guest question\"");
    expect(panels).toContain('No guest questions match this triage view right now.');
    expect(panels).toContain('Jump to suggested question');
    expect(actionsHook).toContain('export function useCoordinatorDashboardActions(args: Args)');
    expect(actionsHook).toContain('const toggleCheckIn = async (guest: GuestLiteForCoordinator) => {');
    expect(actionsHook).toContain('await updateCoordinatorGuestCheckIn({ siteId: args.siteId, guestId: guest.id, checkedInAt: next });');
    expect(actionsHook).toContain('const sendDayOfAlert = async () => {');
    expect(actionsHook).toContain('await createCoordinatorAlertMessage({');
    expect(actionsHook).toContain('const addQnaItem = async () => {');
    expect(actionsHook).toContain('const data = await createCoordinatorQnaQuestion(args.siteId, q);');
    expect(cueLifecycle).toContain('export function useCoordinatorDashboardCueLifecycle(');
    expect(cueLifecycle).toContain('shouldResetCoordinatorCommandJumpLabel({');
    expect(cueLifecycle).toContain("const timer = window.setTimeout(() => {");
    expect(cueLifecycle).toContain('shouldExpireCoordinatorOverrideCue({');
    expect(page).not.toContain("from '../../lib/supabase'");
    expect(page).not.toContain("from '../../lib/activeSite'");
    expect(page).not.toContain("supabase.from(");
  });

  it('loads name-change planner rows with explicit projections', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/planning/nameChangeService.ts'), 'utf8');

    expect(source).toContain('const NAME_CHANGE_CASE_SELECT = ');
    expect(source).toContain('const NAME_CHANGE_DOCUMENT_SELECT = ');
    expect(source).toContain('const NAME_CHANGE_EXTRACTED_FIELD_SELECT = ');
    expect(source).toContain('const NAME_CHANGE_PLAN_SNAPSHOT_SELECT = ');
    expect(source).toContain('const NAME_CHANGE_REMINDER_SELECT = ');
    expect(source).toContain('.select(NAME_CHANGE_CASE_SELECT)');
    expect(source).toContain('.select(NAME_CHANGE_DOCUMENT_SELECT)');
    expect(source).toContain('.select(NAME_CHANGE_EXTRACTED_FIELD_SELECT)');
    expect(source).toContain('.select(NAME_CHANGE_PLAN_SNAPSHOT_SELECT)');
    expect(source).toContain('.select(NAME_CHANGE_REMINDER_SELECT)');
    expect(source).toContain('function toPersistedNameChangeReminderRow');
    expect(source).toContain('toPersistedNameChangeReminderRow(reminder, caseId)');
    expect(source).not.toContain(".from('name_change_cases').select('*')");
    expect(source).not.toContain(".from('name_change_documents').select('*')");
    expect(source).not.toContain(".from('name_change_extracted_fields').select('*')");
    expect(source).not.toContain(".from('name_change_plan_snapshots').select('*')");
    expect(source).not.toContain(".from('name_change_reminders').select('*')");
    expect(source).not.toContain('.upsert(payload, { onConflict: \'wedding_site_id\' })\n    .select()\n    .single()');
  });

  it('loads vault dashboard rows with explicit projections', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/Vault.tsx'), 'utf8');
    const service = readFileSync(join(process.cwd(), 'src/pages/dashboard/vaultService.ts'), 'utf8');
    const actions = readFileSync(join(process.cwd(), 'src/pages/dashboard/useVaultDashboardActions.ts'), 'utf8');
    const liveContent = readFileSync(join(process.cwd(), 'src/pages/dashboard/VaultDashboardLiveContent.tsx'), 'utf8');

    expect(source).not.toContain("from '../../lib/supabase'");
    expect(source).toContain('<VaultDashboardRouteView');
    expect(source).toContain('<VaultDashboardLiveContent');
    expect(source).toContain('useVaultDashboardActions({');
    expect(service).toContain('export const VAULT_CONFIG_SELECT = ');
    expect(service).toContain('export const VAULT_ENTRY_SELECT = ');
    expect(service).toContain('const VAULT_SITE_SELECT = ');
    expect(service).toContain('.select(VAULT_CONFIG_SELECT)');
    expect(service).toContain('.select(VAULT_ENTRY_SELECT)');
    expect(service).toContain('.select(VAULT_SITE_SELECT)');
    expect(source).not.toContain(".from('vault_configs')\n            .select('*')");
    expect(source).not.toContain(".from('vault_entries')\n              .select('*')");
    expect(source).not.toContain(".from('vault_configs')\n        .select('*')");
    expect(source).not.toContain(".from('vault_entries')\n          .select('*')");
    expect(source).not.toContain("supabase.from('vault_entries')");
    expect(source).not.toContain("supabase.from('vault_configs')");
    expect(source).not.toContain(".from('wedding_sites')");
    expect(source).not.toContain("supabase.functions.invoke('vault-resolve-entry-link'");
    expect(source).not.toContain("supabase.functions.invoke('google-drive-health'");
    expect(source).not.toContain("supabase.functions.invoke('google-drive-auth-start'");
    expect(source).not.toContain("supabase.functions.invoke('google-drive-auth-callback'");
    expect(source).toContain('resolveVaultEntryLinkFromService(entry.id)');
    expect(source).toContain('checkVaultGoogleDriveHealth(weddingSiteId)');
    expect(source).toContain('startVaultGoogleDriveAuth(weddingSiteId)');
    expect(source).toContain('finishVaultGoogleDriveAuth(googleCode, googleState)');
    expect(actions).toContain('await sendAnniversaryReminder({');
    expect(actions).toContain('const created = await createVaultConfig({');
    expect(actions).toContain('const configs = await seedStarterVaultConfigs(weddingSiteId)');
    expect(actions).toContain('await updateVaultEnabled(configId, enabled)');
    expect(actions).toContain('await updateVaultConfig({ id, label, durationYears })');
    expect(actions).toContain('created = await createVaultEntry(weddingSiteId, entry)');
    expect(actions).toContain('await deleteVaultEntry(id)');
    expect(actions).toContain('await deleteVaultConfigWithEntryRollback(configId, deletedEntries)');
    expect(liveContent).toContain('export function VaultDashboardLiveContent({');
    expect(liveContent).toContain('<DashboardPageHero');
    expect(liveContent).toContain('Create 1, 5, and 10 year vaults');
    expect(liveContent).toContain('How Vaults work');
    expect(source).not.toContain('<DashboardLayout');
    expect(source).not.toContain('<DashboardStateBlock');
    expect(source).not.toContain('Create 1, 5, and 10 year vaults');
    expect(service).toContain('export async function resolveVaultEntryLink(entryId: string): Promise<string | null>');
    expect(service).toContain('export async function checkVaultGoogleDriveHealth(siteId: string): Promise<{');
    expect(service).toContain('export async function startVaultGoogleDriveAuth(siteId: string): Promise<string>');
    expect(service).toContain('export async function finishVaultGoogleDriveAuth(code: string, state: string): Promise<{');
    expect(service).not.toContain(".from('vault_configs')\n    .select('*')");
    expect(service).not.toContain(".from('vault_entries')\n    .select('*')");
    expect(service).not.toContain(".from('wedding_sites')\n    .select('*')");
    expect(source).not.toContain(".select('*');");
    expect(source).not.toContain('await sendAnniversaryReminder({');
    expect(source).not.toContain('const created = await createVaultConfig({');
    expect(source).not.toContain('const configs = await seedStarterVaultConfigs(weddingSiteId)');
    expect(source).not.toContain('await updateVaultEnabled(configId, enabled)');
    expect(source).not.toContain('await updateVaultConfig({ id, label, durationYears })');
    expect(source).not.toContain('created = await createVaultEntry(weddingSiteId, entry)');
    expect(source).not.toContain('await deleteVaultEntry(id)');
    expect(source).not.toContain('await deleteVaultConfigWithEntryRollback(configId, deletedEntries)');
  });

  it('keeps overview intelligence persistence behind its service', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/Overview.tsx'), 'utf8');
    const service = readFileSync(join(process.cwd(), 'src/pages/dashboard/overviewService.ts'), 'utf8');
    const actions = readFileSync(join(process.cwd(), 'src/pages/dashboard/useOverviewIntelligenceActions.ts'), 'utf8');
    const model = readFileSync(join(process.cwd(), 'src/pages/dashboard/buildOverviewDashboardModel.ts'), 'utf8');
    const snapshotState = readFileSync(join(process.cwd(), 'src/pages/dashboard/buildOverviewSnapshotState.ts'), 'utf8');
    const liveContent = readFileSync(join(process.cwd(), 'src/pages/dashboard/OverviewDashboardLiveContent.tsx'), 'utf8');

    expect(source).toContain('<OverviewDashboardRouteView');
    expect(source).toContain('<OverviewDashboardLiveContent');
    expect(source).toContain('useOverviewIntelligenceActions({');
    expect(source).toContain('buildOverviewDashboardModel({');
    expect(source).toContain('buildOverviewSiteDraftState(site)');
    expect(source).toContain('buildNameChangeOverviewSnapshotState(workspace)');
    expect(source).toContain('buildOverviewStatsFromSnapshot({');
    expect(source).toContain('loadOverviewDashboardSnapshot(user.id)');
    expect(source).toContain('loadOverviewInteractiveData(slug)');
    expect(source).not.toContain('<DashboardLayout');
    expect(source).not.toContain('<DashboardStateBlock');
    expect(source).not.toContain("supabase.from('interactive_suggestions').update({ is_hidden: true })");
    expect(source).not.toContain('intelligenceDismissals: next');
    expect(source).not.toContain("supabase.from('wedding_sites')");
    expect(source).not.toContain("supabase.from('guests')");
    expect(source).not.toContain("supabase.from('interactive_suggestions')");
    expect(source).not.toContain("supabase.from('interactive_votes')");
    expect(actions).toContain('await markOverviewBuilderFieldAsUserEdited(stats.siteId, fieldPath)');
    expect(actions).toContain('const seed = await loadOverviewDraftRefreshSeed(stats.siteId)');
    expect(actions).toContain('await updateOverviewDraftRefresh(stats.siteId, {');
    expect(actions).toContain('void persistOverviewIntelligenceDismissals(stats.siteId, next).catch(() => {})');
    expect(actions).toContain('await hideInteractiveSuggestion(id)');
    expect(model).toContain('const websiteInviteAnalytics = buildWebsiteInviteAnalyticsReadiness({');
    expect(model).toContain('const publishReadinessItems: OverviewChecklistItem[] = buildPublishReadinessItems({');
    expect(model).toContain('const calmDigest = stats ? buildCalmOwnerDigest({');
    expect(snapshotState).toContain('export function buildDemoOverviewSnapshotState()');
    expect(snapshotState).toContain('export function buildOverviewSiteDraftState(site: {');
    expect(snapshotState).toContain('export function buildNameChangeOverviewSnapshotState(workspace:');
    expect(snapshotState).toContain('export function buildOverviewStatsFromSnapshot({');
    expect(liveContent).toContain('export function OverviewDashboardLiveContent({');
    expect(liveContent).toContain('A calmer place to plan {coupleLabel}.');
    expect(liveContent).toContain('<CardTitle>Your wedding site</CardTitle>');
    expect(service).toContain("const OVERVIEW_DISMISSALS_SITE_SELECT = 'wedding_data'");
    expect(service).toContain("const OVERVIEW_SITE_SELECT = 'id, site_slug, site_url, is_published, site_json, updated_at, template_id, wedding_data, onboarding_answers, couple_name_1, couple_name_2, venue_name, wedding_date, venue_date, wedding_location'");
    expect(service).toContain('.select(OVERVIEW_DISMISSALS_SITE_SELECT)');
    expect(service).toContain('.select(OVERVIEW_SITE_SELECT)');
    expect(service).toContain('.select(OVERVIEW_GUEST_SELECT)');
    expect(service).not.toContain(".from('wedding_sites')\n    .select('*')");
    expect(source).not.toContain('await markOverviewBuilderFieldAsUserEdited(stats.siteId, fieldPath)');
    expect(source).not.toContain('const seed = await loadOverviewDraftRefreshSeed(stats.siteId)');
    expect(source).not.toContain('await updateOverviewDraftRefresh(stats.siteId, {');
    expect(source).not.toContain('void persistOverviewIntelligenceDismissals(stats.siteId, next).catch(() => {})');
    expect(source).not.toContain('await hideInteractiveSuggestion(id)');
    expect(model).not.toContain("from '../../lib/supabase'");
    expect(snapshotState).not.toContain("from '../../lib/supabase'");
    expect(source).not.toContain('A calmer place to plan {coupleLabel}.');
  });

  it('keeps guest photo bucket persistence behind its service', () => {
    const source = readFileSync(join(process.cwd(), 'src/pages/dashboard/GuestPhotoSharing.tsx'), 'utf8');
    const service = readFileSync(join(process.cwd(), 'src/pages/dashboard/guestPhotoSharingService.ts'), 'utf8');
    const albumActions = readFileSync(join(process.cwd(), 'src/pages/dashboard/guestPhotos/useGuestPhotoAlbumActions.ts'), 'utf8');
    const liveContent = readFileSync(join(process.cwd(), 'src/pages/dashboard/guestPhotos/GuestPhotoDashboardLiveContent.tsx'), 'utf8');

    expect(source).toContain('loadGuestPhotoDashboardSnapshot(userId)');
    expect(source).toContain('persistGuestPhotoBuckets(siteId, nextBuckets)');
    expect(source).toContain('await saveGuestPhotoHubSettings(siteId, hubSettings)');
    expect(source).toContain('await moderateGuestbookEntryFromService(entryId, patch)');
    expect(source).toContain('await persistGuestPhotoAiOpsPlan(siteId, plan)');
    expect(source).toContain('await moveGuestPhotoUploadToBucket(siteId, move.uploadId, move.targetBucketId)');
    expect(source).toContain('await createGuestPhotoBucketCorrection(siteId, analysis, action, chosenBucketId, reason)');
    expect(source).toContain("await analyzeGuestPhotoUploads(siteId, uploadIds, force, force ? 'vision' : 'auto')");
    expect(source).toContain('await exportGuestPhotoManifest(siteId, showHidden)');
    expect(source).toContain("await moderateGuestPhotoUploads(ids, { is_hidden: hide })");
    expect(source).toContain('useGuestPhotoAlbumActions({');
    expect(source).toContain('resolveGuestPhotoDashboardUserId()');
    expect(source).toContain('refreshGuestPhotoSession()');
    expect(source).toContain('queueGuestPhotoFollowupsFromService(siteId, kind)');
    expect(source).toContain('<GuestPhotoDashboardLiveContent');
    expect(liveContent).toContain('<GuestPhotoHeroCard');
    expect(liveContent).toContain('<GuestPhotoMemoryVaultsCard');
    expect(liveContent).toContain('<GuestPhotoMemoryFlowCard');
    expect(liveContent).toContain('<GuestPhotoHubQrCard');
    expect(liveContent).toContain('<GuestPhotoRecapSharingCard');
    expect(liveContent).toContain('<GuestPhotoHubControlsCard');
    expect(liveContent).toContain('<GuestPhotoFollowupCard');
    expect(liveContent).toContain('<GuestPhotoGuestbookCard');
    expect(liveContent).toContain('<GuestPhotoCoupleAlbumsCard');
    expect(liveContent).toContain('<GuestPhotoAlbumCreateCard');
    expect(liveContent).toContain('<GuestPhotoAlbumListState');
    expect(liveContent).toContain('<GuestPhotoAlbumControls');
    expect(liveContent).toContain('<GuestPhotoBucketList');
    expect(liveContent).toContain('<GuestPhotoQuickStartBanner');
    expect(liveContent).toContain('<GuestPhotoStatsCards');
    expect(liveContent).toContain('<GuestPhotoSlideshowDraftCard');
    expect(liveContent).toContain('<GuestPhotoSlideshowCard');
    expect(liveContent).toContain('<GuestPhotoMomentsCard');
    expect(liveContent).toContain('<GuestPhotoMomentAlbumsCard');
    expect(liveContent).toContain('<GuestPhotoOrganizerCard');
    expect(liveContent).toContain('<GuestPhotoReviewCard');
    expect(albumActions).toContain('await createGuestPhotoAlbum({');
    expect(albumActions).toContain("await manageGuestPhotoAlbum({ action: 'regenerate_link', albumId: bucketId })");
    expect(albumActions).toContain("await manageGuestPhotoAlbum({ action: 'set_window', albumId: bucketId, opensAt, closesAt })");
    expect(source).not.toContain('supabase.auth.getUser()');
    expect(source).not.toContain('supabase.auth.getSession()');
    expect(source).not.toContain('supabase.auth.refreshSession()');
    expect(source).not.toContain("supabase.from('wedding_sites')");
    expect(source).not.toContain("supabase.from('itinerary_events')");
    expect(source).not.toContain("supabase.from('photo_albums')");
    expect(source).not.toContain("supabase.from('photo_uploads')");
    expect(source).not.toContain("supabase.from('guestbook_entries')");
    expect(source).not.toContain("supabase.from('guest_prospect_optins')");
    expect(source).not.toContain("supabase.from('photo_upload_ai_analysis')");
    expect(source).not.toContain("supabase.from('photo_upload_metadata')");
    expect(source).not.toContain("supabase.from('photo_ai_bucket_corrections')");
    expect(source).not.toContain("supabase.from('guest_hub_settings')");
    expect(source).not.toContain(".from('wedding_sites')\n      .select('wedding_data')");
    expect(source).not.toContain(".from('guest_hub_settings')\n        .upsert({");
    expect(source).not.toContain(".from('guestbook_entries')\n        .update({ ...patch, moderated_at: new Date().toISOString() })");
    expect(source).not.toContain(".from('photo_uploads')\n          .update({ photo_album_id: move.targetBucketId })");
    expect(source).not.toContain(".from('photo_ai_bucket_corrections')\n      .insert(payload)");
    expect(source).not.toContain('resolveActiveSiteForUser(userId)');
    expect(source).not.toContain("invokeOrThrow('photo-analyze-batch'");
    expect(source).not.toContain("invokeOrThrow('photo-export-manifest'");
    expect(source).not.toContain("invokeOrThrow('photo-upload-moderate'");
    expect(source).not.toContain("invokeOrThrow('photo-album-manage'");
    expect(source).not.toContain("invokeGuestPhotoOwnerFunction<PhotoAlbumCreateResponse>('photo-album-create'");
    expect(source).not.toContain("supabase.from('wedding_sites').update({ wedding_data: nextWeddingData, site_json: nextSiteJson })");
    expect(source).not.toContain('<GuestPhotoHeroCard');
    expect(source).not.toContain('<GuestPhotoQuickStartBanner');
    expect(source).not.toContain('<GuestPhotoAlbumListState');
    expect(source).not.toContain('Create simple photo albums, share one upload link or QR code, and let guests send photos without making an account.');
    expect(source).not.toContain('Albums collect the weekend. Vaults keep the pieces you want to revisit later.');
    expect(source).not.toContain('Know what is ready before the QR goes on a sign.');
    expect(source).not.toContain('Print this single link on signage. Guests can RSVP, upload photos or video, leave a guestbook note, and find guest update flows without installing anything.');
    expect(source).not.toContain('Control when the photo recap is guest-facing.');
    expect(source).not.toContain('Choose which no-login guest actions are available from the one QR code. Turning photos off also blocks upload links and the public recap.');
    expect(source).not.toContain('Guests who asked for recap updates or want to hear about using dayof later.');
    expect(source).not.toContain('Written messages submitted from the one-QR hub.');
    expect(source).not.toContain('Create your own couple-photo albums here so uploads stay organized by the moments and photo types you actually care about.');
    expect(source).not.toContain('Copy links, QR codes, and guest-facing prompts without digging through menus.');
    expect(source).not.toContain('Share one clean upload destination for this album.');
    expect(source).not.toContain('Recent uploads');
    expect(source).not.toContain('Next up: add photos, then review your draft');
    expect(source).not.toContain('Blank album sheet');
    expect(source).not.toContain('No albums match those filters. Try a different search, switch the status filter, or clear your hidden / flagged view.');
    expect(source).not.toContain('<GuestPhotoBucketCard');
    expect(source).not.toContain('<GuestPhotoBucketWindowEditor');
    expect(source).not.toContain('<GuestPhotoRecentUploadsList');
    expect(source).not.toContain('Turn uploaded guest photos into a simple slideshow. Start with your strongest moments, preview the sequence, then polish later.');
    expect(source).not.toContain('Sort new guest photos into the moments they belong to, then reuse that work for albums, slideshow order, captions, and quality checks.');
    expect(source).not.toContain('Moment albums from the schedule');
    expect(source).not.toContain('Created an organization and slideshow plan for review.');
    expect(source).not.toContain('Photo review');
    expect(source).not.toContain('Add at least three visible uploads to an active album to start a slideshow draft.');
    expect(service).toContain("const GUEST_PHOTO_BUCKET_SITE_SELECT = 'wedding_data, site_json'");
    expect(service).toContain("const GUEST_PHOTO_DASHBOARD_SITE_SELECT = 'id, site_slug, wedding_data'");
    expect(service).toContain("const GUEST_PHOTO_EVENT_SELECT = 'id,event_name,event_date,start_time,end_time' as const;");
    expect(service).toContain("const GUEST_PHOTO_ALBUM_SELECT = 'id,name,slug,parent_album_id,hierarchy_label,drive_folder_url,is_active,created_at,itinerary_event_id,opens_at,closes_at' as const;");
    expect(service).toContain("const GUEST_PHOTO_UPLOAD_SELECT = 'id,photo_album_id,original_filename,guest_name,guest_email,note,mime_type,size_bytes,drive_web_view_link,is_hidden,is_flagged,recap_hidden,recap_featured,recap_story,uploaded_at' as const;");
    expect(service).toContain('export async function loadGuestPhotoDashboardSnapshot(userId: string): Promise<GuestPhotoDashboardSnapshot>');
    expect(service).toContain('export async function saveGuestPhotoHubSettings(');
    expect(service).toContain('export async function moderateGuestbookEntry(');
    expect(service).toContain('export async function persistGuestPhotoAiOpsPlan(');
    expect(service).toContain('export async function moveGuestPhotoUploadToBucket(');
    expect(service).toContain('export async function createGuestPhotoBucketCorrection(');
    expect(service).toContain('export async function analyzeGuestPhotoUploads(');
    expect(service).toContain('export async function createGuestPhotoAlbum(');
    expect(service).toContain('export async function exportGuestPhotoManifest(');
    expect(service).toContain('export async function moderateGuestPhotoUploads(');
    expect(service).toContain('export async function manageGuestPhotoAlbum(');
    expect(service).toContain('export async function refreshGuestPhotoSession(): Promise<boolean>');
    expect(service).toContain('export async function getGuestPhotoCurrentUserId(): Promise<string | null>');
    expect(service).toContain('export async function resolveGuestPhotoDashboardUserId(): Promise<string | null>');
    expect(service).toContain('export async function invokeGuestPhotoOwnerFunction<T = unknown>(');
    expect(service).toContain("export async function queueGuestPhotoFollowups(");
    expect(service).toContain('supabase.auth.getUser()');
    expect(service).toContain('supabase.auth.getSession()');
    expect(service).toContain('supabase.auth.refreshSession()');
    expect(service).toContain('resolveActiveSiteForUser(userId)');
    expect(service).toContain("const data = await invokeFunctionOrThrow(supabase, fnName, body);");
    expect(service).toContain("return await invokeGuestPhotoOwnerFunction<{ queued?: number }>('queue-guest-followups', { siteId, kind })");
    expect(service).toContain("return await invokeGuestPhotoOwnerFunction<{ analyzed?: number; skipped?: number; results?: PhotoUploadAiAnalysisRow[] }>('photo-analyze-batch', {");
    expect(service).toContain("return await invokeGuestPhotoOwnerFunction<{");
    expect(service).toContain("return await invokeGuestPhotoOwnerFunction<{ rows?: Array<Record<string, unknown>> }>('photo-export-manifest', {");
    expect(service).toContain("await invokeGuestPhotoOwnerFunction('photo-upload-moderate', { uploadIds, patch });");
    expect(service).toContain("return await invokeGuestPhotoOwnerFunction<Record<string, unknown>>('photo-album-manage', body);");
    expect(service).toContain('.select(GUEST_PHOTO_BUCKET_SITE_SELECT)');
    expect(service).toContain('.select(GUEST_PHOTO_DASHBOARD_SITE_SELECT)');
    expect(service).toContain('.select(GUEST_PHOTO_EVENT_SELECT)');
    expect(service).toContain('.select(GUEST_PHOTO_ALBUM_SELECT)');
    expect(service).toContain('.select(GUEST_PHOTO_UPLOAD_SELECT)');
    expect(service).not.toContain(".from('wedding_sites')\n    .select('*')");
  });
});
