export function buildGuestDashboardViewProps(args: any) {
  const guestEngagementProps = {
    activeSegmentLabel: args.segmentLabelMap[args.filterStatus] || args.filterStatus,
    autoRemindersEnabled: args.autoRemindersEnabled,
    bulkSending: args.bulkSending,
    canEditGuests: args.canEditGuests,
    campaignPreset: args.campaignPreset,
    campaignReadiness: args.campaignReadiness,
    checkInMode: args.checkInMode,
    checkedInCount: args.guests.filter((g: any) => !!g.checked_in_at).length,
    cleanGuestsView: args.cleanGuestsView,
    contactNoContactCount: args.contactStats.withNoContact,
    csvFileInputRef: args.csvFileInputRef,
    csvImporting: args.csvImporting,
    csvMaxFileMb: args.csvMaxFileMb,
    csvMaxRows: args.csvMaxRows,
    csvSelectedFilename: args.csvSelectedFilename,
    daysToWedding: args.daysToWedding,
    dueReminderCount: args.dueReminderCandidatesGlobal.length,
    extraFilterCount: args.extraFilters.length,
    filterStatus: args.filterStatus,
    guestCount: args.guests.length,
    hasNextUnresolvedGuest: Boolean(args.nextUnresolvedGuest),
    isDemoMode: args.isDemoMode,
    lastCheckInGuestName: args.lastCheckIn?.guestName ?? null,
    manualFollowUpCount: args.filteredGuests.filter((guest: any) => args.fallbackByGuest.get(guest.id)?.state === 'manual-follow-up').length,
    manualHandledCount: args.filteredGuests.filter((guest: any) => args.fallbackByGuest.get(guest.id)?.state === 'manual-handled').length,
    reminderCandidateCount: args.reminderCandidates.length,
    reminderCandidates: args.reminderCandidates.map((guest: any) => ({
      email: guest.email ?? null,
      id: guest.id,
      name: (guest.first_name || guest.last_name)
        ? `${guest.first_name ?? ''} ${guest.last_name ?? ''}`.trim()
        : guest.name,
    })),
    rsvpOps: args.rsvpOps,
    searchQuery: args.searchQuery,
    segmentOptions: [
      { value: 'all', label: `All (${args.stats.total})` },
      { value: 'confirmed', label: `Confirmed (${args.stats.confirmed})` },
      { value: 'declined', label: `Declined (${args.stats.declined})` },
      { value: 'pending', label: `Pending (${args.stats.pending})` },
    ],
    selectedGuestCount: args.selectedGuestIds.size,
    showCampaignModal: args.showCampaignModal,
    showExceptionBanner: args.filteredGuests.some((guest: any) => (args.exceptionStateByGuest.get(guest.id) || []).length > 0) && args.filterStatus === 'all',
    showMissingMealBanner: args.filterStatus === 'missing-meal',
    showNoContactBanner: args.filterStatus === 'no-contact',
    showOpsMenu: args.showOpsMenu,
    showRecipientPreview: args.showRecipientPreview,
    skipRecentlyInvited: args.skipRecentlyInvited,
    viewMode: args.viewMode,
    visibleSelectedCount: args.filteredGuests.filter((g: any) => args.selectedGuestIds.has(g.id)).length,
    onAddGuest: args.onAddGuest,
    onApplyCampaignPreset: args.onApplyCampaignPreset,
    onClearAllCheckIns: args.onClearAllCheckIns,
    onClearFilters: args.onClearFilters,
    onClearSelection: args.onClearSelection,
    onCopyAddressCollectionLink: args.onCopyAddressCollectionLink,
    onCopyChecklist: args.onCopyChecklist,
    onCopyContactRequestLink: args.onCopyContactRequestLink,
    onCopyExceptionChecklist: args.onCopyExceptionChecklist,
    onCopyFilteredEmails: args.onCopyFilteredEmails,
    onCopyMissingContactList: args.onCopyMissingContactList,
    onCopyMissingMealChecklist: args.onCopyMissingMealChecklist,
    onCopyTextRsvpLinks: args.onCopyTextRsvpLinks,
    onCreateChecklist: args.onCreateChecklist,
    onDeleteAllGuests: args.onDeleteAllGuests,
    onDryRun: args.onDryRun,
    onExportAddressCollection: args.onExportAddressCollection,
    onExportAllGuests: args.onExportAllGuests,
    onExportAttendingGuests: args.onExportAttendingGuests,
    onExportCheckedInGuests: args.onExportCheckedInGuests,
    onExportDeclinedGuests: args.onExportDeclinedGuests,
    onExportEventAttendance: args.onExportEventAttendance,
    onExportFilteredGuests: args.onExportFilteredGuests,
    onExportHouseholdLabels: args.onExportHouseholdLabels,
    onExportMissingMealChoices: args.onExportMissingMealChoices,
    onExportPendingRsvp: args.onExportPendingRsvp,
    onExportRsvpResponders: args.onExportRsvpResponders,
    onExportThankYouDue: args.onExportThankYouDue,
    onFileChange: args.onFileChange,
    onFocusHandledPersonally: args.onFocusHandledPersonally,
    onFocusHighRiskFirst: args.onFocusHighRiskFirst,
    onFocusMissingContact: args.onFocusMissingContact,
    onFocusMissingMeal: args.onFocusMissingMeal,
    onFocusPending: args.onFocusPending,
    onFocusPendingNoEmail: args.onFocusPendingNoEmail,
    onFocusPlusOneNames: args.onFocusPlusOneNames,
    onMarkAllDueThankYous: args.onMarkAllDueThankYous,
    onNextUnresolved: args.onNextUnresolved,
    onOpenCampaignModal: args.onOpenCampaignModal,
    onSearchQueryChange: args.onSearchQueryChange,
    onSelectCheckedInFilter: args.onSelectCheckedInFilter,
    onSelectFiltered: args.onSelectFiltered,
    onSelectPrimaryFilter: args.onSelectPrimaryFilter,
    onSelectUnresolved: args.onSelectUnresolved,
    onSendDueReminders: args.onSendDueReminders,
    onSendDueRemindersToggle: args.onSendDueRemindersToggle,
    onSendFilteredInvitations: args.onSendFilteredInvitations,
    onSendSelectedInvitations: args.onSendSelectedInvitations,
    onSetShowCampaignModal: args.onSetShowCampaignModal,
    onSetShowOpsMenu: args.onSetShowOpsMenu,
    onSetShowRecipientPreview: args.onSetShowRecipientPreview,
    onSetSkipRecentlyInvited: args.onSetSkipRecentlyInvited,
    onToggleCheckInMode: args.onToggleCheckInMode,
    onToggleHouseholdsView: args.onToggleHouseholdsView,
    onUndoLastCheckIn: args.onUndoLastCheckIn,
    onKeepOnlyVisibleSelection: args.onKeepOnlyVisibleSelection,
  };

  const guestHouseholdProps = {
    householdBusy: args.householdBusy,
    households: args.households,
    isDemoMode: args.isDemoMode,
    publicSiteSlug: args.publicSiteSlug,
    selectedGuestIds: args.selectedGuestIds,
    selectedGuestLanguageDraft: args.selectedGuestLanguageDraft,
    getStatusBadge: args.getStatusBadge,
    onApplySelectedGuestLanguage: args.onApplySelectedGuestLanguage,
    onMergeIntoHousehold: args.onMergeIntoHousehold,
    onSetSelectedGuestLanguageDraft: args.onSetSelectedGuestLanguageDraft,
    onSetSelectedGuestIds: args.onSetSelectedGuestIds,
  };

  const guestListProps = {
    checkInMode: args.checkInMode,
    confirmDeleteId: args.confirmDeleteId,
    deletingGuestId: args.deletingGuestId,
    displayedGuests: args.displayedGuests,
    filteredGuestCount: args.filteredGuests.length,
    isGuestsReadOnly: args.isGuestsReadOnly,
    publicSiteSlug: args.publicSiteSlug,
    searchQuery: args.searchQuery,
    sendingInviteId: args.sendingInviteId,
    getStatusBadge: args.getStatusBadge,
    onDeleteGuest: args.onDeleteGuest,
    onOpenAssistedRsvpModal: args.onOpenAssistedRsvpModal,
    onOpenEditModal: args.onOpenEditModal,
    onOpenItineraryDrawer: args.onOpenItineraryDrawer,
    onSendInvitation: args.onSendInvitation,
    onToggleCheckIn: args.onToggleCheckIn,
    onMarkThankYouSent: args.onMarkThankYouSent,
  };

  const guestInsightsProps = {
    contactStats: args.contactStats,
    customAnswerRollup: args.customAnswerRollup,
    eventReport: args.eventReport,
    mealChoiceRollup: args.mealChoiceRollup,
    mealSummary: args.mealSummary,
    rsvpOps: args.rsvpOps,
    songRequestEntries: args.songRequestEntries,
    stats: args.stats,
    onFocusCeremonyNo: args.onFocusCeremonyNo,
    onFocusMissingMeal: args.onFocusMissingMeal,
    onFocusNoResponse: args.onFocusNoResponse,
    onFocusPendingNoEmail: args.onFocusPendingNoEmail,
    onFocusPlusOneMissing: args.onFocusPlusOneMissing,
    onFocusReceptionNo: args.onFocusReceptionNo,
  };

  const guestConflictProps = {
    conflictFilter: args.conflictFilter,
    guests: args.guests,
    resolvingConflictId: args.resolvingConflictId,
    rsvpConflicts: args.rsvpConflicts,
    rsvpConflictStats: args.rsvpConflictStats,
    showConflictDetails: args.showConflictDetails,
    visibleRsvpConflicts: args.visibleRsvpConflicts,
    onResolveAllVisibleConflicts: args.onResolveAllVisibleConflicts,
    onResolveConflict: args.onResolveConflict,
    onReviewPending: args.onReviewPending,
    onSetConflictFilter: args.onSetConflictFilter,
    onToggleConflictDetails: args.onToggleConflictDetails,
  };

  const guestOpsSummaryProps = {
    cleanGuestsView: args.cleanGuestsView,
    fromQuickStart: args.fromQuickStart,
    nextStep: args.nextStep,
    opsQueue: args.opsQueue,
    plannerHandoff: args.plannerHandoff,
    recommendedAction: args.recommendedAction,
    onAddFollowUpTask: args.onAddFollowUpTask,
    onFocusQueueItem: args.onFocusQueueItem,
    onFocusRecommendedAction: args.onFocusRecommendedAction,
    onSkipToPhotos: args.onSkipToPhotos,
  };

  const guestWorkspaceProps = {
    engagementProps: guestEngagementProps,
    filteredGuestCount: args.filteredGuests.length,
    householdProps: guestHouseholdProps,
    listProps: guestListProps,
    viewMode: args.viewMode,
    onClearFilters: args.onClearFilters,
  };

  const guestHeaderProps = {
    canEditGuests: args.canEditGuests,
    contactCoverage: args.contactStats.contactCoverage,
    csvImportSummary: args.csvImportSummary,
    guestsRole: args.guestsRole,
    rsvpNoResponseCount: args.rsvpOps.noResponse,
    showInsights: args.showInsights,
    stats: args.stats,
    onAddGuest: args.onHeaderAddGuest,
    onSetGuestsTab: args.onSetGuestsTab,
    onToggleInsights: args.onToggleInsights,
  };

  const guestDashboardContentProps = {
    cleanGuestsView: args.cleanGuestsView,
    conflictProps: guestConflictProps,
    insightsProps: guestInsightsProps,
    opsSummaryProps: guestOpsSummaryProps,
    workspaceProps: guestWorkspaceProps,
  };

  const guestDashboardOpsViewProps = {
    contentProps: guestDashboardContentProps,
    headerProps: guestHeaderProps,
  };

  const guestRsvpConfigViewProps = {
    recommendedRsvpAccessMode: args.recommendedRsvpAccessMode,
    rsvpAccessModePlan: args.rsvpAccessModePlan,
    rsvpAuditFeed: args.rsvpAuditFeed,
    rsvpAuditLoading: args.rsvpAuditLoading,
    rsvpAutoSaveState: args.rsvpAutoSaveState,
    rsvpConfigSaving: args.rsvpConfigSaving,
    rsvpMealEnabled: args.rsvpMealEnabled,
    rsvpMealOptions: args.rsvpMealOptions,
    rsvpQuestionTemplateCoverage: args.rsvpQuestionTemplateCoverage,
    rsvpQuestions: args.rsvpQuestions,
    rsvpSetupChecklist: args.rsvpSetupChecklist,
    stats: args.stats,
    onAddRsvpQuestionTemplate: args.onAddRsvpQuestionTemplate,
    onSaveRsvpConfig: args.onSaveRsvpConfig,
    onSetConfirmDialog: args.onSetConfirmDialog,
    onSetGuestsTab: args.onSetGuestsTab,
    onSetRsvpConfigDirty: args.onSetRsvpConfigDirty,
    onSetRsvpMealEnabled: args.onSetRsvpMealEnabled,
    onSetRsvpMealOptions: args.onSetRsvpMealOptions,
    onSetRsvpQuestions: args.onSetRsvpQuestions,
  };

  return {
    guestDashboardOpsViewProps,
    guestRsvpConfigViewProps,
  };
}
