import React, { useMemo } from 'react';
import { DashboardLayout } from '../../components/dashboard/DashboardLayout';
import { useAuth } from '../../hooks/useAuth';
import { type PlannerAccessRole, type PlannerPermissionKey } from '../../lib/plannerAccess';
import { useToast } from '../../components/ui/Toast';
import { resolveCoordinatorCorrectionCueTarget } from '../../lib/coordinatorCorrectionCueTarget';
import { resolveCoordinatorPanelFocus, type CoordinatorPanelFocus } from '../../lib/coordinatorPanelFocus';
import { resolveCoordinatorEscalationTimelineTarget } from '../../lib/coordinatorEscalationAction';
import { resolveCoordinatorReturnToBoardState } from '../../lib/coordinatorReturnToBoard';
import { getCoordinatorNeutralFocusReason } from '../../lib/coordinatorNeutralFocusReason';
import { resolveCoordinatorNeutralFocusTarget } from '../../lib/coordinatorNeutralFocusTarget';
import { getCoordinatorTimelineTransitionLabel, syncCoordinatorAlertDraftForTimelineTransition } from '../../lib/coordinatorTimelineTransition';
import { getCoordinatorCommandSummaryTarget } from '../../lib/coordinatorCommandSummaryTarget';
import { getCoordinatorCommandJumpLabel } from '../../lib/coordinatorCommandJumpLabel';
import { shouldResetCoordinatorAlertOverride } from '../../lib/coordinatorAlertOverrideReset';
import { createCoordinatorSummaryFeedback, type CoordinatorSummaryFeedback } from '../../lib/coordinatorSummaryFeedback';
import { setCoordinatorEventTimelineState } from '../../lib/coordinatorTimelineState';
import { resolveCoordinatorTimelineAlertIntent } from '../../lib/coordinatorTimelineAlertIntent';
import { validateCoordinatorAlertForm } from '../../lib/coordinatorAlertFlow';
import { updateCoordinatorQnaItem } from '../../lib/coordinatorQnaFlow';
import { type CoordinatorQnaFilter } from '../../lib/coordinatorQnaTriage';
import { resolveCoordinatorQnaFocusAfterItemsChange, resolveCoordinatorTimelineFocusAfterStateChange } from '../../lib/coordinatorResolvedFocus';
import { getCoordinatorStablePromptTarget } from '../../lib/coordinatorStablePromptTarget';
import { getCoordinatorStandingPromptReason } from '../../lib/coordinatorStandingPromptReason';
import { getCoordinatorStandingPromptReasonTightened } from '../../lib/coordinatorStandingPromptReasonTighten';
import { updateCoordinatorQnaAnswer } from './coordinator/coordinatorService';
import { buildCoordinatorDashboardBoardActions } from './coordinator/buildCoordinatorDashboardBoardActions';
import { buildCoordinatorDashboardRouteContentProps } from './coordinator/buildCoordinatorDashboardRouteContentProps';
import { buildCoordinatorDashboardRouteSupport } from './coordinator/buildCoordinatorDashboardRouteSupport';
import { CoordinatorDashboardRouteContent } from './coordinator/CoordinatorDashboardRouteContent';
import { useCoordinatorDashboardActions } from './coordinator/useCoordinatorDashboardActions';
import { buildCoordinatorDashboardFocusActions } from './coordinator/buildCoordinatorDashboardFocusActions';
import { buildCoordinatorDashboardDerivedState } from './coordinator/buildCoordinatorDashboardDerivedState';
import { useCoordinatorDashboardData } from './coordinator/useCoordinatorDashboardData';
import { useCoordinatorDashboardCueLifecycle } from './coordinator/useCoordinatorDashboardCueLifecycle';
import { useCoordinatorDashboardUiState, useCoordinatorDashboardUiStateSync } from './coordinator/useCoordinatorDashboardUiState';


export const DashboardCoordinatorMode: React.FC = () => {
  const { user, isDemoMode } = useAuth();
  const { toast } = useToast();
  const {
    activeGuestId,
    activeQnaId,
    activeSiteRole,
    activeTimelineEventId,
    alertChannelFilter,
    alertForm,
    alertLog,
    alertTimingFilter,
    checkInFilter,
    checkInQuery,
    checkInReviewOnly,
    commandSource,
    coordinatorPermissions,
    coordinatorRole,
    eventGuestIds,
    events,
    guests,
    lastAlertSuggestionKey,
    loading,
    panelFocus,
    qnaDraftAnswers,
    qnaFilter,
    qnaInput,
    qnaItems,
    setActiveGuestId,
    setActiveQnaId,
    setActiveTimelineEventId,
    setAlertChannelFilter,
    setAlertForm,
    setAlertLog,
    setAlertTimingFilter,
    setCheckInFilter,
    setCheckInQuery,
    setCheckInReviewOnly,
    setCommandSource,
    setCoordinatorRole,
    setEvents,
    setGuests,
    setLastAlertSuggestionKey,
    setPanelFocus,
    setQnaDraftAnswers,
    setQnaFilter,
    setQnaInput,
    setQnaItems,
    setTimelineState,
    siteId,
    timelineState,
  } = useCoordinatorDashboardData({
    isDemoMode,
    toast,
    userId: user?.id,
  });
  const {
    canCheckIn,
    canEditQna,
    canEditTimeline,
    canScheduleAlerts,
    canSendAlerts,
  } = buildCoordinatorDashboardRouteSupport({
    coordinatorPermissions,
    coordinatorRole,
  });
  const {
    alertOverrideLabelState,
    alertOverrideUpdatedAt,
    commandJumpLabel,
    commandJumpPanelFocus,
    commandJumpTargetId,
    manualOverrideLabel,
    manualOverrideUpdatedAt,
    neutralFocusReason,
    overrideCueShownAt,
    previousAlertAligned,
    setAlertOverrideLabelState,
    setAlertOverrideUpdatedAt,
    setCommandJumpLabel,
    setCommandJumpPanelFocus,
    setCommandJumpTargetId,
    setManualOverrideLabel,
    setManualOverrideUpdatedAt,
    setNeutralFocusReason,
    setOverrideCueShownAt,
    setPreviousAlertAligned,
    setSummaryFeedback,
    setSummaryFeedbackShownAt,
    summaryFeedback,
    summaryFeedbackShownAt,
  } = useCoordinatorDashboardUiState();

  const {
    activeCheckInGuest,
    activeQnaDraftStateLabel,
    activeQnaDraftValue,
    activeQnaItem,
    alertActivityBoard,
    alertAudienceCount,
    alertBoard,
    alertLaneLabel,
    alertOverrideBadge,
    alertOverrideCurrentLabel,
    alertOverrideLabel,
    alertOverrideTargetLabel,
    alertStats,
    alertSuggestions,
    alertSummary,
    alertSummaryStateLabel,
    alertSummaryTransitionLabel,
    alertTargetCue,
    checkInBoard,
    checkInBoardTargetId,
    checkInQueue,
    checkInTargetGuest,
    checkInTargetState,
    checkInWatchCount,
    commandBoard,
    commandDeckItems,
    commandModeGuidance,
    commandModeLabel,
    commandSummaryItems,
    correctionCues,
    correctionEventId,
    correctionGuestId,
    eventAudienceOptions,
    executionBoard,
    filteredAlertLog,
    filteredAlertLogView,
    filteredQnaItems,
    liveEvent,
    liveEventAudience,
    liveEventId,
    liveIssues,
    manualOverrideActionLabel,
    manualOverrideBadge,
    manualOverrideCurrentTargetLabel,
    manualOverrideTargetLabel,
    navigationBoard,
    nextArrivals,
    opsSnapshotItems,
    overrideBadgeToneClassName,
    overrideDisplayCue,
    preferredAlertSuggestion,
    primaryAction,
    primaryActionBoard,
    primaryActionTarget,
    priorityCommandCta,
    priorityCommandLabel,
    priorityCommandReason,
    priorityCommandTargetReason,
    qnaBoard,
    qnaBoardTargetId,
    qnaCounts,
    qnaTargetItem,
    qnaTargetState,
    roleBoard,
    roleCapabilities,
    secondaryCommandLabel,
    sortedGuests,
    stablePrompt,
    stablePromptBadgeToneClassName,
    stablePromptState,
    stablePromptStateToneClassName,
    stablePromptTargetLabel,
    standingPromptBadge,
    standingPromptCopy,
    standingPromptMode,
    standingPromptStateLabel,
    stats,
    summaryDisplayCue,
    summaryFeedbackBadge,
    summaryFeedbackBadgeToneClassName,
    summaryFeedbackCopy,
    summaryFeedbackEmphasis,
    summaryFeedbackLayout,
    summaryFeedbackTone,
    timelineBoard,
    timelineBoardTargetId,
    timelineTargetEvent,
    timelineTargetState,
    upNextEvent,
    upNextEventId,
  } = useMemo(() => buildCoordinatorDashboardDerivedState({
    activeGuestId,
    activeQnaId,
    activeTimelineEventId,
    alertChannelFilter,
    alertForm,
    alertLog,
    alertOverrideLabelState,
    alertOverrideUpdatedAt,
    alertTimingFilter,
    checkInFilter,
    checkInQuery,
    checkInReviewOnly,
    commandSource,
    coordinatorPermissions,
    coordinatorRole,
    eventGuestIds,
    events,
    guests,
    lastAlertSuggestionKey,
    manualOverrideLabel,
    manualOverrideUpdatedAt,
    panelFocus,
    previousAlertAligned,
    qnaDraftAnswers,
    qnaFilter,
    qnaItems,
    summaryFeedback,
    timelineState,
    canEditTimeline,
    canScheduleAlerts,
  }), [
    activeGuestId,
    activeQnaId,
    activeTimelineEventId,
    alertChannelFilter,
    alertForm,
    alertLog,
    alertOverrideLabelState,
    alertOverrideUpdatedAt,
    alertTimingFilter,
    checkInFilter,
    checkInQuery,
    checkInReviewOnly,
    commandSource,
    coordinatorPermissions,
    coordinatorRole,
    eventGuestIds,
    events,
    guests,
    lastAlertSuggestionKey,
    manualOverrideLabel,
    manualOverrideUpdatedAt,
    panelFocus,
    previousAlertAligned,
    qnaDraftAnswers,
    qnaFilter,
    qnaItems,
    summaryFeedback,
    timelineState,
    canEditTimeline,
    canScheduleAlerts,
  ]);
  const alertValidationError = validateCoordinatorAlertForm(alertForm, alertAudienceCount);
  useCoordinatorDashboardUiStateSync({
    commandSource,
    correctionCueCount: correctionCues.length,
    liveIssueCount: liveIssues.length,
    panelFocus,
    primaryActionKey: primaryAction.key,
    setCommandSource,
    setNeutralFocusReason,
  });
  const {
    clearCoordinatorTransientState,
    escalateDoorReview,
    focusCoordinatorAlertLane,
    focusCoordinatorCheckInLane,
    focusCoordinatorQnaLane,
    focusCoordinatorTimelineLane,
    focusFirstCoordinatorOpenQna,
    focusFirstCoordinatorQueueGuest,
    focusNextCoordinatorQna,
    jumpToCommandSummaryItem,
    jumpToOpsSnapshotLane,
    jumpToStablePrompt,
    jumpToTimelineEvent,
    returnToBoardTarget,
    revisitNeutralFocus,
  } = useMemo(() => buildCoordinatorDashboardFocusActions({
    alertTargetCueAligned: alertTargetCue.aligned,
    canEditQna,
    canSendAlerts,
    checkInBoardTargetId,
    checkInQueue,
    checkInWatchCount,
    liveEventId,
    nextArrivals,
    panelFocus,
    preferredAlertSuggestion,
    priorityCommandLabel,
    qnaBoardTargetId,
    qnaItems,
    timelineBoardTargetId,
    upNextEventId,
    setActiveGuestId,
    setActiveQnaId,
    setActiveTimelineEventId,
    setAlertForm,
    setCheckInFilter,
    setCheckInReviewOnly,
    setCommandJumpLabel,
    setCommandJumpPanelFocus,
    setCommandJumpTargetId,
    setCommandSource,
    setManualOverrideUpdatedAt,
    setNeutralFocusReason,
    setOverrideCueShownAt,
    setPanelFocus,
    setQnaFilter,
    setQnaInput,
    setSummaryFeedback,
    setSummaryFeedbackShownAt,
    setAlertOverrideUpdatedAt,
    toast,
  }), [
    alertTargetCue.aligned,
    canEditQna,
    canSendAlerts,
    checkInBoardTargetId,
    checkInQueue,
    checkInWatchCount,
    liveEventId,
    nextArrivals,
    panelFocus,
    preferredAlertSuggestion,
    priorityCommandLabel,
    qnaBoardTargetId,
    qnaItems,
    timelineBoardTargetId,
    upNextEventId,
    setActiveGuestId,
    setActiveQnaId,
    setActiveTimelineEventId,
    setAlertForm,
    setCheckInFilter,
    setCheckInReviewOnly,
    setCommandJumpLabel,
    setCommandJumpPanelFocus,
    setCommandJumpTargetId,
    setCommandSource,
    setManualOverrideUpdatedAt,
    setNeutralFocusReason,
    setOverrideCueShownAt,
    setPanelFocus,
    setQnaFilter,
    setQnaInput,
    setSummaryFeedback,
    setSummaryFeedbackShownAt,
    setAlertOverrideUpdatedAt,
    toast,
  ]);

  const {
    addQnaItem,
    alertBusy,
    checkInBusyGuestId,
    sendDayOfAlert,
    toggleCheckIn,
  } = useCoordinatorDashboardActions({
    alertAudienceCount,
    alertForm,
    alertOverrideLabel,
    alertTargetCueAligned: alertTargetCue.aligned,
    canCheckIn,
    canEditQna,
    canScheduleAlerts,
    canSendAlerts,
    checkInFilter,
    checkInQueue,
    focusCoordinatorQnaLane,
    isDemoMode,
    preferredAlertSuggestion,
    qnaInput,
    setActiveGuestId,
    setAlertForm,
    setAlertLog,
    setAlertOverrideLabelState,
    setGuests,
    setPreviousAlertAligned,
    setQnaInput,
    setQnaItems,
    siteId,
    toast,
    validationError: alertValidationError,
  });
  useCoordinatorDashboardCueLifecycle({
    activeGuestId,
    activeQnaId,
    activeTimelineEventId,
    alertOverrideLabelState,
    checkInBoardTargetId,
    commandJumpLabel,
    commandJumpPanelFocus,
    commandJumpTargetId,
    manualOverrideLabel,
    overrideCueShownAt,
    panelFocus,
    qnaBoardTargetId,
    summaryFeedback,
    summaryFeedbackShownAt,
    timelineBoardTargetId,
    setAlertOverrideLabelState,
    setAlertOverrideUpdatedAt,
    setCommandJumpLabel,
    setCommandJumpPanelFocus,
    setCommandJumpTargetId,
    setManualOverrideLabel,
    setManualOverrideUpdatedAt,
    setOverrideCueShownAt,
    setSummaryFeedback,
    setSummaryFeedbackShownAt,
  });

  const {
    focusArrivalGuest,
    returnToBoard,
    runCorrectionCue,
    runEscalationIssue,
    runPrimaryAction,
    runTimelineAction,
    saveQnaAnswer,
    selectTimelineState,
  } = useMemo(() => buildCoordinatorDashboardBoardActions({
    alertForm,
    alertSuggestions,
    alertTargetCueAligned: alertTargetCue.aligned,
    canEditQna,
    canEditTimeline,
    correctionCues,
    correctionEventId,
    correctionGuestId,
    events,
    guests,
    isDemoMode,
    liveIssues,
    panelFocus,
    primaryAction,
    qnaBoardTargetId,
    qnaDraftAnswers,
    qnaItems,
    sortedGuests,
    siteId,
    timelineBoardTargetId,
    timelineState,
    upNextEvent,
    upNextEventId,
    setActiveGuestId,
    setActiveQnaId,
    setActiveTimelineEventId,
    setAlertForm,
    setCheckInFilter,
    setCheckInReviewOnly,
    setCommandSource,
    setLastAlertSuggestionKey,
    setNeutralFocusReason,
    setPanelFocus,
    setQnaDraftAnswers,
    setQnaItems,
    setSummaryFeedback,
    setSummaryFeedbackShownAt,
    setTimelineState,
    clearCoordinatorTransientState,
    focusCoordinatorCheckInLane,
    focusCoordinatorQnaLane,
    focusCoordinatorTimelineLane,
    toast,
    updateCoordinatorQnaAnswer,
  }), [
    alertForm,
    alertSuggestions,
    alertTargetCue.aligned,
    canEditQna,
    canEditTimeline,
    correctionCues,
    correctionEventId,
    correctionGuestId,
    events,
    guests,
    isDemoMode,
    liveIssues,
    panelFocus,
    primaryAction,
    qnaBoardTargetId,
    qnaDraftAnswers,
    qnaItems,
    sortedGuests,
    siteId,
    timelineBoardTargetId,
    timelineState,
    upNextEvent,
    upNextEventId,
    setActiveGuestId,
    setActiveQnaId,
    setActiveTimelineEventId,
    setAlertForm,
    setCheckInFilter,
    setCheckInReviewOnly,
    setCommandSource,
    setLastAlertSuggestionKey,
    setNeutralFocusReason,
    setPanelFocus,
    setQnaDraftAnswers,
    setQnaItems,
    setSummaryFeedback,
    setSummaryFeedbackShownAt,
    setTimelineState,
    clearCoordinatorTransientState,
    focusCoordinatorCheckInLane,
    focusCoordinatorQnaLane,
    focusCoordinatorTimelineLane,
    toast,
    updateCoordinatorQnaAnswer,
  ]);

  const coordinatorDashboardRouteContentProps = buildCoordinatorDashboardRouteContentProps({
    attentionPanelProps: {
          correctionCues,
          liveIssues,
          nextArrivals,
          onArrivalClick: focusArrivalGuest,
          onCorrectionCueClick: runCorrectionCue,
          onEscalationClick: runEscalationIssue,
        },
    checkInQueuePanelProps: {
          activeGuestId,
          canCheckIn,
          canEditQna,
          checkInBoard,
          checkInBoardTargetId,
          checkInBusyGuestId,
          checkInFilter,
          checkInQuery,
          checkInQueue,
          checkInReviewOnly,
          checkInTargetState,
          checkInWatchCount,
          isFocused: panelFocus === 'check-in',
          nextArrivals,
          onCheckInGuest: (guest) => { void toggleCheckIn(guest); },
          onEscalateDoorReview: escalateDoorReview,
          onFocusFirstQueueGuest: focusFirstCoordinatorQueueGuest,
          onFocusLane: focusCoordinatorCheckInLane,
          onSelectGuest: setActiveGuestId,
          onSetFilter: (filter) => {
            setCheckInFilter(filter);
            setCheckInReviewOnly(false);
          },
          onSetQuery: setCheckInQuery,
        },
    coordinatorRole,
    dayOfMessagePanelProps: {
          alertActivityBoard,
          alertBoard,
          alertBusy,
          alertChannelFilter,
          alertForm,
          alertLaneLabel,
          alertLog,
          alertOverrideCurrentLabel,
          alertOverrideLabel,
          alertOverrideTargetLabel,
          alertStats,
          alertSuggestions,
          alertSummary,
          alertTargetCue,
          alertTimingFilter,
          alertValidationError,
          canScheduleAlerts,
          canSendAlerts,
          eventAudienceOptions,
          filteredAlertLogCount: filteredAlertLog.length,
          filteredAlertLogView,
          onFocusLane: focusCoordinatorAlertLane,
          onSendAlert: () => void sendDayOfAlert(),
          onSetAlertChannelFilter: setAlertChannelFilter,
          onSetAlertForm: setAlertForm,
          onSetAlertTimingFilter: setAlertTimingFilter,
          onSetLastAlertSuggestionKey: setLastAlertSuggestionKey,
          preferredAlertSuggestion,
        },
    dayOfSummaryPanelProps: {
          alertOverrideBadge,
          alertOverrideCurrentLabel,
          alertOverrideTargetLabel,
          commandBoard,
          commandDeckItems,
          commandModeGuidance,
          commandModeLabel,
          commandSource,
          commandSummaryItems,
          executionBoard,
          hasPanelFocus: Boolean(panelFocus),
          manualOverrideActionLabel,
          manualOverrideBadge,
          manualOverrideCurrentTargetLabel,
          manualOverrideTargetLabel,
          navigationBoard,
          neutralFocusReason,
          onCommandClick: jumpToCommandSummaryItem,
          onOpsSnapshotClick: jumpToOpsSnapshotLane,
          onPrimaryAction: runPrimaryAction,
          onReturnToBoard: returnToBoard,
          onReturnToBoardTarget: returnToBoardTarget,
          onRevisitNeutralFocus: revisitNeutralFocus,
          onStablePromptClick: jumpToStablePrompt,
          opsSnapshotItems,
          overrideBadgeToneClassName,
          primaryAction,
          primaryActionBoard,
          priorityCommandCta,
          priorityCommandLabel,
          priorityCommandReason,
          priorityCommandTargetReason,
          stablePrompt,
          stablePromptBadgeToneClassName,
          stablePromptStateToneClassName,
          stablePromptTargetLabel,
          standingPromptBadge,
          standingPromptCopy,
          standingPromptMode,
          standingPromptStateLabel,
          summaryDisplayCue,
          summaryFeedbackBadge,
          summaryFeedbackBadgeToneClassName,
          summaryFeedbackCopy,
          summaryFeedbackLayout,
          summaryFeedbackTone,
        },
    hasUncheckedGuests: sortedGuests.some((guest) => !guest.checked_in_at),
    helperAccessPanelProps: {
          coordinatorRole,
          roleBoard,
          roleCapabilities,
        },
    onActiveGuestCheckIn: () => {
          const activeGuest = checkInQueue.find((guest) => guest.id === activeGuestId);
          if (!activeGuest) return;
          focusCoordinatorCheckInLane();
          void toggleCheckIn(activeGuest);
        },
    onReadyNowClick: () => {
          focusCoordinatorCheckInLane();
          setCheckInFilter('arrivals');
          setCheckInReviewOnly(false);
          setActiveGuestId(nextArrivals[0]?.id ?? null);
        },
    onReviewOnlyClick: () => {
          focusCoordinatorCheckInLane();
          setCheckInFilter('arrivals');
          setCheckInReviewOnly((prev) => !prev);
          setActiveGuestId(checkInBoardTargetId);
        },
    qnaPanelProps: {
          activeQnaDraftStateLabel,
          activeQnaId,
          activeQnaItem,
          canEditQna,
          filteredQnaItems,
          focusCoordinatorQnaLane,
          focusFirstCoordinatorOpenQna,
          focusNextCoordinatorQna,
          onAddQnaItem: () => { void addQnaItem(); },
          onChangeDraftAnswer: (id, value) => setQnaDraftAnswers((prev) => ({ ...prev, [id]: value })),
          onChangeQnaInput: setQnaInput,
          onSaveQnaAnswer: (id) => { void saveQnaAnswer(id); },
          onSelectQna: setActiveQnaId,
          onSetQnaFilter: setQnaFilter,
          panelFocus,
          qnaBoard,
          qnaBoardTargetId,
          qnaCounts,
          qnaDraftAnswers,
          qnaFilter,
          qnaInput,
          qnaItemsCount: qnaItems.length,
          qnaTargetState,
        },
    roleSelectorProps: {
          activeSiteRole,
          coordinatorRole,
          onRoleChange: setCoordinatorRole,
        },
    statsCardProps: {
          loading,
          stats,
        },
    timelinePanelProps: {
          activeTimelineEventId,
          canEditTimeline,
          events,
          liveEventId,
          onFocusLane: focusCoordinatorTimelineLane,
          onJumpToEvent: jumpToTimelineEvent,
          onRunAction: runTimelineAction,
          onSelectEvent: setActiveTimelineEventId,
          onSelectState: selectTimelineState,
          panelFocus,
          timelineBoard,
          timelineBoardTargetId,
          timelineState,
          timelineTargetState,
          upNextEventId,
        },
  });

  return (
    <DashboardLayout currentPage="coordinator">
      <CoordinatorDashboardRouteContent
        {...coordinatorDashboardRouteContentProps}
      />
    </DashboardLayout>
  );
};

export default DashboardCoordinatorMode;
