import React, { useEffect, useMemo, useRef } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { PLANNER_ROLE_OPTIONS, canManageGuests, derivePlannerRoleFromPermissions } from '../../lib/plannerAccess';
import { formatGuestOpsDate, formatGuestOpsDateTime, formatGuestOpsRelativeTime } from './guestOpsTime';
import { formatGuestEventDate } from './guestEventDate';
import { getInviteLifecycleState } from '../../lib/inviteLifecycle';
import { getGuestLifecycleStage } from '../../lib/guestLifecycleStage';
import { getPlusOneState } from '../../lib/plusOneState';
import { getPerEventRsvpState } from '../../lib/perEventRsvpState';
import { getRsvpExceptionStates } from '../../lib/rsvpExceptionState';
import { buildGuestVisibilityPreview } from '../../lib/guestVisibilityPreview';
import {
  RSVP_QUESTION_TEMPLATES,
  buildRsvpAccessModePlan,
  buildRsvpQuestionTemplateCoverage,
  buildRsvpSetupChecklist,
} from '../../lib/rsvpAccessPlanner';
import { extractDietaryNote } from '../../lib/dietaryNotes';
import { GUEST_IMPORT_MAX_FILE_BYTES, GUEST_IMPORT_MAX_ROWS } from '../../lib/guestImportParser';
import { Button, Input, Select, Textarea } from '../../components/ui';
import { Download, UserPlus, XCircle, Clock, X, Upload, Users, Mail, AlertCircle, Merge, Scissors, CalendarDays, ChevronRight, Loader2, ChevronDown, Trash2, ExternalLink, Eye } from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';
import { useToast } from '../../components/ui/Toast';
import type { ConfirmDialogProps } from '../../components/ui/ConfirmDialog';
import { buildQuickStartPhotosPath, readQuickStartDashboardContinuation } from '../../lib/quickStartContinuation';
import { resolvePublicSiteSlugFromRow } from '../../lib/publicSiteSlug';
import { logAppAction } from '../../lib/actionAudit';
import {
  buildGuestDashboardOverlayActions,
} from './guests/buildGuestDashboardOverlayActions';
import {
  formatCustomAnswers,
  getAuditActionIcon,
  getAuditActionTone,
  getAuditGuestLabel,
  getCustomAnswerEntries,
  summarizeAuditEntry,
} from './guests/guestDisplayUtils';
import { buildGuestDashboardDerivedState } from './guests/buildGuestDashboardDerivedState';
import { buildGuestDashboardOverlayProps } from './guests/buildGuestDashboardOverlayProps';
import { buildGuestDashboardRouteActions } from './guests/buildGuestDashboardRouteActions';
import { buildGuestDashboardViewProps } from './guests/buildGuestDashboardViewProps';
import { GuestDashboardRouteView } from './guests/GuestDashboardRouteView';
import {
  type Guest,
  type ItineraryEvent,
} from './guests/guestDashboardTypes';
import {
  buildGuestHouseholdGroups,
  makeRsvpQuestion,
  toTitleCase,
  csvColumnLetter,
  GUEST_SEGMENT_LABELS,
} from './guests/guestDashboardUtils';
import {
  fetchGuestRsvps,
  generateSecureGuestInviteToken,
  loadGuestDashboardPublicSlug,
  loadGuestDashboardSiteSlug,
} from './guests/guestService';
import { useGuestDashboardCampaignActions } from './guests/useGuestDashboardCampaignActions';
import { useGuestDashboardCheckIns } from './guests/useGuestDashboardCheckIns';
import { useGuestDashboardClipboardActions } from './guests/useGuestDashboardClipboardActions';
import { useGuestDashboardConflictActions } from './guests/useGuestDashboardConflictActions';
import { useGuestDashboardCsvImport } from './guests/useGuestDashboardCsvImport';
import { useGuestDashboardData } from './guests/useGuestDashboardData';
import { useGuestDashboardFollowUpActions } from './guests/useGuestDashboardFollowUpActions';
import { useGuestDashboardCrudActions } from './guests/useGuestDashboardCrudActions';
import { useGuestDashboardGuestDetailActions } from './guests/useGuestDashboardGuestDetailActions';
import { useGuestDashboardOpsActions } from './guests/useGuestDashboardOpsActions';
import { useGuestDashboardRsvpConfigActions } from './guests/useGuestDashboardRsvpConfigActions';
import { useGuestDashboardRouteSupport } from './guests/useGuestDashboardRouteSupport';
import { useGuestDashboardUiState } from './guests/useGuestDashboardUiState';
import { useGuestDashboardExports } from './guests/useGuestDashboardExports';

export const DashboardGuests: React.FC = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { fromQuickStart, nextStep } = readQuickStartDashboardContinuation(searchParams);
  const guestPreviewQa = searchParams.get('guestPreviewQa') === '1';
  const { user, isDemoMode } = useAuth();
  const { toast } = useToast();
  const rsvpConfigLoadedRef = useRef(false);
  const {
    autoRemindersEnabled,
    campaignLog,
    campaignPreset,
    checkInMode,
    confirmDeleteId,
    conflictFilter,
    deleteAllBusy,
    deleteAllConfirmInput,
    deletingGuestId,
    editingGuest,
    extraFilters,
    filterStatus,
    followUpTasks,
    formData,
    formEventInviteIds,
    guestsTab,
    reminderCadenceDays,
    savedSegments,
    searchQuery,
    selectedGuestIds,
    selectedGuestLanguageDraft,
    setAutoRemindersEnabled,
    setCampaignLog,
    setCampaignPreset,
    setCheckInMode,
    setConfirmDeleteId,
    setConflictFilter,
    setDeleteAllBusy,
    setDeleteAllConfirmInput,
    setDeletingGuestId,
    setEditingGuest,
    setExtraFilters,
    setFilterStatus,
    setFollowUpTasks,
    setFormData,
    setFormEventInviteIds,
    setGuestsTab,
    setReminderCadenceDays,
    setSavedSegments,
    setSearchQuery,
    setSelectedGuestIds,
    setSelectedGuestLanguageDraft,
    setShowAddModal,
    setShowCampaignModal,
    setShowConflictDetails,
    setShowDeleteAllModal,
    setShowInsights,
    setShowOpsMenu,
    setShowRecipientPreview,
    setSkipRecentlyInvited,
    setSortByPriority,
    setViewMode,
    showAddModal,
    showCampaignModal,
    showConflictDetails,
    showDeleteAllModal,
    showInsights,
    showOpsMenu,
    showRecipientPreview,
    skipRecentlyInvited,
    sortByPriority,
    viewMode,
  } = useGuestDashboardUiState();

  useEffect(() => {
    if (!guestPreviewQa) return;
    setCheckInMode(false);
    setShowInsights(false);
    setViewMode('list');
  }, [guestPreviewQa, setCheckInMode, setShowInsights, setViewMode]);

  const {
    eventInviteGuestMap,
    fetchGuests,
    guests,
    guestsPermissions,
    guestsRole,
    itineraryEvents,
    itineraryFilterEvents,
    loading,
    rsvpAuditFeed,
    rsvpAuditLoading,
    rsvpAccessSelection,
    rsvpConflictHistory,
    rsvpConflicts,
    rsvpMealEnabled,
    rsvpMealOptions,
    rsvpQuestions,
    setGuests,
    setGuestsRole,
    setItineraryEvents,
    setRsvpConflictHistory,
    setRsvpConflicts,
    setRsvpAccessSelection,
    setRsvpMealEnabled,
    setRsvpMealOptions,
    setRsvpQuestions,
    setWeddingSiteId,
    weddingSiteId,
    weddingSiteInfo,
  } = useGuestDashboardData({
    guestsTab,
    isDemoMode,
    rsvpConfigLoadedRef,
    setAutoRemindersEnabled,
    setReminderCadenceDays,
    toast,
    userId: user?.id ?? null,
  });
  const {
    confirmDialog,
    effectiveItineraryEvents,
    recommendedRsvpAccessMode,
    requestConfirmation,
    rsvpAccessModePlan,
    rsvpQuestionTemplateCoverage,
    rsvpSetupChecklist,
    setConfirmDialog,
  } = useGuestDashboardRouteSupport({
    guests,
    guestsRole,
    itineraryFilterEvents,
    rsvpAccessSelection,
    rsvpMealEnabled,
    rsvpMealOptions,
    rsvpQuestions,
    setGuestsRole,
    weddingSiteId,
  });
  const isGuestsReadOnly = !canManageGuests(guestsRole, guestsPermissions);

  const {
    addRsvpQuestionTemplate,
    handleSaveRsvpConfig,
    rsvpAutoSaveState,
    rsvpConfigDirty,
    rsvpConfigSaving,
    setRsvpConfigDirty,
  } = useGuestDashboardRsvpConfigActions({
    guestsTab,
    isDemoMode,
    rsvpConfigLoadedRef,
    rsvpAccessSelection,
    rsvpMealEnabled,
    rsvpMealOptions,
    rsvpQuestions,
    setRsvpQuestions,
    toast,
    weddingSiteId,
  });

  const logGuestAction = (type: string, summary: string, metadata?: Record<string, unknown>, targetId?: string | null, targetLabel?: string | null) => {
    if (!weddingSiteId) return;
    void logAppAction({
      weddingSiteId,
      area: 'guests',
      type,
      summary,
      targetId,
      targetLabel,
      metadata,
    });
  };
  const cleanGuestsView = !showInsights;

  const {
    assistedRsvpGuest,
    assistedRsvpNotes,
    assistedRsvpSaving,
    assistedRsvpSource,
    assistedRsvpStatus,
    guestAuditEntries,
    guestEventIds,
    handleMergeIntoHousehold,
    handleReassignHousehold,
    handleRevokeGuestInviteToken,
    handleRotateGuestInviteToken,
    handleSaveAssistedRsvp,
    handleSetGuestsPreferredLanguage,
    handleSplitFromHousehold,
    handleToggleCheckIn,
    handleToggleEventInvite,
    householdBusy,
    itineraryDrawerGuest,
    drawerItineraryEvents,
    lastCheckIn,
    loadingDrawer,
    openAssistedRsvpModal,
    openItineraryDrawer,
    rotatingInviteToken,
    setAssistedRsvpGuest,
    setAssistedRsvpNotes,
    setAssistedRsvpSource,
    setAssistedRsvpStatus,
    setGuestAuditEntries,
    setItineraryDrawerGuest,
    setLastCheckIn,
    togglingEventId,
  } = useGuestDashboardGuestDetailActions({
    fetchGuests,
    guests,
    isDemoMode,
    isGuestsReadOnly,
    setGuests,
    toast,
    weddingSiteId,
  });
  const generateLocalInviteToken = () => `demo_${Math.random().toString(36).slice(2, 14)}`;
  const {
    csvColumnSamples,
    csvDataRows,
    csvDuplicateNames,
    csvFieldMap,
    csvFileInputRef,
    csvHeaders,
    csvHouseholdWarnings,
    csvImporting,
    csvImportSummary,
    csvMappingSummary,
    csvNameMappingValid,
    csvPreview,
    csvSelectedFilename,
    csvShowMapper,
    csvSkipped,
    csvUnknownEvents,
    buildCsvPreviewFromMapping,
    confirmCsvImport,
    importCSV,
    resetCsvReviewState,
    setCsvFieldMap,
    setCsvShowMapper,
  } = useGuestDashboardCsvImport({
    buildQuickStartPhotosPath,
    drawerItineraryEvents,
    fetchGuests,
    fromQuickStart,
    generateLocalInviteToken,
    generateSecureToken: generateSecureGuestInviteToken,
    isDemoMode,
    isGuestsReadOnly,
    navigate,
    nextStep,
    setGuests,
    setWeddingSiteId,
    toast,
    userId: user?.id ?? null,
    weddingSiteId,
  });

  const {
    resolveAllVisibleConflicts,
    resolveConflict,
    resolvingConflictId,
    rsvpConflictStats,
    visibleRsvpConflicts,
  } = useGuestDashboardConflictActions({
    conflictFilter,
    isDemoMode,
    rsvpConflictHistory,
    rsvpConflicts,
    setRsvpConflictHistory,
    setRsvpConflicts,
    toast,
  });
  const households = useMemo(() => buildGuestHouseholdGroups(guests), [guests]);

  const {
    handleAddGuest,
    handleDeleteGuest,
    handleEditGuest,
    openEditModal,
    resetForm,
  } = useGuestDashboardCrudActions({
    effectiveItineraryEvents,
    eventInviteGuestMap,
    fetchGuests,
    formData,
    formEventInviteIds,
    guests,
    isDemoMode,
    isGuestsReadOnly,
    logGuestAction,
    setConfirmDeleteId,
    setDeletingGuestId,
    setEditingGuest,
    setFormData,
    setFormEventInviteIds,
    setGuests,
    setShowAddModal,
    toast,
    weddingSiteId,
  });

  const {
    campaignReadiness,
    contactStats,
    customAnswerRollup,
    daysToWedding,
    displayedGuests,
    dueReminderCandidatesGlobal,
    dueReminderGuestIds,
    dueThankYouGuestIds,
    eventReport,
    exceptionStateByGuest,
    fallbackByGuest,
    filteredGuests,
    householdStateByGuest,
    mealChoiceRollup,
    mealSummary,
    nextUnresolvedGuest,
    opsQueue,
    plannerHandoff,
    recommendedAction,
    reminderCandidates,
    rsvpCompleteness,
    rsvpOps,
    songRequestEntries,
    stats,
  } = buildGuestDashboardDerivedState({
    checkInMode,
    effectiveItineraryEvents,
    eventInviteGuestMap,
    extraFilters,
    filterStatus,
    guests,
    reminderCadenceDays,
    searchQuery,
    skipRecentlyInvited,
    sortByPriority,
    weddingDate: weddingSiteInfo?.wedding_date,
  });
  const publicSiteSlug = resolvePublicSiteSlugFromRow({
    site_slug: weddingSiteInfo?.site_slug ?? null,
    site_url: weddingSiteInfo?.site_url ?? null,
  });

  const segmentLabelMap = GUEST_SEGMENT_LABELS;

  const {
    applyCampaignPreset,
    clearFilters,
    clearGuestSelection,
    focusHighRiskFirst,
    handleDeleteAllGuests,
    keepOnlyVisibleSelection,
    persistReminderSettingsForSite,
    selectFilteredGuests,
  } = useGuestDashboardOpsActions({
    deleteAllConfirmInput,
    fetchGuests,
    filteredGuests,
    guests,
    isDemoMode,
    logGuestAction,
    setCampaignPreset,
    setDeleteAllBusy,
    setDeleteAllConfirmInput,
    setExtraFilters,
    setFilterStatus,
    setSearchQuery,
    setSelectedGuestIds,
    setShowDeleteAllModal,
    setSortByPriority,
    setViewMode,
    toast,
    weddingSiteId,
  });
  const {
    handleClearAllCheckIns,
    handleMarkAllDueThankYous,
    handleMarkThankYouSent,
    handleUndoLastCheckIn,
  } = useGuestDashboardCheckIns({
    dueThankYouGuestIds,
    fetchGuests,
    guests,
    isDemoMode,
    isGuestsReadOnly,
    lastCheckIn,
    requestConfirmation,
    setLastCheckIn,
    toast,
    weddingSiteId,
  });
  const { addFollowUpTask, generateChecklistTasks, saveCurrentSegment } = useGuestDashboardFollowUpActions({
    contactStats,
    filterStatus,
    filteredGuestCount: filteredGuests.length,
    rsvpOps,
    segmentLabel: segmentLabelMap[filterStatus] || filterStatus,
    setFollowUpTasks,
    setSavedSegments,
    toast,
  });
  const {
    handleCopyCampaignDryRun,
    handleCopyChecklist,
    handleCopyExceptionChecklist,
    handleCopyFilteredEmails,
    handleCopyMissingMealChecklist,
    handleCopyNoContactChecklist,
    handleCopyOpsSummary,
  } = useGuestDashboardClipboardActions({
    contactStats,
    exceptionStateByGuest,
    filteredGuests,
    filterStatus,
    followUpTasks,
    reminderCandidates,
    rsvpOps,
    segmentLabel: segmentLabelMap[filterStatus] || filterStatus,
    toast,
  });

  const {
    bulkSending,
    handleSendBulkInvitations,
    handleSendDueRemindersNow,
    handleSendInvitation,
    handleSendSelectedInvitations,
    sendingInviteId,
  } = useGuestDashboardCampaignActions({
    contactStats,
    dueReminderCandidatesGlobal,
    fetchGuests,
    filterLabel: segmentLabelMap[filterStatus] || filterStatus,
    guests,
    isDemoMode,
    isGuestsReadOnly,
    reminderCadenceDays,
    reminderCandidates,
    requestConfirmation,
    selectedGuestIds,
    setCampaignLog,
    skipRecentlyInvited,
    toast,
    weddingSiteId,
    weddingSiteInfo,
  });

  const {
    copyContactRequestLink,
    copySmsRsvpLinksForFiltered,
    exportAddressCollectionCSV,
    exportAttendingGuestsCSV,
    exportCheckedInCSV,
    exportCSV,
    exportDeclinedGuestsCSV,
    exportEventAttendanceCSV,
    exportFilteredCSV,
    exportHouseholdLabelsCSV,
    exportMissingMealCSV,
    exportPendingGuestsCSV,
    exportRsvpRespondersCSV,
    exportThankYouDueCSV,
  } = useGuestDashboardExports({
    dueThankYouGuestIds,
    effectiveItineraryEvents,
    eventInviteGuestMap,
    filteredGuests,
    guests,
    loadPublicSlug: loadGuestDashboardPublicSlug,
    loadSiteSlug: loadGuestDashboardSiteSlug,
    reminderCandidates,
    segmentLabel: segmentLabelMap[filterStatus] || filterStatus,
    toast,
    weddingSiteId,
    weddingSiteInfo,
  });

  const canEditGuests = !isGuestsReadOnly;
  const guestDashboardRouteActions = buildGuestDashboardRouteActions({
    autoRemindersEnabled,
    confirmDeleteId,
    copyContactRequestLink,
    copySmsRsvpLinksForFiltered,
    displayedGuests,
    focusHighRiskFirst,
    handleClearAllCheckIns,
    handleCopyCampaignDryRun,
    handleCopyChecklist,
    handleCopyExceptionChecklist,
    handleCopyFilteredEmails,
    handleCopyMissingMealChecklist,
    handleCopyNoContactChecklist,
    handleDeleteGuest,
    handleMarkAllDueThankYous,
    handleMergeIntoHousehold,
    handleSendBulkInvitations,
    handleSendDueRemindersNow,
    handleSendSelectedInvitations,
    handleUndoLastCheckIn,
    nextUnresolvedGuest,
    persistReminderSettingsForSite,
    resetForm,
    selectedGuestIds,
    setAutoRemindersEnabled,
    setCheckInMode,
    setDeleteAllConfirmInput,
    setExtraFilters,
    setFilterStatus,
    setSearchQuery,
    setSelectedGuestIds,
    setShowAddModal,
    setShowCampaignModal,
    setShowConflictDetails,
    setShowDeleteAllModal,
    setShowInsights,
    setViewMode,
    toast,
  });
  const guestDashboardOverlayActions = buildGuestDashboardOverlayActions({
    csvImporting,
    editingGuest,
    handleAddGuest,
    handleEditGuest,
    resetCsvReviewState,
    resetForm,
    setAssistedRsvpGuest,
    setEditingGuest,
    setGuestAuditEntries,
    setItineraryDrawerGuest,
    setShowAddModal,
    setShowDeleteAllModal,
  });
  const { guestDashboardOpsViewProps, guestRsvpConfigViewProps } = buildGuestDashboardViewProps({
    autoRemindersEnabled,
    bulkSending,
    campaignPreset,
    campaignReadiness,
    canEditGuests,
    checkInMode,
    cleanGuestsView,
    conflictFilter,
    confirmDeleteId,
    contactStats,
    csvFileInputRef,
    csvImportSummary,
    csvImporting,
    csvMaxFileMb: Math.round(GUEST_IMPORT_MAX_FILE_BYTES / 1024 / 1024),
    csvMaxRows: GUEST_IMPORT_MAX_ROWS,
    csvSelectedFilename,
    customAnswerRollup,
    daysToWedding,
    deleteAllBusy,
    deleteAllConfirmInput,
    deletingGuestId,
    displayedGuests,
    dueReminderCandidatesGlobal,
    effectiveItineraryEvents,
    eventReport,
    exceptionStateByGuest,
    extraFilters,
    fallbackByGuest,
    filterStatus,
    filteredGuests,
    formRsvpStats: stats,
    fromQuickStart,
    guests,
    guestsRole,
    householdBusy,
    households,
    isDemoMode,
    isGuestsReadOnly,
    lastCheckIn,
    loadingDrawer,
    mealChoiceRollup,
    mealSummary,
    nextStep,
    nextUnresolvedGuest,
    opsQueue,
    plannerHandoff,
    publicSiteSlug,
    recommendedAction,
    reminderCandidates,
    resolvingConflictId,
    rsvpAccessModePlan,
    rsvpAccessSelection,
    rsvpAuditFeed,
    rsvpAuditLoading,
    rsvpAutoSaveState,
    rsvpConfigSaving,
    rsvpConflictStats,
    rsvpConflicts,
    rsvpMealEnabled,
    rsvpMealOptions,
    rsvpOps,
    rsvpQuestionTemplateCoverage,
    rsvpQuestions,
    rsvpSetupChecklist,
    searchQuery,
    segmentLabelMap,
    selectedGuestIds,
    selectedGuestLanguageDraft,
    sendingInviteId,
    showCampaignModal,
    showConflictDetails,
    showInsights,
    showOpsMenu,
    showRecipientPreview,
    skipRecentlyInvited,
    songRequestEntries,
    stats,
    viewMode,
    visibleRsvpConflicts,
    onAddFollowUpTask: addFollowUpTask,
    onAddRsvpQuestionTemplate: addRsvpQuestionTemplate,
    onApplyCampaignPreset: applyCampaignPreset,
    onClearFilters: clearFilters,
    onClearSelection: clearGuestSelection,
    onCreateChecklist: generateChecklistTasks,
    onExportAddressCollection: exportAddressCollectionCSV,
    onExportAllGuests: exportCSV,
    onExportAttendingGuests: exportAttendingGuestsCSV,
    onExportCheckedInGuests: exportCheckedInCSV,
    onExportDeclinedGuests: exportDeclinedGuestsCSV,
    onExportEventAttendance: exportEventAttendanceCSV,
    onExportFilteredGuests: exportFilteredCSV,
    onExportHouseholdLabels: exportHouseholdLabelsCSV,
    onExportMissingMealChoices: exportMissingMealCSV,
    onExportPendingRsvp: exportPendingGuestsCSV,
    onExportRsvpResponders: exportRsvpRespondersCSV,
    onExportThankYouDue: exportThankYouDueCSV,
    onFileChange: importCSV,
    onKeepOnlyVisibleSelection: keepOnlyVisibleSelection,
    onMarkThankYouSent: handleMarkThankYouSent,
    onOpenAssistedRsvpModal: openAssistedRsvpModal,
    onOpenEditModal: openEditModal,
    onOpenItineraryDrawer: openItineraryDrawer,
    onResolveAllVisibleConflicts: resolveAllVisibleConflicts,
    onResolveConflict: resolveConflict,
    onSaveRsvpConfig: handleSaveRsvpConfig,
    onSearchQueryChange: setSearchQuery,
    onSelectFiltered: selectFilteredGuests,
    onSendInvitation: handleSendInvitation,
    onSetConfirmDialog: setConfirmDialog,
    onSetConflictFilter: setConflictFilter,
    onSetGuestsTab: setGuestsTab,
    onSetRsvpAccessSelection: setRsvpAccessSelection,
    onSetSelectedGuestLanguageDraft: setSelectedGuestLanguageDraft,
    onSetRsvpConfigDirty: setRsvpConfigDirty,
    onSetRsvpMealEnabled: setRsvpMealEnabled,
    onSetRsvpMealOptions: setRsvpMealOptions,
    onSetRsvpQuestions: setRsvpQuestions,
    onSetSelectedGuestIds: setSelectedGuestIds,
    onSetShowCampaignModal: setShowCampaignModal,
    onSetShowOpsMenu: setShowOpsMenu,
    onSetShowRecipientPreview: setShowRecipientPreview,
    onSetSkipRecentlyInvited: setSkipRecentlyInvited,
    onSkipToPhotos: () => navigate(buildQuickStartPhotosPath()),
    onApplySelectedGuestLanguage: () => handleSetGuestsPreferredLanguage(selectedGuestIds, selectedGuestLanguageDraft, () => {
      setSelectedGuestIds(new Set());
      setSelectedGuestLanguageDraft('');
    }),
    onToggleCheckIn: handleToggleCheckIn,
    ...guestDashboardRouteActions,
  });
  const guestOverlayProps = buildGuestDashboardOverlayProps({
    assistedRsvpGuest,
    assistedRsvpNotes,
    assistedRsvpSaving,
    assistedRsvpSource,
    assistedRsvpStatus,
    confirmDialog,
    csvColumnSamples,
    csvDataRows,
    csvDuplicateNames,
    csvFieldMap,
    csvHeaders,
    csvHouseholdWarnings,
    csvImporting,
    csvMappingSummary,
    csvNameMappingValid,
    csvPreview,
    csvSelectedFilename,
    csvShowMapper,
    csvSkipped,
    csvUnknownEvents,
    deleteAllBusy,
    deleteAllConfirmInput,
    editingGuest,
    effectiveItineraryEvents,
    formData,
    formEventInviteIds,
    guestAuditEntries,
    guestEventIds,
    guests,
    itineraryDrawerGuest,
    itineraryEvents: drawerItineraryEvents,
    itineraryFilterEventCount: itineraryFilterEvents.length,
    loadingDrawer,
    rotatingInviteToken,
    showAddModal,
    showDeleteAllModal,
    togglingEventId,
    weddingSiteInfo,
    onAddFollowUpTask: addFollowUpTask,
    onBuildCsvPreview: buildCsvPreviewFromMapping,
    onConfirmCsvImport: confirmCsvImport,
    onConfirmDeleteAllGuests: handleDeleteAllGuests,
    onCopyContactRequestLink: copyContactRequestLink,
    onFocusGuestSearch: setSearchQuery,
    onRevokeGuestInviteToken: handleRevokeGuestInviteToken,
    onRotateGuestInviteToken: handleRotateGuestInviteToken,
    onSaveAssistedRsvp: handleSaveAssistedRsvp,
    onSetAssistedRsvpNotes: setAssistedRsvpNotes,
    onSetAssistedRsvpSource: setAssistedRsvpSource,
    onSetAssistedRsvpStatus: setAssistedRsvpStatus,
    onSetCsvFieldMap: setCsvFieldMap,
    onSetCsvShowMapper: setCsvShowMapper,
    onSetDeleteAllConfirmInput: setDeleteAllConfirmInput,
    onSetFormData: setFormData,
    onSetFormEventInviteIds: setFormEventInviteIds,
    onToast: toast,
    onToggleEventInvite: handleToggleEventInvite,
    ...guestDashboardOverlayActions,
  });

  return (
    <GuestDashboardRouteView
      loading={loading}
      overlayProps={guestOverlayProps}
      opsViewProps={guestDashboardOpsViewProps}
      rsvpConfigViewProps={guestRsvpConfigViewProps}
      showRsvpConfig={guestsTab === 'rsvp-config'}
    />
  );
};
