import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import { useToast } from '../../components/ui/Toast';
import {
  type SettingsCollaboratorInviteRow,
} from './settings/settingsSiteData';
import {
  type SiteLanguageCode,
} from './settings/settingsDashboardTypes';
import {
  safeSettingsError,
} from './settings/settingsDashboardUtils';
import { buildSettingsDashboardRouteContentProps } from './settings/buildSettingsDashboardRouteContentProps';
import { SettingsDashboardRouteContent } from './settings/SettingsDashboardRouteContent';
import { useSettingsAccountActions } from './settings/useSettingsAccountActions';
import { useSettingsDashboardSupport } from './settings/useSettingsDashboardSupport';
import { useSettingsSiteAccessActions } from './settings/useSettingsSiteAccessActions';
import { useSettingsExperienceActions } from './settings/useSettingsExperienceActions';
import { useSettingsDashboardSnapshotHydration } from './settings/useSettingsDashboardSnapshotHydration';
import { useSettingsDashboardUiState } from './settings/useSettingsDashboardUiState';
import { useSettingsDashboardRouteSupport } from './settings/useSettingsDashboardRouteSupport';

export const DashboardSettings: React.FC = () => {
  const { toast } = useToast();
  const navigate = useNavigate();
  const { user, isDemoMode, signOut } = useAuth();
  const {
    activeTab,
    accountEmail,
    accountError,
    accountSaving,
    accountSuccess,
    billingError,
    billingInfo,
    billingLoading,
    changingTemplate,
    analyticsEnabled,
    analyticsRetentionDays,
    analyticsGuestNotice,
    collapsedQuestionIds,
    collaboratorInvites,
    confirmPassword,
    coupleNames,
    creatingCollaboratorInvite,
    currentPassword,
    currentTemplate,
    allowedLanguages,
    defaultLanguage,
    guestAccessToken,
    isPublished,
    hideFromSearch,
    musicPlaylistUrl,
    newPassword,
    notifDigest,
    notifDigestCadence,
    notifDigestIncludePlanner,
    notifDigestQuietUntilLabel,
    notifDigestNextDeliveryAt,
    notifDigestLastReviewedAt,
    notifDigestLastDeliveredAt,
    notifDraftGuard,
    notifError,
    notifPhotos,
    notifRsvp,
    notifSaving,
    notifSuccess,
    notifUpdates,
    passwordError,
    passwordSaving,
    passwordSuccess,
    plannerInvite,
    plannerInviteEmail,
    plannerInviteError,
    plannerInviteName,
    plannerInvitePermissions,
    plannerInviteRole,
    plannerInviteSuccess,
    privacyCopied,
    privacyMode,
    rsvpDraftGuard,
    rsvpMealEnabled,
    rsvpMealOptions,
    rsvpQuestions,
    rsvpQuestionsError,
    rsvpQuestionsSaving,
    rsvpQuestionsSuccess,
    revokingCollaboratorInviteId,
    settingsRole,
    showAdvancedRsvp,
    showConfirmPw,
    showCurrentPw,
    showMealChoiceSettings,
    showNewPw,
    showNotificationSettings,
    showPrivacySettings,
    showSitePassword,
    showTemplateSettings,
    sitePassword,
    siteSlug,
    slugError,
    slugSaving,
    slugSuccess,
    subscribeError,
    subscribeLoading,
    templateError,
    templateSuccess,
    translatingLanguage,
    translationStatuses,
    settingsWeddingData,
    venueName,
    visibilityDraftGuard,
    visibilityError,
    visibilitySaving,
    visibilitySuccess,
    weddingDate,
    weddingSiteId,
    setActiveTab,
    setAccountEmail,
    setAccountError,
    setAccountSaving,
    setAccountSuccess,
    setBillingError,
    setBillingInfo,
    setBillingLoading,
    setChangingTemplate,
    setAnalyticsEnabled,
    setAnalyticsRetentionDays,
    setAnalyticsGuestNotice,
    setCollapsedQuestionIds,
    setCollaboratorInvites,
    setConfirmPassword,
    setCoupleNames,
    setCreatingCollaboratorInvite,
    setCurrentPassword,
    setCurrentTemplate,
    setAllowedLanguages,
    setDefaultLanguage,
    setGuestAccessToken,
    setIsPublished,
    setHideFromSearch,
    setMusicPlaylistUrl,
    setNewPassword,
    setNotifDigest,
    setNotifDigestCadence,
    setNotifDigestIncludePlanner,
    setNotifDigestQuietUntilLabel,
    setNotifDigestNextDeliveryAt,
    setNotifDigestLastReviewedAt,
    setNotifDigestLastDeliveredAt,
    setNotifError,
    setNotifPhotos,
    setNotifRsvp,
    setNotifSaving,
    setNotifSuccess,
    setNotifUpdates,
    setPasswordError,
    setPasswordSaving,
    setPasswordSuccess,
    setPlannerInvite,
    setPlannerInviteEmail,
    setPlannerInviteError,
    setPlannerInviteName,
    setPlannerInvitePermissions,
    setPlannerInviteRole,
    setPlannerInviteSuccess,
    setPrivacyCopied,
    setPrivacyMode,
    setRsvpMealEnabled,
    setRsvpMealOptions,
    setRsvpQuestions,
    setRsvpQuestionsError,
    setRsvpQuestionsSaving,
    setRsvpQuestionsSuccess,
    setRevokingCollaboratorInviteId,
    setSettingsRole,
    setShowAdvancedRsvp,
    setShowConfirmPw,
    setShowCurrentPw,
    setShowMealChoiceSettings,
    setShowNewPw,
    setShowNotificationSettings,
    setShowPrivacySettings,
    setShowSitePassword,
    setShowTemplateSettings,
    setSitePassword,
    setSiteSlug,
    setSlugError,
    setSlugSaving,
    setSlugSuccess,
    setSubscribeError,
    setSubscribeLoading,
    setTemplateError,
    setTemplateSuccess,
    setTranslatingLanguage,
    setTranslationStatuses,
    setSettingsWeddingData,
    setVenueName,
    setVisibilityError,
    setVisibilitySaving,
    setVisibilitySuccess,
    setWeddingDate,
    setWeddingSiteId,
  } = useSettingsDashboardUiState({ userId: user?.id });

  const {
    downloadTextFile,
    loadCollaboratorInvites,
    loadTranslationStatuses,
    logSettingsAction,
    resolveSettingsSiteId,
  } = useSettingsDashboardSupport({
    setCollaboratorInvites,
    setTranslationStatuses,
    setWeddingSiteId,
    userId: user?.id,
    weddingSiteId,
  });

  useSettingsDashboardSnapshotHydration({
    isDemoMode,
    notifDraftGuard,
    rsvpDraftGuard,
    setAccountEmail,
    setAccountError,
    setAllowedLanguages,
    setAnalyticsEnabled,
    setAnalyticsGuestNotice,
    setAnalyticsRetentionDays,
    setCollaboratorInvites,
    setCoupleNames,
    setCurrentTemplate,
    setDefaultLanguage,
    setGuestAccessToken,
    setHideFromSearch,
    setIsPublished,
    setMusicPlaylistUrl,
    setNotifDigest,
    setNotifDigestCadence,
    setNotifDigestIncludePlanner,
    setNotifDigestQuietUntilLabel,
    setNotifDigestNextDeliveryAt,
    setNotifDigestLastReviewedAt,
    setNotifDigestLastDeliveredAt,
    setNotifPhotos,
    setNotifRsvp,
    setNotifUpdates,
    setPrivacyMode,
    setRsvpMealEnabled,
    setRsvpMealOptions,
    setRsvpQuestions,
    setSettingsRole,
    setSiteSlug,
    setSettingsWeddingData,
    setTranslationStatuses,
    setVenueName,
    setWeddingDate,
    setWeddingSiteId,
    userEmail: user?.email ?? null,
    userId: user?.id ?? null,
    visibilityDraftGuard,
  });

  const {
    handleSaveAccount,
    handleUpdatePassword,
  } = useSettingsAccountActions({
    coupleNames,
    currentPassword,
    newPassword,
    confirmPassword,
    logSettingsAction,
    setAccountError,
    setAccountSaving,
    setAccountSuccess,
    setConfirmPassword,
    setCurrentPassword,
    setNewPassword,
    setPasswordError,
    setPasswordSaving,
    setPasswordSuccess,
    weddingSiteId,
  });

  const {
    handleLogout,
    plannerRoleOptions,
    publicSiteUrl,
    safeMusicPlaylistUrl,
    tabs,
    weddingIdentityExportKit,
    weddingIdentityPrintAssets,
    weddingIdentityStoryGraphic,
    weddingIdentityStyleKit,
  } = useSettingsDashboardRouteSupport({
    coupleNames,
    currentTemplate,
    defaultLanguage,
    isPublished,
    musicPlaylistUrl,
    navigate,
    settingsRole,
    signOut,
    siteSlug,
    venueName,
    weddingDate,
  });

  const {
    copyIdentityManifest,
    copyIdentityStyleKit,
    copyInviteLink,
    downloadIdentityStoryGraphic,
    downloadIdentityPrintPack,
    handleAllowedLanguagesChange,
    handleAutoTranslateLanguage,
    handleCopyCollaboratorInviteLink,
    handleCreateCollaboratorInvite,
    handleDefaultLanguageChange,
    handleRegenerateToken,
    handleRemovePlannerInvite,
    handleResendCollaboratorInvite,
    handleRevokeCollaboratorInvite,
    handleSaveMusicPlaylist,
    handleSavePlannerInvite,
    handleSavePrivacy,
    handleUpdateSlug,
    togglePlannerPermission,
  } = useSettingsSiteAccessActions({
    userId: user?.id,
    siteSlug,
    weddingSiteId,
    plannerInvite,
    plannerInviteName,
    plannerInviteEmail,
    plannerInviteRole,
    plannerInvitePermissions,
    collaboratorInvites,
    isPublished,
    privacyMode,
    hideFromSearch,
    allowedLanguages,
    defaultLanguage,
    analyticsEnabled,
    analyticsRetentionDays,
    analyticsGuestNotice,
    settingsWeddingData,
    sitePassword,
    guestAccessToken,
    musicPlaylistUrl,
    weddingIdentityExportKit,
    weddingIdentityPrintAssets,
    weddingIdentityStoryGraphic,
    weddingIdentityStyleKit,
    resolveSettingsSiteId,
    loadCollaboratorInvites,
    loadTranslationStatuses,
    logSettingsAction,
    toast,
    visibilityDraftGuard,
    downloadTextFile,
    setPlannerInvite,
    setPlannerInviteName,
    setPlannerInviteEmail,
    setPlannerInviteRole,
    setPlannerInvitePermissions,
    setCreatingCollaboratorInvite,
    setDefaultLanguage,
    setGuestAccessToken,
    setPlannerInviteError,
    setPlannerInviteSuccess,
    setPrivacyCopied,
    setRevokingCollaboratorInviteId,
    setSitePassword,
    setSiteSlug,
    setSlugError,
    setSlugSaving,
    setSlugSuccess,
    setTranslatingLanguage,
    setAllowedLanguages,
    setSettingsWeddingData,
    setVisibilityError,
    setVisibilitySaving,
    setVisibilitySuccess,
    setWeddingSiteId,
  });

  const {
    handleSaveNotifications,
    handleSaveRsvpQuestions,
    handleSubscribe,
    handleTemplateChange,
    saveRsvpSettings,
  } = useSettingsExperienceActions({
    userId: user?.id,
    isDemoMode,
    weddingSiteId,
    rsvpQuestions,
    rsvpMealEnabled,
    rsvpMealOptions,
    notifRsvp,
    notifPhotos,
    notifDigest,
    notifDigestCadence,
    notifDigestIncludePlanner,
    notifDigestQuietUntilLabel,
    notifDigestLastDeliveredAt,
    notifUpdates,
    billingInfo,
    resolveSettingsSiteId,
    logSettingsAction,
    rsvpDraftGuard,
    notifDraftGuard,
    setWeddingSiteId,
    setRsvpQuestions,
    setRsvpMealOptions,
    setRsvpQuestionsSaving,
    setRsvpQuestionsSuccess,
    setRsvpQuestionsError,
    setNotifSaving,
    setNotifSuccess,
    setNotifError,
    setNotifDigestNextDeliveryAt,
    setNotifDigestLastReviewedAt,
    setSubscribeLoading,
    setSubscribeError,
    setChangingTemplate,
    setTemplateError,
    setTemplateSuccess,
    setCurrentTemplate,
  });

  const settingsDashboardRouteContentProps = buildSettingsDashboardRouteContentProps({
    accountEmail,
    accountError,
    accountSaving,
    accountSuccess,
    activeTab,
    billingError,
    billingInfo,
    billingLoading,
    changingTemplate,
    collapsedQuestionIds,
    collaboratorInvites,
    confirmPassword,
    coupleNames,
    creatingCollaboratorInvite,
    currentPassword,
    currentTemplate,
    allowedLanguages,
    analyticsEnabled,
    analyticsRetentionDays,
    analyticsGuestNotice,
    defaultLanguage,
    guestAccessToken,
    isPublished,
    onAutoTranslateLanguage: handleAutoTranslateLanguage,
    handleAllowedLanguagesChange,
    handleCopyCollaboratorInviteLink,
    handleCreateCollaboratorInvite,
    handleDefaultLanguageChange,
    handleLogout,
    handleRegenerateToken,
    handleRemovePlannerInvite,
    handleResendCollaboratorInvite,
    handleRevokeCollaboratorInvite,
    handleSaveAccount,
    handleSaveMusicPlaylist,
    handleSaveNotifications,
    handleSavePlannerInvite,
    handleSavePrivacy,
    handleSaveRsvpQuestions,
    handleSubscribe,
    handleTemplateChange,
    handleUpdatePassword,
    handleUpdateSlug,
    hideFromSearch,
    musicPlaylistUrl,
    newPassword,
    notifDigest,
    notifDigestCadence,
    notifDigestIncludePlanner,
    notifDigestQuietUntilLabel,
    notifDigestNextDeliveryAt,
    notifDigestLastReviewedAt,
    notifDigestLastDeliveredAt,
    notifDraftMarkDirty: notifDraftGuard.markDirty,
    notifError,
    notifPhotos,
    notifRsvp,
    notifSaving,
    notifSuccess,
    notifUpdates,
    onCopyIdentityManifest: copyIdentityManifest,
    onCopyIdentityStyleKit: copyIdentityStyleKit,
    onCopyInviteLink: copyInviteLink,
    onDownloadIdentityStoryGraphic: downloadIdentityStoryGraphic,
    onDownloadIdentityPrintPack: downloadIdentityPrintPack,
    passwordError,
    passwordSaving,
    passwordSuccess,
    plannerInvite,
    plannerInviteEmail,
    plannerInviteError,
    plannerInviteName,
    plannerInvitePermissions,
    plannerInviteRole,
    plannerInviteSuccess,
    plannerRoleOptions,
    privacyCopied,
    privacyMode,
    publicSiteUrl,
    revokingCollaboratorInviteId,
    rsvpDraftMarkDirty: rsvpDraftGuard.markDirty,
    rsvpMealEnabled,
    rsvpMealOptions,
    rsvpQuestions,
    rsvpQuestionsError,
    rsvpQuestionsSaving,
    rsvpQuestionsSuccess,
    safeMusicPlaylistUrl,
    saveRsvpSettings,
    setActiveTab,
    setCollapsedQuestionIds,
    setConfirmPassword,
    setCoupleNames,
    setCurrentPassword,
    setHideFromSearch,
    setAnalyticsEnabled,
    setAnalyticsRetentionDays,
    setAnalyticsGuestNotice,
    setMusicPlaylistUrl,
    setNewPassword,
    setNotifDigest,
    setNotifDigestCadence,
    setNotifDigestIncludePlanner,
    setNotifDigestQuietUntilLabel,
    setNotifPhotos,
    setNotifRsvp,
    setNotifUpdates,
    setPlannerInviteEmail,
    setPlannerInviteName,
    setPlannerInvitePermissions,
    setPlannerInviteRole,
    setPrivacyMode,
    setRsvpMealEnabled,
    setRsvpMealOptions,
    setRsvpQuestions,
    setShowAdvancedRsvp,
    setShowConfirmPw,
    setShowCurrentPw,
    setShowMealChoiceSettings,
    setShowNewPw,
    setShowNotificationSettings,
    setShowPrivacySettings,
    setShowSitePassword,
    setShowTemplateSettings,
    setSitePassword,
    setSiteSlug,
    settingsRole,
    showAdvancedRsvp,
    showConfirmPw,
    showCurrentPw,
    showMealChoiceSettings,
    showNewPw,
    showNotificationSettings,
    showPrivacySettings,
    showSitePassword,
    showTemplateSettings,
    sitePassword,
    siteSlug,
    slugError,
    slugSaving,
    slugSuccess,
    subscribeError,
    subscribeLoading,
    tabs,
    templateError,
    templateSuccess,
    togglePlannerPermission,
    translatingLanguage,
    translationStatuses,
    visibilityDraftMarkDirty: visibilityDraftGuard.markDirty,
    visibilityError,
    visibilitySaving,
    visibilitySuccess,
    hasWeddingIdentityStoryGraphic: Boolean(weddingIdentityStoryGraphic),
    weddingIdentityExportKit,
    weddingIdentityPrintAssets,
  });

  return (
    <SettingsDashboardRouteContent {...settingsDashboardRouteContentProps} />
  );
};
