import {
  BuilderSectionDefinition,
  BuilderSectionType,
  BuilderSectionCapabilities,
  createDefaultSectionInstance,
  BuilderSectionInstance,
} from '../../types/builder/section.ts';

const defaultCapabilities: BuilderSectionCapabilities = {
  draggable: true,
  duplicable: true,
  deletable: true,
  mediaAware: false,
  hasSettings: true,
  hasBindings: false,
  locked: false,
};

export interface VariantMeta {
  id: string;
  label: string;
  description: string;
  bestFor?: string;
  effort?: 'easy' | 'medium' | 'advanced';
  recommended?: boolean;
}

export type BuilderSectionDefinitionWithMeta = BuilderSectionDefinition & {
  variantMeta: VariantMeta[];
};

export const SECTION_MANIFESTS: Record<BuilderSectionType, BuilderSectionDefinitionWithMeta> = {
  hero: {
    type: 'hero',
    label: 'Hero',
    icon: 'Image',
    defaultVariant: 'default',
    supportedVariants: ['default', 'minimal', 'fullbleed', 'split', 'botanical', 'video', 'invitation', 'countdown'],
    variantMeta: [
      { id: 'default', label: 'Classic', description: 'Names, date, and photo with a soft overlay', bestFor: 'most couples who want a polished first screen fast', effort: 'easy', recommended: true },
      { id: 'minimal', label: 'Minimal', description: 'Clean typography only, no background image', bestFor: 'editorial sites with strong typography or limited photos', effort: 'easy' },
      { id: 'fullbleed', label: 'Full Bleed', description: 'Edge-to-edge image with bold text overlay', bestFor: 'dramatic venue or portrait photography', effort: 'medium' },
      { id: 'split', label: 'Split Screen', description: 'Photo fills the left half, names and details on the right', bestFor: 'couples who want image and invitation details equally visible', effort: 'medium' },
      { id: 'botanical', label: 'Botanical', description: 'Floral frame overlay with soft romantic styling', bestFor: 'garden, estate, and romantic spring weddings', effort: 'easy' },
      { id: 'video', label: 'Video Background', description: 'Looping video background with centered text overlay', bestFor: 'premium sites with a strong highlight clip', effort: 'advanced' },
      { id: 'invitation', label: 'Invitation Card', description: 'Stationery-style card with formal typography on a textured background', bestFor: 'black-tie and invitation-led designs', effort: 'easy' },
      { id: 'countdown', label: 'Countdown Hero', description: 'Hero with live countdown timer embedded in the lower third', bestFor: 'save-the-date sites and guests revisiting often', effort: 'medium' },
    ],
    capabilities: { ...defaultCapabilities, mediaAware: true, deletable: false },
    settingsSchema: {
      fields: [
        { key: 'headline', label: 'Headline (overrides couple names)', type: 'text', placeholder: 'Leave blank to use couple names' },
        { key: 'subtitle', label: 'Subheadline', type: 'text', placeholder: 'Leave blank to use wedding date' },
        { key: 'title', label: 'Small intro line', type: 'text', placeholder: 'e.g. We are getting married' },
        { key: 'showTitle', label: 'Show small intro line', type: 'toggle', defaultValue: true },
        { key: 'backgroundImage', label: 'Background photo', type: 'image' },
        { key: 'overlayOpacity', label: 'Photo overlay (%)', type: 'number', defaultValue: 40 },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/hero.jpg',
  },
  story: {
    type: 'story',
    label: 'Our Story',
    icon: 'Heart',
    defaultVariant: 'default',
    supportedVariants: ['default', 'centered', 'split', 'timeline', 'chapters', 'duoColumn', 'milestones'],
    variantMeta: [
      { id: 'default', label: 'Classic', description: 'Text on left, photo on right', bestFor: 'short heartfelt stories that need one great photo', effort: 'easy', recommended: true },
      { id: 'centered', label: 'Centered', description: 'Story text centered with photo above', bestFor: 'simple pages where the story should feel calm and readable', effort: 'easy' },
      { id: 'split', label: 'Split', description: 'Large image beside full-height text', bestFor: 'editorial sites with a strong couple portrait', effort: 'medium' },
      { id: 'timeline', label: 'Timeline', description: 'Milestone timeline with alternating text and photos', bestFor: 'relationship arcs with clear dates and milestones', effort: 'medium' },
      { id: 'chapters', label: 'Chapters', description: 'Story in numbered chapters with large editorial photos', bestFor: 'longer stories that should feel like a magazine feature', effort: 'advanced' },
      { id: 'duoColumn', label: 'His & Hers', description: 'Side-by-side columns with each person\'s perspective', bestFor: 'two voices, proposal stories, or playful point-counterpoint copy', effort: 'medium' },
      { id: 'milestones', label: 'Milestones', description: 'Icon cards for key moments: first date, proposal, and more', bestFor: 'quick scanning when guests will not read a long story', effort: 'easy' },
    ],
    capabilities: { ...defaultCapabilities, mediaAware: true },
    settingsSchema: {
      fields: [
        { key: 'showTitle', label: 'Show section title', type: 'toggle', defaultValue: true },
        { key: 'title', label: 'Section title', type: 'text', defaultValue: 'Our Story' },
        { key: 'storyText', label: 'Story text', type: 'textarea' },
        { key: 'photo', label: 'Couple photo', type: 'image' },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/story.jpg',
  },
  venue: {
    type: 'venue',
    label: 'Venue',
    icon: 'MapPin',
    defaultVariant: 'card',
    supportedVariants: ['card', 'mapFirst', 'splitMap', 'detailsFirst', 'banner', 'stacked', 'minimal'],
    variantMeta: [
      { id: 'card', label: 'Card', description: 'Each venue in a rich card with photo and details', bestFor: 'single-venue weddings that need directions and atmosphere together', effort: 'easy', recommended: true },
      { id: 'mapFirst', label: 'Map First', description: 'Full-width map at the top, details below', bestFor: 'city weddings where guests need location context first', effort: 'medium' },
      { id: 'splitMap', label: 'Split Map', description: 'Details and map/photo side by side', bestFor: 'venue sections that balance logistics with a strong image', effort: 'medium' },
      { id: 'detailsFirst', label: 'Details First', description: 'Structured detail grid with icons', bestFor: 'practical venue information guests will scan quickly', effort: 'easy' },
      { id: 'banner', label: 'Aerial Banner', description: 'Full-width cinematic venue photo with overlaid name and details', bestFor: 'venues with a dramatic exterior or landscape image', effort: 'medium' },
      { id: 'stacked', label: 'Stacked', description: 'Ceremony and reception venues stacked with photo headers', bestFor: 'separate ceremony and reception spaces', effort: 'medium' },
      { id: 'minimal', label: 'Minimal', description: 'Typography-first layout with small map thumbnail', bestFor: 'formal sites that want venue details quiet and clean', effort: 'easy' },
    ],
    capabilities: { ...defaultCapabilities, hasBindings: true, mediaAware: true },
    settingsSchema: {
      fields: [
        { key: 'showTitle', label: 'Show section title', type: 'toggle', defaultValue: true },
        { key: 'title', label: 'Section title', type: 'text', defaultValue: 'Venue' },
        { key: 'showMap', label: 'Show map', type: 'toggle', defaultValue: true },
      ],
    },
    bindingsSchema: {
      slots: [
        { key: 'venueIds', label: 'Venues', dataSource: 'venues', multiple: true },
      ],
    },
    previewImagePath: '/previews/venue.jpg',
  },
  schedule: {
    type: 'schedule',
    label: 'Schedule',
    icon: 'Clock',
    defaultVariant: 'timeline',
    supportedVariants: ['timeline', 'dayTabs', 'agendaCards', 'bands', 'horizontal', 'program'],
    variantMeta: [
      { id: 'timeline', label: 'Timeline', description: 'Vertical timeline with times on the left', bestFor: 'single-day schedules guests need to scan quickly', effort: 'easy', recommended: true },
      { id: 'dayTabs', label: 'Day Tabs', description: 'Tab switcher for multi-day weekend events', bestFor: 'welcome party, wedding day, and farewell brunch weekends', effort: 'medium' },
      { id: 'agendaCards', label: 'Agenda Cards', description: 'Each event as a card in a grid layout', bestFor: 'small schedules with photos or location notes per event', effort: 'easy' },
      { id: 'bands', label: 'Program Bands', description: 'Alternating full-width rows styled like a printed program', bestFor: 'formal timelines that should feel like a printed insert', effort: 'medium' },
      { id: 'horizontal', label: 'Horizontal', description: 'Events along a horizontal scrolling timeline track', bestFor: 'desktop-heavy preview moments and short event lists', effort: 'advanced' },
      { id: 'program', label: 'Split Two-Column', description: 'Ceremony events left, reception events right', bestFor: 'separating ceremony details from reception flow', effort: 'medium' },
    ],
    capabilities: { ...defaultCapabilities, hasBindings: true },
    settingsSchema: {
      fields: [
        { key: 'showTitle', label: 'Show section title', type: 'toggle', defaultValue: true },
        { key: 'title', label: 'Section title', type: 'text', defaultValue: 'Schedule' },
        { key: 'showIcons', label: 'Show icons', type: 'toggle', defaultValue: true },
      ],
    },
    bindingsSchema: {
      slots: [
        { key: 'scheduleItemIds', label: 'Schedule moments', dataSource: 'schedule', multiple: true },
      ],
    },
    previewImagePath: '/previews/schedule.jpg',
  },
  travel: {
    type: 'travel',
    label: 'Travel & Hotels',
    icon: 'Plane',
    defaultVariant: 'list',
    supportedVariants: ['list', 'hotelBlock', 'thingsToDo', 'localGuide', 'tiers', 'mapPins', 'splitAirHotel', 'compact'],
    variantMeta: [
      { id: 'list', label: 'List', description: 'Travel tips plus a compact hotel list', bestFor: 'most couples with one or two hotel suggestions', effort: 'easy', recommended: true },
      { id: 'hotelBlock', label: 'Hotel Block', description: 'Hotel-first layout with booking codes, amenities, and shuttle info', bestFor: 'room blocks with deadlines, codes, and shuttle details', effort: 'medium' },
      { id: 'thingsToDo', label: 'Things To Do', description: 'Local recommendations section for guests extending their stay', bestFor: 'destination weddings and weekend guides', effort: 'medium' },
      { id: 'localGuide', label: 'Local Guide', description: 'Travel logistics plus local tips and key locations for guests', bestFor: 'guests flying in who need context beyond hotels', effort: 'medium' },
      { id: 'tiers', label: 'Tiered Options', description: 'Hotels grouped by Closest, Best Value, and Budget tiers', bestFor: 'multiple lodging options at different price points', effort: 'medium' },
      { id: 'mapPins', label: 'Map & Pins', description: 'Map with hotel and venue pins plus a list below', bestFor: 'city weddings where location context matters', effort: 'advanced' },
      { id: 'splitAirHotel', label: 'Air & Hotel Split', description: 'Airport info on the left, hotel recommendations on the right', bestFor: 'out-of-town guests balancing flights and hotels', effort: 'medium' },
      { id: 'compact', label: 'Compact List', description: 'Minimalist bullet list with names, distances, and links', bestFor: 'already-informed guests and very simple logistics', effort: 'easy' },
    ],
    capabilities: { ...defaultCapabilities },
    settingsSchema: {
      fields: [
        { key: 'showTitle', label: 'Show section title', type: 'toggle', defaultValue: true },
        { key: 'title', label: 'Section title', type: 'text', defaultValue: 'Travel' },
        { key: 'showParking', label: 'Show parking notes', type: 'toggle', defaultValue: true },
        { key: 'showTimezoneBadge', label: 'Show time zone note', type: 'toggle', defaultValue: true },
        { key: 'showIcsButton', label: 'Show add-to-calendar button', type: 'toggle', defaultValue: true },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/travel.jpg',
  },
  registry: {
    type: 'registry',
    label: 'Registry',
    icon: 'Gift',
    defaultVariant: 'cards',
    supportedVariants: ['default', 'cards', 'grid', 'fundHighlight', 'featured', 'minimal', 'honeymoon', 'tabs', 'illustrated', 'classic', 'luxury', 'experiences', 'modern', 'playful'],
    variantMeta: [
      { id: 'cards', label: 'Store Links', description: 'Registry links as clickable store cards', bestFor: 'simple registries with two to four stores', effort: 'easy', recommended: true },
      { id: 'fundHighlight', label: 'Fund Highlight', description: 'Highlights one featured fund/link first, then secondary registry links', bestFor: 'cash funds or honeymoon funds that deserve top billing', effort: 'easy' },
      { id: 'featured', label: 'Featured Gifts', description: 'Showcase specific gift items with photos, prices, and store links', bestFor: 'curated registries where visuals help guests choose', effort: 'medium' },
      { id: 'minimal', label: 'Minimal', description: 'Heartfelt note with understated registry links', bestFor: 'couples who want the registry to feel low-pressure', effort: 'easy' },
      { id: 'honeymoon', label: 'Honeymoon Fund', description: 'Large fund card with destination photo and contribute button', bestFor: 'travel funds and experience-first gifting', effort: 'medium' },
      { id: 'tabs', label: 'Tabbed', description: 'Tabbed layout to browse Home, Experiences, and Cash Fund registries', bestFor: 'larger registries with separate gift categories', effort: 'medium' },
      { id: 'illustrated', label: 'Illustrated', description: 'Gift icons and watercolor illustrations with registry links', bestFor: 'playful, colorful, and illustrated site styles', effort: 'medium' },
      { id: 'classic', label: 'Classic', description: 'Classic registry cards used by legacy templates and published sites', bestFor: 'legacy templates that need a familiar store-card registry', effort: 'easy' },
      { id: 'luxury', label: 'Luxury', description: 'Luxury featured registry layout used by published templates', bestFor: 'formal sites where registry content should feel elevated', effort: 'medium' },
      { id: 'experiences', label: 'Experiences', description: 'Experience-first featured registry layout used by published templates', bestFor: 'cash funds, travel experiences, and nontraditional gifts', effort: 'medium' },
      { id: 'modern', label: 'Modern', description: 'Modern registry cards used by published templates', bestFor: 'clean template styles with direct shopping links', effort: 'easy' },
      { id: 'playful', label: 'Playful', description: 'Playful registry cards used by published templates', bestFor: 'colorful sites where gifting should feel casual and warm', effort: 'easy' },
      { id: 'default', label: 'Default', description: 'Classic registry links layout kept compatible with older saved sites', bestFor: 'older site pages that should keep working unchanged', effort: 'easy' },
      { id: 'grid', label: 'Grid', description: 'Classic grid layout kept compatible with older saved sites', bestFor: 'older layouts that expect a simple registry grid', effort: 'easy' },
    ],
    capabilities: { ...defaultCapabilities, hasBindings: true },
    settingsSchema: {
      fields: [
        { key: 'showTitle', label: 'Show section title', type: 'toggle', defaultValue: true },
        { key: 'title', label: 'Section title', type: 'text', defaultValue: 'Registry' },
        { key: 'message', label: 'Gift note', type: 'textarea' },
      ],
    },
    bindingsSchema: {
      slots: [
        { key: 'linkIds', label: 'Registry gifts', dataSource: 'registry', multiple: true },
      ],
    },
    previewImagePath: '/previews/registry.jpg',
  },
  faq: {
    type: 'faq',
    label: 'FAQ',
    icon: 'HelpCircle',
    defaultVariant: 'default',
    supportedVariants: ['default', 'accordion', 'iconGrid', 'twoColumn', 'tabbed', 'chat', 'numbered'],
    variantMeta: [
      { id: 'default', label: 'Open List', description: 'All questions and answers visible at once', bestFor: 'short FAQ lists where guests should see everything immediately', effort: 'easy', recommended: true },
      { id: 'accordion', label: 'Accordion', description: 'Collapsible questions, one open at a time', bestFor: 'longer FAQ sections that need to stay compact on mobile', effort: 'easy' },
      { id: 'iconGrid', label: 'Icon Grid', description: 'Card grid with icon-led FAQ entries for quick scanning', bestFor: 'logistics-heavy sites with clear FAQ categories', effort: 'medium' },
      { id: 'twoColumn', label: 'Two Column', description: 'Q&A pairs in a two-column grid, all visible', bestFor: 'desktop-forward pages with concise answers', effort: 'medium' },
      { id: 'tabbed', label: 'Tabbed', description: 'Questions grouped by category with tab navigation', bestFor: 'larger weddings with travel, attire, RSVP, and gift groups', effort: 'advanced' },
      { id: 'chat', label: 'Chat Bubbles', description: 'Conversational Q&A styled as speech bubbles', bestFor: 'warm, casual sites that want FAQ to feel personal', effort: 'medium' },
      { id: 'numbered', label: 'Numbered', description: 'Clean numbered list with questions and answers', bestFor: 'formal pages that need a structured information list', effort: 'easy' },
    ],
    capabilities: { ...defaultCapabilities, hasBindings: true },
    settingsSchema: {
      fields: [
        { key: 'showTitle', label: 'Show section title', type: 'toggle', defaultValue: true },
        { key: 'title', label: 'Section title', type: 'text', defaultValue: 'FAQ' },
        { key: 'expandAll', label: 'Keep answers open', type: 'toggle', defaultValue: false },
      ],
    },
    bindingsSchema: {
      slots: [
        { key: 'faqIds', label: 'Guest questions', dataSource: 'faq', multiple: true },
      ],
    },
    previewImagePath: '/previews/faq.jpg',
  },
  rsvp: {
    type: 'rsvp',
    label: 'RSVP',
    icon: 'Mail',
    defaultVariant: 'default',
    supportedVariants: ['default', 'inline', 'card', 'illustrated', 'formal', 'multiEvent'],
    variantMeta: [
      { id: 'default', label: 'Full Form', description: 'Dedicated RSVP section with form fields', bestFor: 'the clearest default RSVP flow for most guests', effort: 'easy', recommended: true },
      { id: 'inline', label: 'Inline', description: 'Compact inline form embedded in the page', bestFor: 'short pages where RSVP should feel lightweight', effort: 'easy' },
      { id: 'card', label: 'Card Steps', description: 'Multi-step card form with progress indicator', bestFor: 'longer RSVP forms with meal choices or extra questions', effort: 'medium' },
      { id: 'illustrated', label: 'Illustrated', description: 'Botanical background with a centered form card', bestFor: 'romantic sites that need the RSVP to feel designed', effort: 'medium' },
      { id: 'formal', label: 'Formal', description: 'Invitation-style wording with Accepts / Declines toggle', bestFor: 'black-tie and formal invitation language', effort: 'easy' },
      { id: 'multiEvent', label: 'Multi-Event', description: 'RSVP to each wedding event separately', bestFor: 'welcome parties, brunches, and guest-specific events', effort: 'advanced' },
    ],
    capabilities: { ...defaultCapabilities, deletable: false },
    settingsSchema: {
      fields: [
        { key: 'showTitle', label: 'Show section title', type: 'toggle', defaultValue: true },
        { key: 'title', label: 'Section title', type: 'text', defaultValue: 'RSVP' },
        { key: 'deadlineText', label: 'RSVP deadline note', type: 'text' },
        { key: 'confirmationMessage', label: 'Reply confirmation message', type: 'textarea' },
        {
          key: 'mode',
          label: 'RSVP style',
          type: 'select',
          defaultValue: 'form',
          options: [
            { label: 'Built-in form', value: 'form' },
          { label: 'Outside form link', value: 'embed' },
          ],
        },
        { key: 'embedUrl', label: 'Outside form link (https://...)', type: 'text', placeholder: 'https://example.com/form' },
        { key: 'embedHeight', label: 'Form area height (px)', type: 'number', defaultValue: 760 },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/rsvp.jpg',
  },
  gallery: {
    type: 'gallery',
    label: 'Photo Gallery',
    icon: 'Images',
    defaultVariant: 'masonry',
    supportedVariants: ['masonry', 'grid', 'filmStrip', 'polaroid', 'spotlight', 'carousel', 'mosaic', 'categorized'],
    variantMeta: [
      { id: 'masonry', label: 'Masonry', description: 'Pinterest-style varied height layout with scroll animations', bestFor: 'mixed portrait and landscape galleries', effort: 'easy', recommended: true },
      { id: 'grid', label: 'Grid', description: 'Uniform grid with aspect ratio control and entrance animations', bestFor: 'clean modern galleries with consistent crops', effort: 'easy' },
      { id: 'filmStrip', label: 'Film Strip', description: 'Large hero image with thumbnail filmstrip below', bestFor: 'a small curated set where one photo should lead', effort: 'medium' },
      { id: 'polaroid', label: 'Polaroid', description: 'Scattered photo prints with a warm, vintage feel', bestFor: 'playful engagement photos and informal moments', effort: 'medium' },
      { id: 'spotlight', label: 'Spotlight', description: 'Featured large photo with thumbnail strip for navigation', bestFor: 'highlighting the best five to eight images', effort: 'medium' },
      { id: 'carousel', label: 'Carousel', description: 'Full-width slideshow with arrow navigation and captions', bestFor: 'hands-off browsing and emotional hero moments', effort: 'medium' },
      { id: 'mosaic', label: 'Mosaic', description: 'Curated editorial collage with one hero photo and supporting images', bestFor: 'luxury sites with a deliberate editorial crop set', effort: 'advanced' },
      { id: 'categorized', label: 'Categorized', description: 'Tabbed gallery with photos grouped by Ceremony, Reception, and other moments', bestFor: 'large wedding albums with suggested or custom albums', effort: 'advanced' },
    ],
    capabilities: { ...defaultCapabilities, mediaAware: true },
    settingsSchema: {
      fields: [
        { key: 'eyebrow', label: 'Small intro line', type: 'text', defaultValue: 'Our moments' },
        { key: 'headline', label: 'Section title', type: 'text', defaultValue: 'Photos' },
        { key: 'animation', label: 'Photo entrance', type: 'select', defaultValue: 'fade', options: [
          { label: 'None', value: 'none' },
          { label: 'Fade In', value: 'fade' },
          { label: 'Slide Up', value: 'slide-up' },
          { label: 'Zoom', value: 'zoom' },
          { label: 'Reveal Left', value: 'reveal-left' },
          { label: 'Reveal Right', value: 'reveal-right' },
          { label: 'Blur In', value: 'blur-in' },
          { label: 'Float In', value: 'float-in' },
          { label: 'Scale Up', value: 'scale-up' },
        ]},
        { key: 'showCaptions', label: 'Show captions', type: 'toggle', defaultValue: true },
        { key: 'enableLightbox', label: 'Open photos full size', type: 'toggle', defaultValue: true },
        { key: 'autoScroll', label: 'Auto-advance hero', type: 'toggle', defaultValue: false },
        { key: 'continuousGlide', label: 'Continuous glide rail', type: 'toggle', defaultValue: true },
        { key: 'glideSpeed', label: 'Glide speed (10-90)', type: 'number', defaultValue: 42 },
      ],
    },
    bindingsSchema: {
      slots: [
        { key: 'mediaAssetIds', label: 'Gallery photos', dataSource: 'media', multiple: true },
      ],
    },
    previewImagePath: '/previews/gallery.jpg',
  },
  countdown: {
    type: 'countdown',
    label: 'Countdown',
    icon: 'Clock',
    defaultVariant: 'default',
    supportedVariants: ['default', 'banner', 'rings', 'minimal', 'dark', 'photo'],
    variantMeta: [
      { id: 'default', label: 'Centered', description: 'Large countdown numbers centered on the page', bestFor: 'classic countdown sections that should work anywhere', effort: 'easy', recommended: true },
      { id: 'banner', label: 'Banner', description: 'Slim horizontal strip with countdown and label', bestFor: 'compact reminders between larger content sections', effort: 'easy' },
      { id: 'rings', label: 'Rings', description: 'Circular progress rings for each time unit', bestFor: 'interactive-feeling pages with a more graphic countdown', effort: 'medium' },
      { id: 'minimal', label: 'Typographic', description: 'Ultra-large display numeral showing days remaining', bestFor: 'editorial designs that want one bold number', effort: 'easy' },
      { id: 'dark', label: 'Dark & Bold', description: 'Dark background with glowing countdown numbers', bestFor: 'nightlife, reception, or high-contrast celebration sections', effort: 'medium' },
      { id: 'photo', label: 'Photo Background', description: 'Countdown overlaid on a couple photo with frosted glass panel', bestFor: 'sites with a strong engagement photo ready', effort: 'medium' },
    ],
    capabilities: { ...defaultCapabilities },
    settingsSchema: {
      fields: [
        { key: 'showTitle', label: 'Show section title', type: 'toggle', defaultValue: true },
        { key: 'title', label: 'Section title', type: 'text', placeholder: 'Couple names or custom headline' },
        { key: 'eyebrow', label: 'Small intro line', type: 'text', defaultValue: 'Counting down to' },
        { key: 'targetDate', label: 'Wedding date', type: 'text', placeholder: 'YYYY-MM-DD' },
        { key: 'message', label: 'Message below countdown', type: 'textarea' },
        { key: 'showSeconds', label: 'Show seconds', type: 'toggle', defaultValue: true },
        { key: 'imageUrl', label: 'Background photo', type: 'image' },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/countdown.jpg',
  },
  'wedding-party': {
    type: 'wedding-party',
    label: 'Wedding Party',
    icon: 'Users',
    defaultVariant: 'default',
    supportedVariants: ['default', 'grid', 'scroll', 'storyBios', 'minimal', 'splitSides'],
    variantMeta: [
      { id: 'default', label: 'Two Sides', description: 'Bridal and groom parties shown in separate rows', bestFor: 'traditional wedding party introductions', effort: 'easy', recommended: true },
      { id: 'grid', label: 'Combined Grid', description: 'All party members in a single unified grid', bestFor: 'large parties where equal treatment matters', effort: 'easy' },
      { id: 'scroll', label: 'Horizontal Scroll', description: 'Scrolling strip of tall portrait cards', bestFor: 'portrait-heavy parties and mobile browsing', effort: 'medium' },
      { id: 'storyBios', label: 'Story Bios', description: 'Full-width rows with large photo and longer personal bios', bestFor: 'small parties where each person gets a real intro', effort: 'advanced' },
      { id: 'minimal', label: 'Name List', description: 'Elegant typographic name list grouped by role', bestFor: 'formal sites without headshots ready yet', effort: 'easy' },
      { id: 'splitSides', label: 'Split Panel', description: 'Contrasting left/right panels for each side of the wedding party', bestFor: 'balanced partner-side storytelling', effort: 'medium' },
    ],
    capabilities: { ...defaultCapabilities, mediaAware: true },
    settingsSchema: {
      fields: [
        { key: 'showTitle', label: 'Show section title', type: 'toggle', defaultValue: true },
        { key: 'title', label: 'Section title', type: 'text', defaultValue: 'Wedding Party' },
        { key: 'eyebrow', label: 'Small intro line', type: 'text', defaultValue: 'The crew' },
        { key: 'subtitle', label: 'Subtitle', type: 'textarea' },
        { key: 'bridalTitle', label: "Partner 1 side name", type: 'text', placeholder: "Partner 1's side" },
        { key: 'groomTitle', label: "Partner 2 side name", type: 'text', placeholder: "Partner 2's side" },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/wedding-party.jpg',
  },
  'dress-code': {
    type: 'dress-code',
    label: 'Dress Code',
    icon: 'Shirt',
    defaultVariant: 'default',
    supportedVariants: ['default', 'banner', 'palette', 'illustrated', 'card', 'scale'],
    variantMeta: [
      { id: 'default', label: 'Full', description: 'Dress code with description and style suggestions', bestFor: 'most couples who want clear attire guidance without overthinking it', effort: 'easy', recommended: true },
      { id: 'banner', label: 'Banner', description: 'Compact horizontal banner with dress code name', bestFor: 'simple attire notes that should not dominate the page', effort: 'easy' },
      { id: 'palette', label: 'Color Palette', description: 'Color swatches showing encouraged and avoid colors', bestFor: 'color-specific dress codes and garden-party palettes', effort: 'medium' },
      { id: 'illustrated', label: 'Illustrated', description: 'Fashion silhouette illustrations showing example outfits', bestFor: 'visual outfit guidance for guests who need examples', effort: 'advanced' },
      { id: 'card', label: 'Do & Don\'t Card', description: 'Card with encouraged, avoid, and notes columns', bestFor: 'clear rules when there are important attire boundaries', effort: 'medium' },
      { id: 'scale', label: 'Formality Scale', description: 'Visual spectrum bar showing where the dress code falls', bestFor: 'explaining semi-formal or in-between dress codes', effort: 'medium' },
    ],
    capabilities: { ...defaultCapabilities },
    settingsSchema: {
      fields: [
        { key: 'showTitle', label: 'Show section title', type: 'toggle', defaultValue: true },
        { key: 'eyebrow', label: 'Small intro line', type: 'text', defaultValue: 'What to wear' },
        { key: 'presetCode', label: 'Dress code style', type: 'select', options: [
          { label: 'Black Tie', value: 'black-tie' },
          { label: 'Black Tie Optional', value: 'black-tie-optional' },
          { label: 'Cocktail', value: 'cocktail' },
          { label: 'Garden Party', value: 'garden-party' },
          { label: 'Semi-Formal', value: 'semi-formal' },
          { label: 'Casual', value: 'casual' },
          { label: 'Custom', value: '' },
        ]},
        { key: 'dressCodeLabel', label: 'Dress code name', type: 'text', placeholder: 'e.g. Festive Attire' },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'colorNote', label: 'Color note', type: 'text', placeholder: 'e.g. Please avoid white' },
        { key: 'additionalNote', label: 'Extra note', type: 'text' },
        { key: 'avoidNote', label: 'Please avoid', type: 'text' },
        { key: 'formalityLevel', label: 'Formality level (1-5)', type: 'number', defaultValue: 3 },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/dress-code.jpg',
  },
  accommodations: {
    type: 'accommodations',
    label: 'Accommodations',
    icon: 'Hotel',
    defaultVariant: 'default',
    supportedVariants: ['default', 'cards', 'featured', 'mapList', 'faqStyle', 'onSite'],
    variantMeta: [
      { id: 'default', label: 'List', description: 'Hotels listed with booking codes and details', bestFor: 'simple room blocks with one or two recommended hotels', effort: 'easy', recommended: true },
      { id: 'cards', label: 'Cards', description: 'Each hotel in its own card with booking info', bestFor: 'multiple hotels that need equal weight and direct links', effort: 'easy' },
      { id: 'featured', label: 'Featured Block', description: 'Prominent hotel block card with deadline and booking code', bestFor: 'one preferred hotel block with a booking deadline', effort: 'medium' },
      { id: 'mapList', label: 'Map & List', description: 'Interactive map with hotel pins and a list below', bestFor: 'destination weekends where distance to venue matters', effort: 'advanced' },
      { id: 'faqStyle', label: 'FAQ Style', description: 'Intro with accordion Q&A for parking, shuttle, and booking', bestFor: 'hotel details mixed with shuttle and booking questions', effort: 'medium' },
      { id: 'onSite', label: 'On-Site Lodging', description: 'Estate or inn accommodation feature with photo and booking', bestFor: 'venues with on-property lodging or estate rooms', effort: 'medium' },
    ],
    capabilities: { ...defaultCapabilities },
    settingsSchema: {
      fields: [
        { key: 'showTitle', label: 'Show section title', type: 'toggle', defaultValue: true },
        { key: 'title', label: 'Section title', type: 'text', defaultValue: 'Accommodations' },
        { key: 'eyebrow', label: 'Small intro line', type: 'text', defaultValue: 'Where to stay' },
        { key: 'generalNote', label: 'Guest lodging note', type: 'textarea' },
        { key: 'blockNote', label: 'Room block note', type: 'textarea' },
        { key: 'shuttleNote', label: 'Shuttle note', type: 'textarea' },
        { key: 'mapImage', label: 'Map or lodging image', type: 'image' },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/accommodations.jpg',
  },
  contact: {
    type: 'contact',
    label: 'Contact / Guest Polls',
    icon: 'MessageCircle',
    defaultVariant: 'default',
    supportedVariants: ['default', 'minimal', 'form', 'split', 'casual', 'coordinator', 'interactiveHub'],
    variantMeta: [
      { id: 'default', label: 'Full', description: 'Contact cards with name, role, and contact links', bestFor: 'clear couple and planner contact information', effort: 'easy', recommended: true },
      { id: 'minimal', label: 'Minimal', description: 'Slim bar with contact links inline', bestFor: 'small sites that only need one contact line', effort: 'easy' },
      { id: 'form', label: 'Message Form', description: 'Contact form with name, email, and message fields', bestFor: 'collecting guest questions without exposing direct contact details', effort: 'medium' },
      { id: 'split', label: 'Form & Details', description: 'Form on the left, contact info and social links on the right', bestFor: 'pages that need both a form and human contact context', effort: 'medium' },
      { id: 'casual', label: 'Casual Ask', description: 'Warm heading, couple photo, and single-field email input', bestFor: 'friendly casual sites with a light-touch question prompt', effort: 'easy' },
      { id: 'coordinator', label: 'Coordinator', description: 'Couple contact info plus wedding coordinator card', bestFor: 'weddings with a planner or day-of coordinator contact', effort: 'medium' },
      { id: 'interactiveHub', label: 'Polls & Quiz', description: 'Live polls, quiz, and open-ended guest prompts with results', bestFor: 'guest participation, quizzes, and playful wedding-site engagement', effort: 'advanced' },
    ],
    capabilities: { ...defaultCapabilities },
    settingsSchema: {
      fields: [
        { key: 'showTitle', label: 'Show section title', type: 'toggle', defaultValue: true },
        { key: 'title', label: 'Section title', type: 'text', defaultValue: 'Questions?' },
        { key: 'eyebrow', label: 'Small intro line', type: 'text', defaultValue: 'Need help?' },
        { key: 'subtitle', label: 'Subtitle', type: 'textarea' },
        { key: 'introText', label: 'Intro text', type: 'textarea' },
        { key: 'emailSubject', label: 'Email subject', type: 'text', defaultValue: 'Wedding Question' },
        { key: 'closingNote', label: 'Closing note', type: 'text' },
        { key: 'pollPrompt', label: 'Poll question', type: 'text', placeholder: 'What should our signature drink be?' },
        { key: 'pollOptions', label: 'Poll choices (one per line)', type: 'textarea', placeholder: 'Spicy margarita\nFrench 75\nEspresso martini' },
        { key: 'quizPrompt', label: 'Quiz question', type: 'text', placeholder: 'Who made the first move?' },
        { key: 'quizOptions', label: 'Quiz answers (one per line)', type: 'textarea', placeholder: 'Partner one\nPartner two\nMutual friends' },
        { key: 'correctQuizOption', label: 'Right answer', type: 'text', placeholder: 'Partner two' },
        { key: 'suggestionPrompt', label: 'Open question', type: 'text', placeholder: 'Signature drink ideas' },
        { key: 'allowPublicResults', label: 'Show guest results', type: 'toggle', defaultValue: true },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/contact.jpg',
  },
  'footer-cta': {
    type: 'footer-cta',
    label: 'Footer / RSVP Push',
    icon: 'ArrowRight',
    defaultVariant: 'default',
    supportedVariants: ['default', 'minimal', 'monogram', 'hashtag', 'photo', 'countdown'],
    variantMeta: [
      { id: 'default', label: 'Bold', description: 'Full-width colored section with names and RSVP button', bestFor: 'a clear final RSVP push before the page ends', effort: 'easy', recommended: true },
      { id: 'minimal', label: 'Minimal', description: 'Clean footer section on white with centered RSVP button', bestFor: 'quiet editorial pages that need a restrained ending', effort: 'easy' },
      { id: 'monogram', label: 'Monogram', description: 'Large couple monogram or crest with names and date', bestFor: 'formal sites with initials, crest, or stationery direction', effort: 'medium' },
      { id: 'hashtag', label: 'Hashtag CTA', description: 'Social hashtag in display type with Instagram share prompt', bestFor: 'social-heavy weddings with an event hashtag', effort: 'easy' },
      { id: 'photo', label: 'Closing photo', description: 'Romantic couple photo spanning full width with name overlay', bestFor: 'ending the site with one emotional photo moment', effort: 'medium' },
      { id: 'countdown', label: 'Countdown Push', description: 'RSVP deadline reminder with countdown and action button', bestFor: 'sites where guests need urgency before RSVP closes', effort: 'medium' },
    ],
    capabilities: { ...defaultCapabilities, deletable: false },
    settingsSchema: {
      fields: [
        { key: 'headline', label: 'Headline', type: 'text', defaultValue: 'We hope to see you there' },
        { key: 'subtext', label: 'Subtext', type: 'text' },
        { key: 'ctaLabel', label: 'Button text', type: 'text', defaultValue: 'RSVP Now' },
        { key: 'ctaHref', label: 'RSVP link', type: 'text', defaultValue: '#rsvp' },
        { key: 'monogram', label: 'Monogram', type: 'text', defaultValue: 'K & E' },
        { key: 'hashtag', label: 'Hashtag', type: 'text', defaultValue: '#KaraAndEric' },
        { key: 'photoUrl', label: 'Closing photo', type: 'image' },
        { key: 'footerNote', label: 'Small closing note', type: 'text' },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/footer-cta.jpg',
  },
  custom: {
    type: 'custom',
    label: 'Custom Section',
    icon: 'Layout',
    defaultVariant: 'default',
    supportedVariants: ['default'],
    variantMeta: [
      { id: 'default', label: 'Custom', description: 'Build your own section from a pre-made skeleton', bestFor: 'one-off moments that do not fit a standard wedding section', effort: 'advanced', recommended: true },
    ],
    capabilities: { ...defaultCapabilities },
    settingsSchema: {
      fields: [
        { key: 'backgroundColor', label: 'Background color', type: 'color', defaultValue: '#ffffff' },
        { key: 'paddingSize', label: 'Section spacing', type: 'select', defaultValue: 'md', options: [
          { label: 'Compact', value: 'sm' },
          { label: 'Normal', value: 'md' },
          { label: 'Spacious', value: 'lg' },
        ]},
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/custom.jpg',
  },
  quotes: {
    type: 'quotes',
    label: 'Quotes & Wishes',
    icon: 'Quote',
    defaultVariant: 'carousel',
    supportedVariants: ['carousel', 'grid', 'featured', 'pullQuote', 'guestbook', 'letter'],
    variantMeta: [
      { id: 'carousel', label: 'Carousel', description: 'One quote at a time with auto-advance and dot navigation', bestFor: 'a small set of wishes or quotes that should feel alive', effort: 'easy', recommended: true },
      { id: 'grid', label: 'Grid', description: 'All quotes displayed in a beautiful card grid', bestFor: 'many family wishes that guests may browse all at once', effort: 'easy' },
      { id: 'featured', label: 'Featured', description: 'Spotlight one featured quote with supporting quotes below', bestFor: 'one meaningful quote plus a few supporting messages', effort: 'medium' },
      { id: 'pullQuote', label: 'Pull Quote', description: 'One large meaningful quote in italic serif with decorative marks', bestFor: 'a single poem, vow excerpt, or family blessing', effort: 'easy' },
      { id: 'guestbook', label: 'Guestbook', description: 'Interactive wishing well where guests leave messages', bestFor: 'collecting guest notes before or after the wedding', effort: 'advanced' },
      { id: 'letter', label: 'Love Letter', description: 'Letter styled with paper texture and handwriting font from the couple', bestFor: 'a personal note from the couple to guests', effort: 'medium' },
    ],
    capabilities: { ...defaultCapabilities },
    settingsSchema: {
      fields: [
        { key: 'eyebrow', label: 'Small intro line', type: 'text', defaultValue: 'Wishes & Words' },
        { key: 'headline', label: 'Section title', type: 'text', defaultValue: 'What everyone is saying' },
        { key: 'background', label: 'Background', type: 'select', defaultValue: 'soft', options: [
          { label: 'White', value: 'white' },
          { label: 'Soft', value: 'soft' },
          { label: 'Dark', value: 'dark' },
        ]},
        { key: 'autoplay', label: 'Auto-advance (carousel only)', type: 'toggle', defaultValue: true },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/quotes.jpg',
  },
  menu: {
    type: 'menu',
    label: 'Dining & Menu',
    icon: 'UtensilsCrossed',
    defaultVariant: 'tabs',
    supportedVariants: ['tabs', 'card', 'simple', 'printed', 'cocktailDinner', 'illustrated'],
    variantMeta: [
      { id: 'tabs', label: 'Course Tabs', description: 'Tab switcher for each course with itemized dishes', bestFor: 'multi-course dinners where guests want to browse by course', effort: 'medium', recommended: true },
      { id: 'card', label: 'Menu Cards', description: 'Each course in its own elegant card', bestFor: 'formal plated dinners with a small number of courses', effort: 'easy' },
      { id: 'simple', label: 'Simple List', description: 'Clean single-column menu list with numbered items', bestFor: 'simple menus that need to stay readable on mobile', effort: 'easy' },
      { id: 'printed', label: 'Printed Menu', description: 'Formal centered layout styled like a printed dinner menu card', bestFor: 'black-tie dinners and invitation-style typography', effort: 'medium' },
      { id: 'cocktailDinner', label: 'Cocktail & Dinner', description: 'Two-section layout: cocktail hour stations and plated dinner', bestFor: 'receptions with both passed bites and dinner service', effort: 'medium' },
      { id: 'illustrated', label: 'Illustrated', description: 'Menu items with hand-drawn food illustrations', bestFor: 'playful or food-forward weddings with custom personality', effort: 'advanced' },
    ],
    capabilities: { ...defaultCapabilities },
    settingsSchema: {
      fields: [
        { key: 'eyebrow', label: 'Small intro line', type: 'text', defaultValue: 'Dining' },
        { key: 'headline', label: 'Section title', type: 'text', defaultValue: 'The Menu' },
        { key: 'subtitle', label: 'Subtitle', type: 'text' },
        { key: 'note', label: 'Dietary note', type: 'textarea' },
        { key: 'backgroundImage', label: 'Background photo', type: 'image' },
        { key: 'showDietaryIcons', label: 'Show dietary icons', type: 'toggle', defaultValue: true },
        { key: 'showDietaryKey', label: 'Show dietary key', type: 'toggle', defaultValue: true },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/menu.jpg',
  },
  music: {
    type: 'music',
    label: 'Music & Playlist',
    icon: 'Music',
    defaultVariant: 'playlist',
    supportedVariants: ['playlist', 'setlist', 'compact', 'vinyl', 'requestForm', 'journey'],
    variantMeta: [
      { id: 'playlist', label: 'Playlist', description: 'Tabbed playlists per moment with Spotify / Apple Music links', bestFor: 'sharing a Spotify playlist and setting the weekend mood', effort: 'easy', recommended: true },
      { id: 'setlist', label: 'Special Songs', description: 'Highlight key songs for each special moment', bestFor: 'ceremony, first dance, parent dance, and last song details', effort: 'easy' },
      { id: 'compact', label: 'Compact List', description: 'Clean numbered song list in a single card', bestFor: 'simple soundtracks without extra decoration', effort: 'easy' },
      { id: 'vinyl', label: 'Vinyl Record', description: 'Music streaming-inspired layout with album art cards', bestFor: 'stylized music-forward weddings', effort: 'medium' },
      { id: 'requestForm', label: 'Song Request', description: 'Interactive form for guests to suggest dance floor songs', bestFor: 'guest participation and reception energy', effort: 'medium' },
      { id: 'journey', label: 'Music Journey', description: 'Timeline of the day\'s music arc from ceremony to reception', bestFor: 'telling the story of the day through music', effort: 'advanced' },
    ],
    capabilities: { ...defaultCapabilities },
    settingsSchema: {
      fields: [
        { key: 'eyebrow', label: 'Small intro line', type: 'text', defaultValue: 'The Soundtrack' },
        { key: 'headline', label: 'Section title', type: 'text', defaultValue: 'Music for Our Day' },
        { key: 'subtitle', label: 'Subtitle', type: 'text' },
        { key: 'djBandName', label: 'DJ or band name', type: 'text' },
        { key: 'djBandLabel', label: 'Entertainment label', type: 'text', defaultValue: 'Entertainment by' },
        { key: 'requestNote', label: 'Song request note', type: 'text' },
        { key: 'showRequestNote', label: 'Show song request', type: 'toggle', defaultValue: true },
        { key: 'playlistUrl', label: 'Spotify playlist link', type: 'text', placeholder: 'https://open.spotify.com/playlist/...' },
        { key: 'promptLabel', label: 'Guest song prompt', type: 'text', defaultValue: 'What song gets you on the dance floor?' },
        { key: 'placeholder', label: 'Song field hint', type: 'text', defaultValue: 'Song title and artist' },
        { key: 'buttonLabel', label: 'Song button label', type: 'text', defaultValue: 'Send song' },
        { key: 'showRecentRequests', label: 'Show recent guest requests', type: 'toggle', defaultValue: true },
        { key: 'background', label: 'Background style', type: 'select', defaultValue: 'gradient', options: [
          { label: 'White', value: 'white' },
          { label: 'Dark', value: 'dark' },
          { label: 'Gradient', value: 'gradient' },
          { label: 'Cream', value: 'cream' },
          { label: 'Green', value: 'green' },
        ]},
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/music.jpg',
  },
  directions: {
    type: 'directions',
    label: 'Directions & Map',
    icon: 'MapPin',
    defaultVariant: 'pin',
    supportedVariants: ['pin', 'split', 'card', 'illustrated', 'multiVenue', 'transport', 'fromHotel'],
    variantMeta: [
      { id: 'pin', label: 'Pin & Details', description: 'Address and transport info alongside an embedded map', bestFor: 'most weddings with one primary venue address', effort: 'easy', recommended: true },
      { id: 'split', label: 'Split Screen', description: 'Full-height split layout with details and map side by side', bestFor: 'desktop-forward pages with enough map and copy detail', effort: 'medium' },
      { id: 'card', label: 'Map Card', description: 'All-in-one card with map, address, and directions', bestFor: 'compact pages that need directions in one contained block', effort: 'easy' },
      { id: 'illustrated', label: 'Illustrated Map', description: 'Hand-drawn area map with venue and hotel pins', bestFor: 'destination weddings with a custom weekend map feel', effort: 'advanced' },
      { id: 'multiVenue', label: 'Multi-Venue Pins', description: 'Map showing ceremony, reception, and hotel locations', bestFor: 'weekends with multiple venues guests must navigate', effort: 'advanced' },
      { id: 'transport', label: 'By Air / Car / Train', description: 'Transport columns for driving, flying, and transit guests', bestFor: 'out-of-town guest lists with mixed travel modes', effort: 'medium' },
      { id: 'fromHotel', label: 'From Your Hotel', description: 'Step-by-step directions from each hotel block to the venue', bestFor: 'hotel-block weddings with shuttle or ride-share guidance', effort: 'medium' },
    ],
    capabilities: { ...defaultCapabilities },
    settingsSchema: {
      fields: [
        { key: 'eyebrow', label: 'Small intro line', type: 'text', defaultValue: 'Travel details' },
        { key: 'headline', label: 'Section title', type: 'text', defaultValue: 'Directions and parking' },
        { key: 'venueName', label: 'Venue name', type: 'text' },
        { key: 'address', label: 'Street address', type: 'text' },
        { key: 'city', label: 'City, State, ZIP', type: 'text' },
        { key: 'mapUrl', label: 'Map link (optional)', type: 'text', placeholder: 'Leave blank to auto-generate from address' },
        { key: 'parkingNote', label: 'Parking note', type: 'textarea' },
        { key: 'shuttleNote', label: 'Shuttle note', type: 'textarea' },
        { key: 'publicTransitNote', label: 'Transit note', type: 'textarea' },
        { key: 'drivingTime', label: 'Driving time (e.g. 25 min)', type: 'text' },
        { key: 'drivingTimeFrom', label: 'Driving from', type: 'text', defaultValue: 'downtown' },
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/directions.jpg',
  },
  video: {
    type: 'video',
    label: 'Video',
    icon: 'Play',
    defaultVariant: 'full',
    supportedVariants: ['full', 'card', 'inline', 'background', 'lightbox', 'reel'],
    variantMeta: [
      { id: 'full', label: 'Full Width', description: 'Large cinematic video player centered on the page', bestFor: 'one polished film or highlight reel guests should not miss', effort: 'easy', recommended: true },
      { id: 'card', label: 'Video Cards', description: 'Multiple video cards for save-the-dates and highlight reels', bestFor: 'multiple clips such as proposal, save-the-date, and recap', effort: 'medium' },
      { id: 'inline', label: 'Inline', description: 'Side-by-side video and text content', bestFor: 'video with a meaningful note or context beside it', effort: 'medium' },
      { id: 'background', label: 'Video Background', description: 'Muted looping video as section background with text overlay', bestFor: 'high-impact motion moments with short looping clips', effort: 'advanced' },
      { id: 'lightbox', label: 'Lightbox Trigger', description: 'Static photo with play button that opens a full-screen video modal', bestFor: 'keeping the page calm while offering a cinematic reveal', effort: 'medium' },
      { id: 'reel', label: 'Short Reel', description: 'Portrait 9:16 video in a phone frame for save-the-date reels', bestFor: 'vertical social clips and mobile-first save-the-dates', effort: 'advanced' },
    ],
    capabilities: { ...defaultCapabilities },
    settingsSchema: {
      fields: [
        { key: 'eyebrow', label: 'Small intro line', type: 'text' },
        { key: 'headline', label: 'Section title', type: 'text', defaultValue: 'A short film from us' },
        { key: 'subtitle', label: 'Subtitle', type: 'text' },
        { key: 'videoUrl', label: 'Video link (YouTube or Vimeo)', type: 'text', placeholder: 'https://youtube.com/watch?v=...' },
        { key: 'thumbnailUrl', label: 'Thumbnail image link', type: 'text' },
        { key: 'videoType', label: 'Video source', type: 'select', defaultValue: 'youtube', options: [
          { label: 'YouTube', value: 'youtube' },
          { label: 'Vimeo', value: 'vimeo' },
          { label: 'Direct link', value: 'direct' },
        ]},
        { key: 'background', label: 'Background', type: 'select', defaultValue: 'dark', options: [
          { label: 'Dark', value: 'dark' },
          { label: 'White', value: 'white' },
          { label: 'Soft', value: 'soft' },
        ]},
      ],
    },
    bindingsSchema: { slots: [] },
    previewImagePath: '/previews/video.jpg',
  },
};

export function getSectionManifest(type: BuilderSectionType): BuilderSectionDefinitionWithMeta {
  const manifest = SECTION_MANIFESTS[type];
  if (!manifest) throw new Error(`Unknown section type: ${type}`);
  return manifest;
}

export function getAllSectionManifests(): BuilderSectionDefinitionWithMeta[] {
  return Object.values(SECTION_MANIFESTS);
}

export function getDefaultSectionInstance(
  type: BuilderSectionType,
  variant?: string,
  orderIndex = 0
): BuilderSectionInstance {
  const manifest = getSectionManifest(type);
  return createDefaultSectionInstance(type, variant ?? manifest.defaultVariant, orderIndex);
}
