import type { NameChangeFormRegistryEntry, NameChangeInstitutionEntry } from './types';

export const NAME_CHANGE_ENGINE_VERSION = '2026-04-18.2';

export const NAME_CHANGE_FORM_REGISTRY: NameChangeFormRegistryEntry[] = [
  {
    code: 'SSA-SS5',
    title: 'Application for a Social Security Card',
    authority: 'Social Security Administration',
    jurisdiction: 'federal',
    url: 'https://www.ssa.gov/forms/ss-5.pdf',
    appliesWhen: ['marriage', 'court_order'],
    description: 'Primary federal identity update for your Social Security record after a legal name change.',
  },
  {
    code: 'CA-DMV-DL44',
    title: 'Driver License / Identification Card Application',
    authority: 'California DMV',
    jurisdiction: 'state',
    url: 'https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/',
    appliesWhen: ['california_resident', 'marriage', 'court_order'],
    description: 'Used when updating your California driver license or state ID after the SSA record changes.',
  },
  {
    code: 'DS-82',
    title: 'U.S. Passport Renewal Application',
    authority: 'U.S. Department of State',
    jurisdiction: 'federal',
    url: 'https://travel.state.gov/content/travel/en/passports/how-apply/forms.html',
    appliesWhen: ['passport', 'marriage', 'court_order', 'citizen'],
    description: 'Typical mail renewal path when your passport is eligible for renewal and needs the new name.',
  },
  {
    code: 'DS-11',
    title: 'Application for a U.S. Passport',
    authority: 'U.S. Department of State',
    jurisdiction: 'federal',
    url: 'https://travel.state.gov/content/travel/en/passports/how-apply/forms.html',
    appliesWhen: ['passport', 'marriage', 'court_order', 'citizen'],
    description: 'Use when a brand-new passport application is required rather than a renewal flow.',
  },
  {
    code: 'DS-5504',
    title: 'Passport Re-Application / Data Correction',
    authority: 'U.S. Department of State',
    jurisdiction: 'federal',
    url: 'https://travel.state.gov/content/travel/en/passports/how-apply/forms.html',
    appliesWhen: ['passport', 'marriage', 'court_order', 'citizen'],
    description: 'Used when a recent passport issuance qualifies for a low-friction name change or correction path.',
  },
  {
    code: 'CA-SUPERIOR-COURT-NC',
    title: 'California Civil Name Change Petition Packet',
    authority: 'California Superior Court',
    jurisdiction: 'state',
    url: 'https://selfhelp.courts.ca.gov/name-change',
    appliesWhen: ['court_order', 'california_resident'],
    description: 'Court petition path when the requested name is outside a marriage-based CA shortcut.',
  },
];

export const NAME_CHANGE_INSTITUTION_LIBRARY: NameChangeInstitutionEntry[] = [
  {
    key: 'irs-records',
    label: 'IRS name / tax record alignment',
    category: 'government',
    launchPriority: 12,
    triggers: ['all'],
    notes: 'IRS records follow your Social Security record, so confirm tax and withholding systems are using the same legal name after SSA lands.',
    suggestedTiming: 'Right after SSA confirmation and before payroll or filing mismatches pile up',
    evidenceNeeded: ['Updated Social Security record', 'Recent tax filing or IRS account details'],
    reminderDaysAfterPrimaryId: 1,
  },
  {
    key: 'irs-employer',
    label: 'Employer payroll / HR',
    category: 'employment',
    launchPriority: 10,
    triggers: ['employment'],
    notes: 'Update payroll and benefits after SSA so tax reporting lines up cleanly.',
    suggestedTiming: 'Within 1-3 business days after SSA confirmation',
    evidenceNeeded: ['Updated Social Security record', 'Updated photo ID when available', 'Payroll or benefits account details'],
    reminderDaysAfterPrimaryId: 2,
  },
  {
    key: 'banks',
    label: 'Banks and credit cards',
    category: 'financial',
    launchPriority: 20,
    triggers: ['all'],
    notes: 'Usually easiest after your main photo ID reflects the new name.',
    suggestedTiming: 'Within the first week after DMV or passport reflects the new name',
    evidenceNeeded: ['Updated photo ID', 'Legal proof document', 'Debit / credit or account details'],
    reminderDaysAfterPrimaryId: 5,
  },
  {
    key: 'investments-loans',
    label: 'Investment, retirement, and loan accounts',
    category: 'financial',
    launchPriority: 22,
    triggers: ['all'],
    notes: 'Carry the same name through brokerages, retirement plans, servicers, and lending portals so statements and verification checks stop splitting.',
    suggestedTiming: 'Within the first week after DMV or passport reflects the new name',
    evidenceNeeded: ['Updated photo ID', 'Legal proof document', 'Account or loan numbers'],
    reminderDaysAfterPrimaryId: 6,
  },
  {
    key: 'insurance',
    label: 'Health, dental, vision, auto, renters, and life insurance',
    category: 'insurance',
    launchPriority: 30,
    triggers: ['all'],
    notes: 'Update policyholder names so claims and cards stay consistent.',
    suggestedTiming: 'During the first 1-2 weeks after primary ID changes',
    evidenceNeeded: ['Updated photo ID', 'Policy numbers', 'Legal proof document'],
    reminderDaysAfterPrimaryId: 7,
  },
  {
    key: 'disability-insurance',
    label: 'Disability insurance and leave administrators',
    category: 'insurance',
    launchPriority: 31,
    triggers: ['employment'],
    notes: 'Short-term disability, leave vendors, and income-protection carriers should match payroll and benefits records.',
    suggestedTiming: 'At the same time as payroll and benefits updates',
    evidenceNeeded: ['Updated Social Security record', 'Updated photo ID when available', 'Policy or claim identifiers'],
    reminderDaysAfterPrimaryId: 4,
  },
  {
    key: 'medical-records',
    label: 'Medical providers / insurance cards',
    category: 'insurance',
    launchPriority: 32,
    triggers: ['all'],
    notes: 'Update provider rosters, patient portals, and member-card records once your primary ID is moving.',
    suggestedTiming: 'During the first 1-2 weeks after primary ID changes',
    evidenceNeeded: ['Updated photo ID', 'Insurance card or portal details', 'Legal proof document'],
    reminderDaysAfterPrimaryId: 8,
  },
  {
    key: 'utilities-housing',
    label: 'Utilities, lease, and landlord records',
    category: 'personal',
    launchPriority: 35,
    triggers: ['all'],
    notes: 'Useful once your primary ID is moving so leases, portals, and mailed statements stop drifting.',
    suggestedTiming: 'During the first 1-2 weeks after primary ID changes',
    evidenceNeeded: ['Updated photo ID when available', 'Utility or lease account details', 'Legal proof document'],
    reminderDaysAfterPrimaryId: 8,
  },
  {
    key: 'phone-digital-identity',
    label: 'Phone plan, email/domain, and primary digital identity',
    category: 'personal',
    launchPriority: 36,
    triggers: ['all'],
    notes: 'Clean up your phone account, email display names, domain registrations, and recovery channels before other services keep syncing the old name back in.',
    suggestedTiming: 'During the first 1-2 weeks after primary ID changes',
    evidenceNeeded: ['Updated photo ID when available', 'Carrier or registrar account details', 'Legal proof document'],
    reminderDaysAfterPrimaryId: 9,
  },
  {
    key: 'subscriptions-social',
    label: 'Subscriptions, social profiles, and lifestyle memberships',
    category: 'personal',
    launchPriority: 37,
    triggers: ['all'],
    notes: 'Update recurring services, creator profiles, and memberships after the legal-facing systems stop moving.',
    suggestedTiming: 'After banks, payroll, and insurance are stable',
    evidenceNeeded: ['Updated preferred display name', 'Service login access'],
    reminderDaysAfterPrimaryId: 12,
  },
  {
    key: 'courtesy-social-sync',
    label: 'Courtesy / social identity sync',
    category: 'personal',
    launchPriority: 90,
    triggers: ['all'],
    notes: 'Best for display names, loyalty profiles, and non-legal-facing account labels once the core admin trail is underway.',
    suggestedTiming: 'After the major legal and institutional records are already in motion',
    evidenceNeeded: ['Updated preferred display name', 'Account login or loyalty profile access'],
    reminderDaysAfterPrimaryId: 14,
  },
  {
    key: 'voter-registration',
    label: 'California voter registration',
    category: 'government',
    launchPriority: 40,
    triggers: ['california_resident'],
    notes: 'California can be updated after your DMV record is settled.',
    suggestedTiming: 'After California DMV reflects the new name',
    evidenceNeeded: ['Updated California DMV record'],
    reminderDaysAfterPrimaryId: 10,
  },
  {
    key: 'tsa-precheck',
    label: 'TSA PreCheck, Global Entry, and airline profiles',
    category: 'personal',
    launchPriority: 50,
    triggers: ['passport'],
    notes: 'Do this after passport or Real ID updates so future travel bookings match.',
    suggestedTiming: 'Immediately after passport or Real ID details match travel bookings',
    evidenceNeeded: ['Updated passport or Real ID', 'Known traveler / loyalty account details'],
    reminderDaysAfterPrimaryId: 1,
  },
  {
    key: 'travel-hospitality',
    label: 'Hotel loyalty, car registration/title, and auto insurance follow-through',
    category: 'personal',
    launchPriority: 52,
    triggers: ['all'],
    notes: 'Finish the travel and mobility stack so reservations, registration, title, and vehicle coverage all match the same identity chain.',
    suggestedTiming: 'After DMV is updated, and after passport if future travel bookings are in play',
    evidenceNeeded: ['Updated DMV record', 'Updated auto policy or title details', 'Loyalty account details'],
    reminderDaysAfterPrimaryId: 11,
  },
  {
    key: 'professional-licenses',
    label: 'Professional licenses and certifications',
    category: 'personal',
    launchPriority: 60,
    triggers: ['employment'],
    notes: 'This matters for healthcare, legal, education, and other licensed work.',
    suggestedTiming: 'Within 1-2 weeks unless your employer or regulator needs it sooner',
    evidenceNeeded: ['Updated ID', 'License numbers', 'Legal proof document'],
    reminderDaysAfterPrimaryId: 10,
  },
];
