import type { NameChangeFormRegistryEntry, NameChangeInstitutionEntry } from './types';

export const NAME_CHANGE_ENGINE_VERSION = '2026-04-18.2';

export const NAME_CHANGE_FORM_REGISTRY: NameChangeFormRegistryEntry[] = [
  {
    code: 'SSA-SS5',
    title: 'Application for a Social Security Card',
    authority: 'Social Security Administration',
    jurisdiction: 'federal',
    url: 'https://www.ssa.gov/forms/ss-5.pdf',
    appliesWhen: ['marriage', 'court_order'],
    description: 'Primary federal identity update for your Social Security record after a legal name change.',
  },
  {
    code: 'CA-DMV-DL44',
    title: 'Driver License / Identification Card Application',
    authority: 'California DMV',
    jurisdiction: 'state',
    url: 'https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/',
    appliesWhen: ['california_resident', 'marriage', 'court_order'],
    description: 'Used when updating your California driver license or state ID after the SSA record changes.',
  },
  {
    code: 'DS-82',
    title: 'U.S. Passport Renewal Application',
    authority: 'U.S. Department of State',
    jurisdiction: 'federal',
    url: 'https://travel.state.gov/content/travel/en/passports/how-apply/forms.html',
    appliesWhen: ['passport', 'marriage', 'court_order', 'citizen'],
    description: 'Typical mail renewal path when your passport is eligible for renewal and needs the new name.',
  },
  {
    code: 'DS-11',
    title: 'Application for a U.S. Passport',
    authority: 'U.S. Department of State',
    jurisdiction: 'federal',
    url: 'https://travel.state.gov/content/travel/en/passports/how-apply/forms.html',
    appliesWhen: ['passport', 'marriage', 'court_order', 'citizen'],
    description: 'Use when a brand-new passport application is required rather than a renewal flow.',
  },
  {
    code: 'DS-5504',
    title: 'Passport Re-Application / Data Correction',
    authority: 'U.S. Department of State',
    jurisdiction: 'federal',
    url: 'https://travel.state.gov/content/travel/en/passports/how-apply/forms.html',
    appliesWhen: ['passport', 'marriage', 'court_order', 'citizen'],
    description: 'Used when a recent passport issuance qualifies for a low-friction name change or correction path.',
  },
  {
    code: 'CA-SUPERIOR-COURT-NC',
    title: 'California Civil Name Change Petition Packet',
    authority: 'California Superior Court',
    jurisdiction: 'state',
    url: 'https://selfhelp.courts.ca.gov/name-change',
    appliesWhen: ['court_order', 'california_resident'],
    description: 'Court petition path when the requested name is outside a marriage-based CA shortcut.',
  },
];

export const NAME_CHANGE_INSTITUTION_LIBRARY: NameChangeInstitutionEntry[] = [
  {
    key: 'uscis-immigration-records',
    label: 'USCIS / immigration records',
    category: 'government',
    launchPriority: 8,
    triggers: ['all'],
    notes: 'If your identity touches immigration records, update them deliberately so federal status records, work authorization, and future travel checks do not drift from your new legal name.',
    suggestedTiming: 'Immediately after the legal proof is grounded, and before relying on downstream federal identity systems',
    evidenceNeeded: ['Certified legal proof document', 'Current immigration document or case number', 'Updated Social Security record when required'],
    reminderDaysAfterPrimaryId: 2,
  },
  {
    key: 'irs-records',
    label: 'IRS name / tax record alignment',
    category: 'government',
    launchPriority: 12,
    triggers: ['all'],
    notes: 'IRS records follow your Social Security record, so confirm tax and withholding systems are using the same legal name after SSA lands.',
    suggestedTiming: 'Right after SSA confirmation and before payroll or filing mismatches pile up',
    evidenceNeeded: ['Updated Social Security record', 'Recent tax filing or IRS account details'],
    reminderDaysAfterPrimaryId: 1,
  },
  {
    key: 'irs-employer',
    label: 'Employer payroll / HR',
    category: 'employment',
    launchPriority: 10,
    triggers: ['employment'],
    notes: 'Update payroll and benefits after SSA so tax reporting lines up cleanly.',
    suggestedTiming: 'Within 1-3 business days after SSA confirmation',
    evidenceNeeded: ['Updated Social Security record', 'Updated photo ID when available', 'Payroll or benefits account details'],
    reminderDaysAfterPrimaryId: 2,
  },
  {
    key: 'state-tax-agency',
    label: 'State tax agency and withholding records',
    category: 'government',
    launchPriority: 14,
    triggers: ['all'],
    notes: 'State tax accounts and withholding records should match SSA, payroll, and DMV so refunds, withholding, and compliance mail do not split across names.',
    suggestedTiming: 'Right after SSA and payroll updates are moving, before the next pay cycle or filing deadline',
    evidenceNeeded: ['Updated Social Security record', 'Payroll or withholding account details', 'Updated photo ID when available'],
    reminderDaysAfterPrimaryId: 3,
  },
  {
    key: 'banks',
    label: 'Banks and credit cards',
    category: 'financial',
    launchPriority: 20,
    triggers: ['all'],
    notes: 'Usually easiest after your main photo ID reflects the new name.',
    suggestedTiming: 'Within the first week after DMV or passport reflects the new name',
    evidenceNeeded: ['Updated photo ID', 'Legal proof document', 'Debit / credit or account details'],
    reminderDaysAfterPrimaryId: 5,
  },
  {
    key: 'investments-loans',
    label: 'Investment, retirement, and loan accounts',
    category: 'financial',
    launchPriority: 22,
    triggers: ['all'],
    notes: 'Carry the same name through brokerages, retirement plans, servicers, and lending portals so statements and verification checks stop splitting.',
    suggestedTiming: 'Within the first week after DMV or passport reflects the new name',
    evidenceNeeded: ['Updated photo ID', 'Legal proof document', 'Account or loan numbers'],
    reminderDaysAfterPrimaryId: 6,
  },
  {
    key: 'student-loans-financial-aid',
    label: 'Student loans, servicers, and financial aid portals',
    category: 'financial',
    launchPriority: 24,
    triggers: ['all'],
    notes: 'Loan servicers and aid portals are notorious for stale identity data, so clean them up before autopay, verification, or school records fork.',
    suggestedTiming: 'Within the first 1-2 weeks after your primary photo ID is updated',
    evidenceNeeded: ['Updated photo ID', 'Legal proof document', 'Loan or aid account identifiers'],
    reminderDaysAfterPrimaryId: 7,
  },
  {
    key: 'mortgage-property-records',
    label: 'Mortgage, property title, and homeowner records',
    category: 'financial',
    launchPriority: 25,
    triggers: ['all'],
    notes: 'Mortgage servicers, property tax mail, title paperwork, and homeowner-facing records should all point at the same legal name before refinancing, escrow, or claims work appears.',
    suggestedTiming: 'During the first 2-3 weeks after primary ID and banking updates are stable',
    evidenceNeeded: ['Updated photo ID', 'Legal proof document', 'Mortgage or property account details'],
    reminderDaysAfterPrimaryId: 9,
  },
  {
    key: 'insurance',
    label: 'Health, dental, vision, auto, renters, and life insurance',
    category: 'insurance',
    launchPriority: 30,
    triggers: ['all'],
    notes: 'Update policyholder names so claims and cards stay consistent.',
    suggestedTiming: 'During the first 1-2 weeks after primary ID changes',
    evidenceNeeded: ['Updated photo ID', 'Policy numbers', 'Legal proof document'],
    reminderDaysAfterPrimaryId: 7,
  },
  {
    key: 'disability-insurance',
    label: 'Disability insurance and leave administrators',
    category: 'insurance',
    launchPriority: 31,
    triggers: ['employment'],
    notes: 'Short-term disability, leave vendors, and income-protection carriers should match payroll and benefits records.',
    suggestedTiming: 'At the same time as payroll and benefits updates',
    evidenceNeeded: ['Updated Social Security record', 'Updated photo ID when available', 'Policy or claim identifiers'],
    reminderDaysAfterPrimaryId: 4,
  },
  {
    key: 'retirement-benefits',
    label: 'Retirement plan, pension, and beneficiary records',
    category: 'employment',
    launchPriority: 18,
    triggers: ['employment'],
    notes: 'Benefits administrators, retirement plans, and beneficiary designations should not lag behind payroll once the legal name changes.',
    suggestedTiming: 'Alongside payroll and HR updates, before open enrollment or beneficiary changes',
    evidenceNeeded: ['Updated Social Security record', 'Benefits or retirement account details', 'Updated photo ID when available'],
    reminderDaysAfterPrimaryId: 4,
  },
  {
    key: 'medical-records',
    label: 'Medical providers / insurance cards',
    category: 'insurance',
    launchPriority: 32,
    triggers: ['all'],
    notes: 'Update provider rosters, patient portals, and member-card records once your primary ID is moving.',
    suggestedTiming: 'During the first 1-2 weeks after primary ID changes',
    evidenceNeeded: ['Updated photo ID', 'Insurance card or portal details', 'Legal proof document'],
    reminderDaysAfterPrimaryId: 8,
  },
  {
    key: 'workers-comp-leave',
    label: 'Workers comp, leave, and claims administrators',
    category: 'insurance',
    launchPriority: 33,
    triggers: ['employment'],
    notes: 'Claims systems, leave coordinators, and workers comp vendors often store identity separately from payroll, so update them before a claim or return-to-work event goes sideways.',
    suggestedTiming: 'At the same time as disability, HR, and insurance record updates',
    evidenceNeeded: ['Updated Social Security record', 'Claim or leave identifiers', 'Updated photo ID when available'],
    reminderDaysAfterPrimaryId: 5,
  },
  {
    key: 'utilities-housing',
    label: 'Utilities, lease, and landlord records',
    category: 'personal',
    launchPriority: 35,
    triggers: ['all'],
    notes: 'Useful once your primary ID is moving so leases, portals, and mailed statements stop drifting.',
    suggestedTiming: 'During the first 1-2 weeks after primary ID changes',
    evidenceNeeded: ['Updated photo ID when available', 'Utility or lease account details', 'Legal proof document'],
    reminderDaysAfterPrimaryId: 8,
  },
  {
    key: 'phone-digital-identity',
    label: 'Phone plan, email/domain, and primary digital identity',
    category: 'personal',
    launchPriority: 36,
    triggers: ['all'],
    notes: 'Clean up your phone account, email display names, domain registrations, and recovery channels before other services keep syncing the old name back in.',
    suggestedTiming: 'During the first 1-2 weeks after primary ID changes',
    evidenceNeeded: ['Updated photo ID when available', 'Carrier or registrar account details', 'Legal proof document'],
    reminderDaysAfterPrimaryId: 9,
  },
  {
    key: 'subscriptions-social',
    label: 'Subscriptions, social profiles, and lifestyle memberships',
    category: 'personal',
    launchPriority: 37,
    triggers: ['all'],
    notes: 'Update recurring services, creator profiles, and memberships after the legal-facing systems stop moving.',
    suggestedTiming: 'After banks, payroll, and insurance are stable',
    evidenceNeeded: ['Updated preferred display name', 'Service login access'],
    reminderDaysAfterPrimaryId: 12,
  },
  {
    key: 'school-alumni-records',
    label: 'School, alumni, and transcript records',
    category: 'personal',
    launchPriority: 38,
    triggers: ['all'],
    notes: 'If you use academic records for hiring, licensing, or background checks, update schools and alumni systems so verification requests stop bouncing between names.',
    suggestedTiming: 'After payroll, banking, and insurance are moving cleanly',
    evidenceNeeded: ['Updated photo ID', 'Student or alumni account details', 'Legal proof document'],
    reminderDaysAfterPrimaryId: 12,
  },
  {
    key: 'courtesy-social-sync',
    label: 'Courtesy / social identity sync',
    category: 'personal',
    launchPriority: 90,
    triggers: ['all'],
    notes: 'Best for display names, loyalty profiles, and non-legal-facing account labels once the core admin trail is underway.',
    suggestedTiming: 'After the major legal and institutional records are already in motion',
    evidenceNeeded: ['Updated preferred display name', 'Account login or loyalty profile access'],
    reminderDaysAfterPrimaryId: 14,
  },
  {
    key: 'voter-registration',
    label: 'California voter registration',
    category: 'government',
    launchPriority: 40,
    triggers: ['california_resident'],
    notes: 'California can be updated after your DMV record is settled.',
    suggestedTiming: 'After California DMV reflects the new name',
    evidenceNeeded: ['Updated California DMV record'],
    reminderDaysAfterPrimaryId: 10,
  },
  {
    key: 'county-recorder-property',
    label: 'County recorder, deed, and local property filings',
    category: 'government',
    launchPriority: 41,
    triggers: ['all'],
    notes: 'If your name appears on deeds or local recorder filings, update them deliberately so county property records and future transactions do not keep surfacing the old name.',
    suggestedTiming: 'After primary ID and mortgage/property records are aligned',
    evidenceNeeded: ['Updated photo ID', 'Recorded deed or parcel details', 'Legal proof document'],
    reminderDaysAfterPrimaryId: 11,
  },
  {
    key: 'tsa-precheck',
    label: 'TSA PreCheck, Global Entry, and airline profiles',
    category: 'personal',
    launchPriority: 50,
    triggers: ['passport'],
    notes: 'Do this after passport or Real ID updates so future travel bookings match.',
    suggestedTiming: 'Immediately after passport or Real ID details match travel bookings',
    evidenceNeeded: ['Updated passport or Real ID', 'Known traveler / loyalty account details'],
    reminderDaysAfterPrimaryId: 1,
  },
  {
    key: 'travel-hospitality',
    label: 'Hotel loyalty, car registration/title, and auto insurance follow-through',
    category: 'personal',
    launchPriority: 52,
    triggers: ['all'],
    notes: 'Finish the travel and mobility stack so reservations, registration, title, and vehicle coverage all match the same identity chain.',
    suggestedTiming: 'After DMV is updated, and after passport if future travel bookings are in play',
    evidenceNeeded: ['Updated DMV record', 'Updated auto policy or title details', 'Loyalty account details'],
    reminderDaysAfterPrimaryId: 11,
  },
  {
    key: 'dmv-registration-title',
    label: 'Vehicle registration and title records',
    category: 'personal',
    launchPriority: 53,
    triggers: ['all'],
    notes: 'Your vehicle registration and title should match the updated DMV identity record so insurance, registration renewals, and any sale or refinance paperwork stay clean.',
    suggestedTiming: 'Immediately after DMV reflects the new name',
    evidenceNeeded: ['Updated DMV record', 'Vehicle registration or title details', 'Auto policy details when relevant'],
    reminderDaysAfterPrimaryId: 6,
  },
  {
    key: 'frequent-flyer-hotel-rail',
    label: 'Frequent flyer, hotel, rail, and cruise loyalty accounts',
    category: 'personal',
    launchPriority: 54,
    triggers: ['passport'],
    notes: 'Travel loyalty systems and reservation profiles should match your passport and TSA identity before you trust them with future bookings.',
    suggestedTiming: 'Right after passport or traveler-profile updates are confirmed',
    evidenceNeeded: ['Updated passport or Real ID', 'Loyalty profile access', 'Upcoming booking details when relevant'],
    reminderDaysAfterPrimaryId: 3,
  },
  {
    key: 'professional-licenses',
    label: 'Professional licenses and certifications',
    category: 'personal',
    launchPriority: 60,
    triggers: ['employment'],
    notes: 'This matters for healthcare, legal, education, and other licensed work.',
    suggestedTiming: 'Within 1-2 weeks unless your employer or regulator needs it sooner',
    evidenceNeeded: ['Updated ID', 'License numbers', 'Legal proof document'],
    reminderDaysAfterPrimaryId: 10,
  },
];
