import { NAME_CHANGE_DMV_FORM_CONTRACT } from './dmvForm';
import { NAME_CHANGE_PASSPORT_RENEWAL_FORM_CONTRACT } from './passportForm';
import { NAME_CHANGE_SS5_FORM_CONTRACT } from './ss5Form';
import type { NameChangeExecutionTargetDefinition } from './types';

export const NAME_CHANGE_EXECUTION_TARGETS: Record<'ssa' | 'dmv' | 'passport', NameChangeExecutionTargetDefinition> = {
  ssa: {
    key: 'ssa',
    label: 'Social Security Administration',
    lane: 'federal',
    recommendedFormCode: NAME_CHANGE_SS5_FORM_CONTRACT.formCode,
    formBuilderKey: 'ss5',
    prerequisiteRules: [],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_last_name',
      'legal.marriage_date',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for SSA',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for SSA.',
      },
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for SSA.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for SS-5',
        kind: 'field_presence',
        targetField: 'applicant.current_first_name',
        missingReason: 'Current legal name fields are still incomplete for SS-5 preparation.',
        satisfiedReason: 'Current legal first and last name are available for SS-5 preparation.',
      },
      {
        key: 'target-surname',
        label: 'Target surname available for SS-5',
        kind: 'field_presence',
        targetField: 'applicant.target_last_name',
        missingReason: 'Target last name is still missing for SS-5 preparation.',
        satisfiedReason: 'Target last name is available for SS-5 preparation.',
      },
      {
        key: 'ssa-support-doc',
        label: 'SSA supporting document intake',
        kind: 'document_support',
        documentKinds: ['current_drivers_license', 'current_passport', 'social_security_card'],
        missingReason: 'No SSA-supporting identity document is represented in intake yet.',
        satisfiedReason: 'An SSA-supporting identity document exists in intake.',
      },
    ],
  },
  dmv: {
    key: 'dmv',
    label: 'California DMV',
    lane: 'state',
    recommendedFormCode: NAME_CHANGE_DMV_FORM_CONTRACT.formCode,
    formBuilderKey: 'dmv',
    prerequisiteRules: [
      {
        key: 'federal-ssa-progress',
        label: 'SSA execution completed before DMV prep',
        required: true,
        requiredStepId: 'federal-ssa',
        requiredStatuses: ['complete'],
        missingReason: 'SSA execution is not complete yet, so DMV sequencing is still blocked on the federal-first path.',
        attentionReason: 'SSA execution is in progress, so DMV should stay queued behind the federal-first path.',
        satisfiedReason: 'SSA execution is marked complete, so DMV sequencing can proceed on the federal-first path.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_last_name',
      'applicant.county',
      'legal.marriage_date',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for DMV',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for DMV.',
      },
      {
        key: 'county-context',
        label: 'California county context available',
        kind: 'requirement',
        requirementKey: 'county-context',
        missingReason: 'County context requirement not evaluated.',
        satisfiedReason: 'County context is available for DMV preparation.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for DMV prep',
        kind: 'field_presence',
        targetField: 'applicant.current_first_name',
        missingReason: 'Current legal name fields are still incomplete for DMV preparation.',
        satisfiedReason: 'Current legal first and last name are available for DMV preparation.',
      },
      {
        key: 'target-surname-county',
        label: 'Target surname + county available',
        kind: 'field_presence',
        targetField: 'applicant.target_last_name',
        missingReason: 'Target surname and/or county are still missing for DMV preparation.',
        satisfiedReason: 'Target surname and county are available for DMV preparation.',
      },
      {
        key: 'dmv-support-doc',
        label: 'California DMV supporting intake',
        kind: 'document_support',
        documentKinds: ['current_drivers_license', 'proof_of_address'],
        missingReason: 'No California-facing ID/address support document is represented in intake yet.',
        satisfiedReason: 'A current California-facing ID or address document exists in intake.',
      },
    ],
  },
  passport: {
    key: 'passport',
    label: 'U.S. Passport',
    lane: 'federal',
    recommendedFormCode: NAME_CHANGE_PASSPORT_RENEWAL_FORM_CONTRACT.formCode,
    formBuilderKey: 'passport',
    prerequisiteRules: [
      {
        key: 'federal-ssa-progress',
        label: 'SSA underway before passport packet prep',
        required: true,
        requiredStepId: 'federal-ssa',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'Passport prep should wait until SSA is underway so the federal identity chain stays coherent.',
        attentionReason: 'SSA is moving, so passport prep can follow without waiting for California DMV.',
        satisfiedReason: 'SSA has already moved enough that passport prep can proceed.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_last_name',
      'legal.marriage_date',
      'identity.passport_issue_date',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for passport packet',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for passport prep.',
      },
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for passport prep.',
      },
      {
        key: 'passport-timing-risk',
        label: 'Passport timing risk reviewed',
        kind: 'requirement',
        requirementKey: 'passport-timing-risk',
        missingReason: 'Passport timing review has not been evaluated yet.',
        satisfiedReason: 'Passport timing risk has been reviewed.',
      },
      {
        key: 'target-surname',
        label: 'Target surname available for passport packet',
        kind: 'field_presence',
        targetField: 'applicant.target_last_name',
        missingReason: 'Target last name is still missing for passport prep.',
        satisfiedReason: 'Target last name is available for passport prep.',
      },
      {
        key: 'passport-support-doc',
        label: 'Passport-supporting document intake',
        kind: 'document_support',
        documentKinds: ['current_passport', 'birth_certificate', 'current_drivers_license'],
        missingReason: 'No passport-supporting identity/citizenship document is represented in intake yet.',
        satisfiedReason: 'A passport-supporting identity/citizenship document exists in intake.',
      },
    ],
  },
};
