import { NAME_CHANGE_BANK_PACKET_CONTRACT } from './bankPacket';
import { NAME_CHANGE_DMV_FORM_CONTRACT } from './dmvForm';
import { NAME_CHANGE_EMPLOYER_PACKET_CONTRACT } from './employerPacket';
import { NAME_CHANGE_INSURANCE_PACKET_CONTRACT } from './insurancePacket';
import { NAME_CHANGE_PASSPORT_RENEWAL_FORM_CONTRACT } from './passportForm';
import { NAME_CHANGE_SS5_FORM_CONTRACT } from './ss5Form';
import type { NameChangeExecutionTargetDefinition } from './types';

export const NAME_CHANGE_EXECUTION_TARGETS: Record<'ssa' | 'dmv' | 'passport' | 'employer' | 'banks' | 'insurance', NameChangeExecutionTargetDefinition> = {
  ssa: {
    key: 'ssa',
    label: 'Social Security Administration',
    lane: 'federal',
    recommendedFormCode: NAME_CHANGE_SS5_FORM_CONTRACT.formCode,
    formBuilderKey: 'ss5',
    prerequisiteRules: [],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_last_name',
      'legal.marriage_date',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for SSA',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for SSA.',
      },
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for SSA.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for SS-5',
        kind: 'field_presence',
        targetField: 'applicant.current_first_name',
        missingReason: 'Current legal name fields are still incomplete for SS-5 preparation.',
        satisfiedReason: 'Current legal first and last name are available for SS-5 preparation.',
      },
      {
        key: 'target-surname',
        label: 'Target surname available for SS-5',
        kind: 'field_presence',
        targetField: 'applicant.target_last_name',
        missingReason: 'Target last name is still missing for SS-5 preparation.',
        satisfiedReason: 'Target last name is available for SS-5 preparation.',
      },
      {
        key: 'ssa-support-doc',
        label: 'SSA supporting document intake',
        kind: 'document_support',
        documentKinds: ['current_drivers_license', 'current_passport', 'social_security_card'],
        missingReason: 'No SSA-supporting identity document is represented in intake yet.',
        satisfiedReason: 'An SSA-supporting identity document exists in intake.',
      },
    ],
  },
  dmv: {
    key: 'dmv',
    label: 'California DMV',
    lane: 'state',
    recommendedFormCode: NAME_CHANGE_DMV_FORM_CONTRACT.formCode,
    formBuilderKey: 'dmv',
    prerequisiteRules: [
      {
        key: 'federal-ssa-progress',
        label: 'SSA execution completed before DMV prep',
        required: true,
        requiredStepId: 'federal-ssa',
        requiredStatuses: ['complete'],
        missingReason: 'SSA execution is not complete yet, so DMV sequencing is still blocked on the federal-first path.',
        attentionReason: 'SSA execution is in progress, so DMV should stay queued behind the federal-first path.',
        satisfiedReason: 'SSA execution is marked complete, so DMV sequencing can proceed on the federal-first path.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_last_name',
      'applicant.county',
      'legal.marriage_date',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for DMV',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for DMV.',
      },
      {
        key: 'county-context',
        label: 'California county context available',
        kind: 'requirement',
        requirementKey: 'county-context',
        missingReason: 'County context requirement not evaluated.',
        satisfiedReason: 'County context is available for DMV preparation.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for DMV prep',
        kind: 'field_presence',
        targetField: 'applicant.current_first_name',
        missingReason: 'Current legal name fields are still incomplete for DMV preparation.',
        satisfiedReason: 'Current legal first and last name are available for DMV preparation.',
      },
      {
        key: 'target-surname-county',
        label: 'Target surname + county available',
        kind: 'field_presence',
        targetField: 'applicant.target_last_name',
        missingReason: 'Target surname and/or county are still missing for DMV preparation.',
        satisfiedReason: 'Target surname and county are available for DMV preparation.',
      },
      {
        key: 'dmv-support-doc',
        label: 'California DMV supporting intake',
        kind: 'document_support',
        documentKinds: ['current_drivers_license', 'proof_of_address'],
        missingReason: 'No California-facing ID/address support document is represented in intake yet.',
        satisfiedReason: 'A current California-facing ID or address document exists in intake.',
      },
    ],
  },
  passport: {
    key: 'passport',
    label: 'U.S. Passport',
    lane: 'federal',
    recommendedFormCode: NAME_CHANGE_PASSPORT_RENEWAL_FORM_CONTRACT.formCode,
    formBuilderKey: 'passport',
    prerequisiteRules: [
      {
        key: 'federal-ssa-progress',
        label: 'SSA underway before passport packet prep',
        required: true,
        requiredStepId: 'federal-ssa',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'Passport prep should wait until SSA is underway so the federal identity chain stays coherent.',
        attentionReason: 'SSA is moving, so passport prep can follow without waiting for California DMV.',
        satisfiedReason: 'SSA has already moved enough that passport prep can proceed.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_last_name',
      'legal.marriage_date',
      'identity.passport_issue_date',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for passport packet',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for passport prep.',
      },
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for passport prep.',
      },
      {
        key: 'passport-timing-risk',
        label: 'Passport timing risk reviewed',
        kind: 'requirement',
        requirementKey: 'passport-timing-risk',
        missingReason: 'Passport timing review has not been evaluated yet.',
        satisfiedReason: 'Passport timing risk has been reviewed.',
      },
      {
        key: 'target-surname',
        label: 'Target surname available for passport packet',
        kind: 'field_presence',
        targetField: 'applicant.target_last_name',
        missingReason: 'Target last name is still missing for passport prep.',
        satisfiedReason: 'Target last name is available for passport prep.',
      },
      {
        key: 'passport-support-doc',
        label: 'Passport-supporting document intake',
        kind: 'document_support',
        documentKinds: ['current_passport', 'birth_certificate', 'current_drivers_license'],
        missingReason: 'No passport-supporting identity/citizenship document is represented in intake yet.',
        satisfiedReason: 'A passport-supporting identity/citizenship document exists in intake.',
      },
    ],
  },
  employer: {
    key: 'employer',
    label: 'Employer payroll / HR',
    lane: 'state',
    recommendedFormCode: NAME_CHANGE_EMPLOYER_PACKET_CONTRACT.formCode,
    formBuilderKey: 'employer',
    prerequisiteRules: [
      {
        key: 'federal-ssa-complete',
        label: 'SSA completed before payroll / HR changes',
        required: true,
        requiredStepId: 'federal-ssa',
        requiredStatuses: ['complete'],
        missingReason: 'Employer / payroll updates should wait until SSA is complete so tax and payroll records do not drift.',
        attentionReason: 'SSA is in motion, but payroll / HR should still wait for completion.',
        satisfiedReason: 'SSA is complete, so employer / payroll updates can proceed cleanly.',
      },
      {
        key: 'primary-photo-id-progress',
        label: 'Primary photo ID underway before HR packet rollout',
        required: false,
        requiredStepId: 'state-dmv',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'Primary photo ID has not started moving yet, so some employers may still need interim proof handling.',
        attentionReason: 'Primary photo ID is moving, which helps HR packet follow-through.',
        satisfiedReason: 'Primary photo ID is already moving or complete for HR packet follow-through.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_last_name',
      'applicant.target_last_name',
      'legal.marriage_date',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for employer packet',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for employer packet prep.',
      },
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for employer packet prep.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for HR packet',
        kind: 'field_presence',
        targetField: 'applicant.current_first_name',
        missingReason: 'Current legal name fields are still incomplete for employer packet prep.',
        satisfiedReason: 'Current legal first and last name are available for employer packet prep.',
      },
      {
        key: 'target-surname',
        label: 'Target surname available for HR packet',
        kind: 'field_presence',
        targetField: 'applicant.target_last_name',
        missingReason: 'Target last name is still missing for employer packet prep.',
        satisfiedReason: 'Target last name is available for employer packet prep.',
      },
      {
        key: 'hr-support-doc',
        label: 'Employer-supporting document intake',
        kind: 'document_support',
        documentKinds: ['social_security_card', 'current_drivers_license', 'current_passport'],
        missingReason: 'No employer-supporting identity document is represented in intake yet.',
        satisfiedReason: 'An employer-supporting identity document exists in intake.',
      },
    ],
  },
  banks: {
    key: 'banks',
    label: 'Banks and credit cards',
    lane: 'state',
    recommendedFormCode: NAME_CHANGE_BANK_PACKET_CONTRACT.formCode,
    formBuilderKey: 'banks',
    prerequisiteRules: [
      {
        key: 'primary-photo-id-progress',
        label: 'Primary photo ID underway before bank rollout',
        required: true,
        requiredStepId: 'state-dmv',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'Banks are usually easiest once your primary photo ID is moving or already updated.',
        attentionReason: 'Primary photo ID is moving, which supports bank update follow-through.',
        satisfiedReason: 'Primary photo ID is already moving or complete for bank update follow-through.',
      },
      {
        key: 'passport-or-dmv-progress',
        label: 'At least one travel / ID-facing record is moving',
        required: false,
        requiredStepId: 'federal-passport',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'No passport progress is recorded yet, so bank updates may rely only on DMV proof.',
        attentionReason: 'Passport progress exists, which helps cross-check travel-facing identity records.',
        satisfiedReason: 'Passport progress exists for cross-checking travel-facing identity records.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_last_name',
      'applicant.target_last_name',
      'legal.marriage_date',
      'applicant.county',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for bank packet',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for bank packet prep.',
      },
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for bank packet prep.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for bank packet',
        kind: 'field_presence',
        targetField: 'applicant.current_first_name',
        missingReason: 'Current legal name fields are still incomplete for bank packet prep.',
        satisfiedReason: 'Current legal first and last name are available for bank packet prep.',
      },
      {
        key: 'target-surname',
        label: 'Target surname available for bank packet',
        kind: 'field_presence',
        targetField: 'applicant.target_last_name',
        missingReason: 'Target last name is still missing for bank packet prep.',
        satisfiedReason: 'Target last name is available for bank packet prep.',
      },
      {
        key: 'bank-support-doc',
        label: 'Bank-supporting document intake',
        kind: 'document_support',
        documentKinds: ['current_drivers_license', 'current_passport', 'proof_of_address'],
        missingReason: 'No bank-supporting ID/address document is represented in intake yet.',
        satisfiedReason: 'A bank-supporting ID/address document exists in intake.',
      },
    ],
  },
  insurance: {
    key: 'insurance',
    label: 'Health, auto, renters, and life insurance',
    lane: 'state',
    recommendedFormCode: NAME_CHANGE_INSURANCE_PACKET_CONTRACT.formCode,
    formBuilderKey: 'insurance',
    prerequisiteRules: [
      {
        key: 'primary-photo-id-progress',
        label: 'Primary photo ID underway before insurance rollout',
        required: true,
        requiredStepId: 'state-dmv',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'Insurance updates usually go smoother once your primary photo ID is moving or already updated.',
        attentionReason: 'Primary photo ID is moving, which supports insurance update follow-through.',
        satisfiedReason: 'Primary photo ID is already moving or complete for insurance update follow-through.',
      },
      {
        key: 'employer-or-bank-progress',
        label: 'Another institutional lane is already moving',
        required: false,
        requiredStepId: 'institution-banks',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'No other institutional rollout step is moving yet, so insurance may be the first account-update lane to start.',
        attentionReason: 'Another institutional lane is already moving, which helps normalize packet handling.',
        satisfiedReason: 'Another institutional lane is already moving for packet normalization.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_last_name',
      'applicant.target_last_name',
      'legal.marriage_date',
      'applicant.county',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for insurance packet',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for insurance packet prep.',
      },
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for insurance packet prep.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for insurance packet',
        kind: 'field_presence',
        targetField: 'applicant.current_first_name',
        missingReason: 'Current legal name fields are still incomplete for insurance packet prep.',
        satisfiedReason: 'Current legal first and last name are available for insurance packet prep.',
      },
      {
        key: 'target-surname',
        label: 'Target surname available for insurance packet',
        kind: 'field_presence',
        targetField: 'applicant.target_last_name',
        missingReason: 'Target last name is still missing for insurance packet prep.',
        satisfiedReason: 'Target last name is available for insurance packet prep.',
      },
      {
        key: 'insurance-support-doc',
        label: 'Insurance-supporting document intake',
        kind: 'document_support',
        documentKinds: ['current_drivers_license', 'current_passport', 'proof_of_address'],
        missingReason: 'No insurance-supporting ID/address document is represented in intake yet.',
        satisfiedReason: 'An insurance-supporting ID/address document exists in intake.',
      },
    ],
  },
};
