import { NAME_CHANGE_BANK_PACKET_CONTRACT } from './bankPacket';
import { NAME_CHANGE_COURT_ORDER_PACKET_CONTRACT } from './courtOrderPacket';
import { NAME_CHANGE_COURTESY_PACKET_CONTRACT } from './courtesyPacket';
import { NAME_CHANGE_DMV_FORM_CONTRACT } from './dmvForm';
import { NAME_CHANGE_EMPLOYER_PACKET_CONTRACT } from './employerPacket';
import { NAME_CHANGE_INSURANCE_PACKET_CONTRACT } from './insurancePacket';
import { NAME_CHANGE_LICENSE_PACKET_CONTRACT } from './licensePacket';
import { NAME_CHANGE_MEDICAL_PACKET_CONTRACT } from './medicalPacket';
import { NAME_CHANGE_PASSPORT_RENEWAL_FORM_CONTRACT } from './passportForm';
import { NAME_CHANGE_SS5_FORM_CONTRACT } from './ss5Form';
import { NAME_CHANGE_TAX_PACKET_CONTRACT } from './taxPacket';
import { NAME_CHANGE_TSA_PACKET_CONTRACT } from './tsaPacket';
import { NAME_CHANGE_UTILITIES_PACKET_CONTRACT } from './utilitiesPacket';
import { NAME_CHANGE_VOTER_PACKET_CONTRACT } from './voterPacket';
import type { NameChangeExecutionTargetDefinition } from './types';

function buildSharedIdentityChecklist(targetNoun: string, supportKey: string, supportLabel: string, supportDocumentKinds: NameChangeExecutionTargetDefinition['checklistSpecs'][number]['documentKinds']): NameChangeExecutionTargetDefinition['checklistSpecs'] {
  return [
    {
      key: 'identity-document-coverage',
      label: 'Identity document coverage',
      kind: 'requirement',
      requirementKey: 'identity-document-coverage',
      missingReason: 'Identity coverage requirement not evaluated.',
      satisfiedReason: `Identity document coverage is ready for ${targetNoun}.`,
    },
    {
      key: 'canonical-extraction-alignment',
      label: 'Canonical vs extracted values aligned',
      kind: 'requirement',
      nextActionCategory: 'document',
      blocksReady: true,
      requirementKey: 'canonical-extraction-alignment',
      missingReason: 'Canonical/extracted alignment has not been evaluated yet.',
      attentionReason: `Structured case truth and extracted document values still disagree for ${targetNoun}.`,
      satisfiedReason: `Structured case truth and extracted document values are aligned for ${targetNoun}.`,
    },
    {
      key: 'current-legal-name',
      label: `Current legal name available for ${targetNoun}`,
      kind: 'field_presence',
      targetFields: ['applicant.current_first_name', 'applicant.current_last_name'],
      conditionalTargetFields: ['applicant.current_middle_name'],
      missingReason: `Current legal name fields are still incomplete for ${targetNoun}.`,
      attentionReason: `Current legal name is populated for ${targetNoun}, but at least one field still needs stronger document support.`,
      satisfiedReason: `Current legal name is available for ${targetNoun}.`,
    },
    {
      key: 'target-legal-name',
      label: `Target legal name available for ${targetNoun}`,
      kind: 'field_presence',
      targetFields: ['applicant.target_first_name', 'applicant.target_last_name'],
      conditionalTargetFields: ['applicant.target_middle_name'],
      missingReason: `Target legal name fields are still incomplete for ${targetNoun}.`,
      attentionReason: `Target legal name is populated for ${targetNoun}, but at least one field still needs stronger document support.`,
      satisfiedReason: `Target legal name is available for ${targetNoun}.`,
    },
    {
      key: supportKey,
      label: supportLabel,
      kind: 'document_support',
      documentKinds: supportDocumentKinds,
      missingReason: `No supporting document is represented in intake yet for ${targetNoun}.`,
      satisfiedReason: `A supporting document exists in intake for ${targetNoun}.`,
    },
  ];
}

function buildPhotoIdInstitutionTarget(config: {
  key: Extract<NameChangeExecutionTargetDefinition['key'], 'banks' | 'insurance' | 'medical' | 'utilities'>;
  label: string;
  recommendedFormCode: string;
  formBuilderKey: Extract<NameChangeExecutionTargetDefinition['formBuilderKey'], 'banks' | 'insurance' | 'medical' | 'utilities'>;
  supportKey: string;
  supportLabel: string;
  supportDocumentKinds: NameChangeExecutionTargetDefinition['checklistSpecs'][number]['documentKinds'];
  primaryRule: NameChangeExecutionTargetDefinition['prerequisiteRules'][number];
  secondaryRule: NameChangeExecutionTargetDefinition['prerequisiteRules'][number];
}): NameChangeExecutionTargetDefinition {
  return {
    key: config.key,
    label: config.label,
    lane: 'state',
    recommendedFormCode: config.recommendedFormCode,
    formBuilderKey: config.formBuilderKey,
    sequenceProfile: config.key,
    prerequisiteRules: [
      config.primaryRule,
      config.secondaryRule,
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_first_name',
      'applicant.target_middle_name',
      'applicant.target_last_name',
      'legal.marriage_date',
      'applicant.county',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: `Legal proof ready for ${config.label.toLowerCase()} packet`,
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: `Legal proof document is ready for ${config.label.toLowerCase()} prep.`,
      },
      ...buildSharedIdentityChecklist(`${config.label.toLowerCase()} prep`, config.supportKey, config.supportLabel, config.supportDocumentKinds),
    ],
  };
}

export const NAME_CHANGE_EXECUTION_TARGETS: Record<'courtOrder' | 'ssa' | 'dmv' | 'passport' | 'employer' | 'taxes' | 'banks' | 'insurance' | 'medical' | 'utilities' | 'courtesy' | 'voter' | 'tsa' | 'licenses', NameChangeExecutionTargetDefinition> = {
  courtOrder: {
    key: 'courtOrder',
    label: 'Court-order path review',
    lane: 'state',
    recommendedFormCode: NAME_CHANGE_COURT_ORDER_PACKET_CONTRACT.formCode,
    formBuilderKey: 'courtOrder',
    sequenceProfile: 'courtOrder',
    prerequisiteRules: [],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_first_name',
      'applicant.target_middle_name',
      'applicant.target_last_name',
      'applicant.county',
      'legal.court_order_case_number',
      'legal.court_order_date',
    ],
    checklistSpecs: [
      {
        key: 'launch-state-alignment',
        label: 'California launch-state alignment',
        kind: 'requirement',
        requirementKey: 'launch-state-alignment',
        missingReason: 'California launch-state alignment has not been evaluated yet.',
        satisfiedReason: 'California launch-state alignment is ready for this modeled court-order review slice.',
      },
      {
        key: 'court-order-path-readiness',
        label: 'Court-order path readiness',
        kind: 'requirement',
        nextActionCategory: 'review',
        requirementKey: 'court-order-path-readiness',
        missingReason: 'Court-order path readiness has not been evaluated yet.',
        satisfiedReason: 'Court-order path readiness is clear for this modeled review slice.',
      },
      {
        key: 'court-order-jurisdiction-context',
        label: 'Court-order jurisdiction context is available',
        kind: 'requirement',
        requirementKey: 'court-order-jurisdiction-context',
        missingReason: 'Court-order jurisdiction context has not been evaluated yet.',
        satisfiedReason: 'Court-order jurisdiction context is available for this modeled review slice.',
      },
      {
        key: 'court-order-reference-extraction',
        label: 'Court-order target legal name and case reference extraction are available',
        kind: 'requirement',
        requirementKey: 'court-order-reference-extraction',
        missingReason: 'Court-order target legal name and case reference extraction have not been evaluated yet.',
        satisfiedReason: 'Court-order target legal name and case reference extraction are available for this modeled review slice.',
      },
      {
        key: 'legal-proof-document',
        label: 'Court-order proof ready',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Court-order proof requirement has not been evaluated yet.',
        satisfiedReason: 'Court-order proof is ready for this modeled review slice.',
      },
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement has not been evaluated yet.',
        satisfiedReason: 'Identity document coverage is ready for this modeled review slice.',
      },
      {
        key: 'canonical-extraction-alignment',
        label: 'Canonical vs extracted values aligned',
        kind: 'requirement',
        nextActionCategory: 'document',
        blocksReady: true,
        requirementKey: 'canonical-extraction-alignment',
        missingReason: 'Canonical/extracted alignment has not been evaluated yet.',
        attentionReason: 'Structured case truth and extracted document values still disagree for this modeled review slice.',
        satisfiedReason: 'Structured case truth and extracted document values are aligned for this modeled review slice.',
      },
      {
        key: 'target-legal-name',
        label: 'Target legal name available for court-order path',
        kind: 'field_presence',
        targetFields: ['applicant.target_first_name', 'applicant.target_last_name'],
        conditionalTargetFields: ['applicant.target_middle_name'],
        missingReason: 'Target legal name is still incomplete for the court-order path.',
        attentionReason: 'Target legal name is populated for the court-order path, but at least one field still needs stronger document support.',
        satisfiedReason: 'Target legal name is available for the court-order path.',
      },
    ],
  },
  ssa: {
    key: 'ssa',
    label: 'Social Security Administration',
    lane: 'federal',
    recommendedFormCode: NAME_CHANGE_SS5_FORM_CONTRACT.formCode,
    formBuilderKey: 'ss5',
    sequenceProfile: 'ssa',
    prerequisiteRules: [],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_first_name',
      'applicant.target_middle_name',
      'applicant.target_last_name',
      'legal.marriage_date',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for SSA',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for SSA.',
      },
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for SSA.',
      },
      {
        key: 'canonical-extraction-alignment',
        label: 'Canonical vs extracted values aligned',
        kind: 'requirement',
        nextActionCategory: 'document',
        blocksReady: true,
        requirementKey: 'canonical-extraction-alignment',
        missingReason: 'Canonical/extracted alignment has not been evaluated yet.',
        attentionReason: 'Structured case truth and extracted document values still disagree for SSA prep.',
        satisfiedReason: 'Structured case truth and extracted document values are aligned for SSA prep.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for SS-5',
        kind: 'field_presence',
        targetFields: ['applicant.current_first_name', 'applicant.current_last_name'],
        conditionalTargetFields: ['applicant.current_middle_name'],
        missingReason: 'Current legal name fields are still incomplete for SS-5 preparation.',
        satisfiedReason: 'Current legal name is available for SS-5 preparation.',
      },
      {
        key: 'target-legal-name',
        label: 'Target legal name available for SS-5',
        kind: 'field_presence',
        targetFields: ['applicant.target_first_name', 'applicant.target_last_name'],
        conditionalTargetFields: ['applicant.target_middle_name'],
        missingReason: 'Target legal name fields are still incomplete for SS-5 preparation.',
        satisfiedReason: 'Target legal name is available for SS-5 preparation.',
      },
      {
        key: 'ssa-support-doc',
        label: 'SSA supporting document intake',
        kind: 'document_support',
        documentKinds: ['current_drivers_license', 'current_passport', 'social_security_card'],
        missingReason: 'No SSA-supporting identity document is represented in intake yet.',
        satisfiedReason: 'An SSA-supporting identity document exists in intake.',
      },
    ],
  },
  dmv: {
    key: 'dmv',
    label: 'California DMV',
    lane: 'state',
    recommendedFormCode: NAME_CHANGE_DMV_FORM_CONTRACT.formCode,
    formBuilderKey: 'dmv',
    sequenceProfile: 'dmv',
    prerequisiteRules: [
      {
        key: 'federal-ssa-progress',
        label: 'SSA execution completed before DMV prep',
        required: true,
        requiredStepId: 'federal-ssa',
        requiredStatuses: ['complete'],
        missingReason: 'SSA execution is not complete yet, so DMV sequencing is still blocked on the federal-first path.',
        attentionReason: 'SSA execution is in progress, so DMV should stay queued behind the federal-first path.',
        satisfiedReason: 'SSA execution is marked complete, so DMV sequencing can proceed on the federal-first path.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_first_name',
      'applicant.target_middle_name',
      'applicant.target_last_name',
      'applicant.county',
      'legal.marriage_date',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for DMV',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for DMV.',
      },
      {
        key: 'county-context',
        label: 'California county context available',
        kind: 'requirement',
        requirementKey: 'county-context',
        missingReason: 'County context requirement not evaluated.',
        satisfiedReason: 'County context is available for DMV preparation.',
      },
      {
        key: 'canonical-extraction-alignment',
        label: 'Canonical vs extracted values aligned',
        kind: 'requirement',
        nextActionCategory: 'document',
        blocksReady: true,
        requirementKey: 'canonical-extraction-alignment',
        missingReason: 'Canonical/extracted alignment has not been evaluated yet.',
        attentionReason: 'Structured case truth and extracted document values still disagree for DMV prep.',
        satisfiedReason: 'Structured case truth and extracted document values are aligned for DMV prep.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for DMV prep',
        kind: 'field_presence',
        targetFields: ['applicant.current_first_name', 'applicant.current_last_name'],
        conditionalTargetFields: ['applicant.current_middle_name'],
        missingReason: 'Current legal name fields are still incomplete for DMV preparation.',
        satisfiedReason: 'Current legal name is available for DMV preparation.',
      },
      {
        key: 'target-legal-name-county',
        label: 'Target legal name + county available',
        kind: 'field_presence',
        targetFields: ['applicant.target_first_name', 'applicant.target_last_name', 'applicant.county'],
        conditionalTargetFields: ['applicant.target_middle_name'],
        missingReason: 'Target legal name fields and/or county are still missing for DMV preparation.',
        satisfiedReason: 'Target legal name plus county is available for DMV preparation.',
      },
      {
        key: 'dmv-support-doc',
        label: 'California DMV supporting intake',
        kind: 'document_support',
        documentKinds: ['current_drivers_license', 'proof_of_address'],
        missingReason: 'No California-facing ID/address support document is represented in intake yet.',
        satisfiedReason: 'A current California-facing ID or address document exists in intake.',
      },
    ],
  },
  passport: {
    key: 'passport',
    label: 'U.S. Passport',
    lane: 'federal',
    recommendedFormCode: NAME_CHANGE_PASSPORT_RENEWAL_FORM_CONTRACT.formCode,
    formBuilderKey: 'passport',
    sequenceProfile: 'passport',
    prerequisiteRules: [
      {
        key: 'federal-ssa-progress',
        label: 'SSA underway before passport packet prep',
        required: true,
        requiredStepId: 'federal-ssa',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'Passport prep should wait until SSA is underway so the federal identity chain stays coherent.',
        attentionReason: 'SSA is moving, so passport prep can follow without waiting for California DMV.',
        satisfiedReason: 'SSA has already moved enough that passport prep can proceed.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_first_name',
      'applicant.target_middle_name',
      'applicant.target_last_name',
      'legal.marriage_date',
      'identity.passport_issue_date',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for passport packet',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for passport prep.',
      },
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for passport prep.',
      },
      {
        key: 'marriage-jurisdiction-alignment',
        label: 'Marriage jurisdiction alignment',
        kind: 'requirement',
        requirementKey: 'marriage-jurisdiction-alignment',
        missingReason: 'Marriage jurisdiction alignment has not been evaluated yet.',
        attentionReason: 'Marriage happened outside California, so passport follow-through should keep the out-of-state certificate path in view.',
        satisfiedReason: 'Marriage jurisdiction is aligned for the modeled passport prep flow.',
      },
      {
        key: 'out-of-state-marriage-certificate-grounding',
        label: 'Out-of-state marriage certificate grounding',
        kind: 'requirement',
        requirementKey: 'out-of-state-marriage-certificate-grounding',
        missingReason: 'Out-of-state marriage certificate grounding has not been evaluated yet.',
        attentionReason: 'Passport follow-through still needs grounded certificate reference fields from the out-of-state marriage certificate.',
        satisfiedReason: 'Out-of-state marriage certificate grounding is ready for passport prep.',
      },
      {
        key: 'passport-timing-risk',
        label: 'Passport timing risk reviewed',
        kind: 'requirement',
        requirementKey: 'passport-timing-risk',
        missingReason: 'Passport timing review has not been evaluated yet.',
        satisfiedReason: 'Passport timing risk has been reviewed.',
      },
      {
        key: 'expedited-travel-sequencing',
        label: 'Expedited travel sequencing ready',
        kind: 'requirement',
        requirementKey: 'expedited-travel-sequencing',
        missingReason: 'Expedited travel sequencing has not been evaluated yet.',
        satisfiedReason: 'Expedited travel sequencing is ready for passport prep.',
      },
      {
        key: 'passport-eligibility-path',
        label: 'Passport eligibility path is clear',
        kind: 'requirement',
        requirementKey: 'passport-eligibility-path',
        missingReason: 'Passport eligibility path has not been evaluated yet.',
        satisfiedReason: 'Passport eligibility path is clear for this passport prep flow.',
      },
      {
        key: 'canonical-extraction-alignment',
        label: 'Canonical vs extracted values aligned',
        kind: 'requirement',
        nextActionCategory: 'document',
        blocksReady: true,
        requirementKey: 'canonical-extraction-alignment',
        missingReason: 'Canonical/extracted alignment has not been evaluated yet.',
        attentionReason: 'Structured case truth and extracted document values still disagree for passport prep.',
        satisfiedReason: 'Structured case truth and extracted document values are aligned for passport prep.',
      },
      {
        key: 'target-legal-name',
        label: 'Target legal name available for passport packet',
        kind: 'field_presence',
        targetFields: ['applicant.target_first_name', 'applicant.target_last_name'],
        conditionalTargetFields: ['applicant.target_middle_name'],
        missingReason: 'Target legal name fields are still missing for passport prep.',
        satisfiedReason: 'Target legal name is available for passport prep.',
      },
      {
        key: 'passport-support-doc',
        label: 'Passport-supporting document intake',
        kind: 'document_support',
        documentKinds: ['current_passport', 'birth_certificate', 'current_drivers_license'],
        missingReason: 'No passport-supporting identity/citizenship document is represented in intake yet.',
        satisfiedReason: 'A passport-supporting identity/citizenship document exists in intake.',
      },
    ],
  },
  employer: {
    key: 'employer',
    label: 'Employer payroll / HR',
    lane: 'state',
    recommendedFormCode: NAME_CHANGE_EMPLOYER_PACKET_CONTRACT.formCode,
    formBuilderKey: 'employer',
    sequenceProfile: 'employer',
    prerequisiteRules: [
      {
        key: 'federal-ssa-complete',
        label: 'SSA completed before payroll / HR changes',
        required: true,
        requiredStepId: 'federal-ssa',
        requiredStatuses: ['complete'],
        missingReason: 'Employer / payroll updates should wait until SSA is complete so tax and payroll records do not drift.',
        attentionReason: 'SSA is in motion, but payroll / HR should still wait for completion.',
        satisfiedReason: 'SSA is complete, so employer / payroll updates can proceed cleanly.',
      },
      {
        key: 'primary-photo-id-progress',
        label: 'Primary photo ID underway before HR packet rollout',
        required: false,
        requiredStepId: 'state-dmv',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'Primary photo ID has not started moving yet, so some employers may still need interim proof handling.',
        attentionReason: 'Primary photo ID is moving, which helps HR packet follow-through.',
        satisfiedReason: 'Primary photo ID is already moving or complete for HR packet follow-through.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_first_name',
      'applicant.target_middle_name',
      'applicant.target_last_name',
      'legal.marriage_date',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for employer packet',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for employer packet prep.',
      },
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for employer packet prep.',
      },
      {
        key: 'canonical-extraction-alignment',
        label: 'Canonical vs extracted values aligned',
        kind: 'requirement',
        nextActionCategory: 'document',
        blocksReady: true,
        requirementKey: 'canonical-extraction-alignment',
        missingReason: 'Canonical/extracted alignment has not been evaluated yet.',
        attentionReason: 'Structured case truth and extracted document values still disagree for employer packet prep.',
        satisfiedReason: 'Structured case truth and extracted document values are aligned for employer packet prep.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for HR packet',
        kind: 'field_presence',
        targetFields: ['applicant.current_first_name', 'applicant.current_last_name'],
        conditionalTargetFields: ['applicant.current_middle_name'],
        missingReason: 'Current legal name fields are still incomplete for employer packet prep.',
        satisfiedReason: 'Current legal name is available for employer packet prep.',
      },
      {
        key: 'target-legal-name',
        label: 'Target legal name available for HR packet',
        kind: 'field_presence',
        targetFields: ['applicant.target_first_name', 'applicant.target_last_name'],
        conditionalTargetFields: ['applicant.target_middle_name'],
        missingReason: 'Target legal name fields are still missing for employer packet prep.',
        satisfiedReason: 'Target legal name is available for employer packet prep.',
      },
      {
        key: 'hr-support-doc',
        label: 'Employer-supporting document intake',
        kind: 'document_support',
        documentKinds: ['social_security_card', 'current_drivers_license', 'current_passport'],
        missingReason: 'No employer-supporting identity document is represented in intake yet.',
        satisfiedReason: 'An employer-supporting identity document exists in intake.',
      },
    ],
  },
  taxes: {
    key: 'taxes',
    label: 'IRS and state tax alignment',
    lane: 'state',
    recommendedFormCode: NAME_CHANGE_TAX_PACKET_CONTRACT.formCode,
    formBuilderKey: 'taxes',
    sequenceProfile: 'taxes',
    prerequisiteRules: [
      {
        key: 'federal-ssa-complete',
        label: 'SSA completed before tax alignment',
        required: true,
        requiredStepId: 'federal-ssa',
        requiredStatuses: ['complete'],
        missingReason: 'IRS and state tax alignment should wait until SSA is complete because tax identity follows the Social Security record.',
        attentionReason: 'SSA is in motion, but tax alignment should still wait for completion.',
        satisfiedReason: 'SSA is complete, so IRS and state tax alignment can proceed cleanly.',
      },
      {
        key: 'employer-payroll-progress',
        label: 'Payroll / withholding lane is moving',
        required: false,
        requiredStepId: 'institution-irs-employer',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'Employer payroll and withholding updates are not moving yet, so state tax alignment may need manual follow-through.',
        attentionReason: 'Employer payroll and withholding updates are moving, which helps tax records stay aligned.',
        satisfiedReason: 'Employer payroll and withholding updates are already moving for tax alignment.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_first_name',
      'applicant.target_middle_name',
      'applicant.target_last_name',
      'legal.marriage_date',
      'applicant.county',
    ],
    checklistSpecs: [
      {
        key: 'legal-proof-document',
        label: 'Legal proof ready for tax alignment',
        kind: 'requirement',
        requirementKey: 'legal-proof-document',
        missingReason: 'Legal proof requirement not evaluated.',
        satisfiedReason: 'Legal proof document is ready for IRS and state tax alignment.',
      },
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for tax alignment.',
      },
      {
        key: 'county-context',
        label: 'State / county tax jurisdiction context',
        kind: 'requirement',
        requirementKey: 'county-context',
        missingReason: 'County and state tax jurisdiction context has not been evaluated yet.',
        satisfiedReason: 'County and state tax jurisdiction context is available for tax alignment.',
      },
      {
        key: 'canonical-extraction-alignment',
        label: 'Canonical vs extracted values aligned',
        kind: 'requirement',
        nextActionCategory: 'document',
        blocksReady: true,
        requirementKey: 'canonical-extraction-alignment',
        missingReason: 'Canonical/extracted alignment has not been evaluated yet.',
        attentionReason: 'Structured case truth and extracted document values still disagree for tax alignment.',
        satisfiedReason: 'Structured case truth and extracted document values are aligned for tax alignment.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for tax alignment',
        kind: 'field_presence',
        targetFields: ['applicant.current_first_name', 'applicant.current_last_name'],
        conditionalTargetFields: ['applicant.current_middle_name'],
        missingReason: 'Current legal name fields are still incomplete for tax alignment.',
        satisfiedReason: 'Current legal name is available for tax alignment.',
      },
      {
        key: 'target-legal-name',
        label: 'Target legal name available for tax alignment',
        kind: 'field_presence',
        targetFields: ['applicant.target_first_name', 'applicant.target_last_name'],
        conditionalTargetFields: ['applicant.target_middle_name'],
        missingReason: 'Target legal name fields are still missing for tax alignment.',
        satisfiedReason: 'Target legal name is available for tax alignment.',
      },
      {
        key: 'tax-support-doc',
        label: 'Tax-supporting identity document intake',
        kind: 'document_support',
        documentKinds: ['social_security_card', 'current_drivers_license', 'current_passport'],
        missingReason: 'No tax-supporting identity document is represented in intake yet.',
        satisfiedReason: 'A tax-supporting identity document exists in intake.',
      },
    ],
  },
  banks: buildPhotoIdInstitutionTarget({
    key: 'banks',
    label: 'Banks and credit cards',
    recommendedFormCode: NAME_CHANGE_BANK_PACKET_CONTRACT.formCode,
    formBuilderKey: 'banks',
    supportKey: 'bank-support-doc',
    supportLabel: 'Bank-supporting document intake',
    supportDocumentKinds: ['current_drivers_license', 'current_passport', 'proof_of_address'],
    primaryRule: {
      key: 'primary-photo-id-progress',
      label: 'Primary photo ID underway before bank rollout',
      required: true,
      requiredStepId: 'state-dmv',
      requiredStatuses: ['in_progress', 'complete'],
      missingReason: 'Banks are usually easiest once your primary photo ID is moving or already updated.',
      attentionReason: 'Primary photo ID is moving, which supports bank update follow-through.',
      satisfiedReason: 'Primary photo ID is already moving or complete for bank update follow-through.',
    },
    secondaryRule: {
      key: 'passport-or-dmv-progress',
      label: 'At least one travel / ID-facing record is moving',
      required: false,
      requiredStepId: 'federal-passport',
      requiredStatuses: ['in_progress', 'complete'],
      missingReason: 'No passport progress is recorded yet, so bank updates may rely only on DMV proof.',
      attentionReason: 'Passport progress exists, which helps cross-check travel-facing identity records.',
      satisfiedReason: 'Passport progress exists for cross-checking travel-facing identity records.',
    },
  }),
  insurance: buildPhotoIdInstitutionTarget({
    key: 'insurance',
    label: 'Health, auto, renters, and life insurance',
    recommendedFormCode: NAME_CHANGE_INSURANCE_PACKET_CONTRACT.formCode,
    formBuilderKey: 'insurance',
    supportKey: 'insurance-support-doc',
    supportLabel: 'Insurance-supporting document intake',
    supportDocumentKinds: ['current_drivers_license', 'current_passport', 'proof_of_address'],
    primaryRule: {
      key: 'primary-photo-id-progress',
      label: 'Primary photo ID underway before insurance rollout',
      required: true,
      requiredStepId: 'state-dmv',
      requiredStatuses: ['in_progress', 'complete'],
      missingReason: 'Insurance updates usually go smoother once your primary photo ID is moving or already updated.',
      attentionReason: 'Primary photo ID is moving, which supports insurance update follow-through.',
      satisfiedReason: 'Primary photo ID is already moving or complete for insurance update follow-through.',
    },
    secondaryRule: {
      key: 'employer-or-bank-progress',
      label: 'Another institutional lane is already moving',
      required: false,
      requiredStepId: 'institution-banks',
      requiredStatuses: ['in_progress', 'complete'],
      missingReason: 'No other institutional rollout step is moving yet, so insurance may be the first account-update lane to start.',
      attentionReason: 'Another institutional lane is already moving, which helps normalize packet handling.',
      satisfiedReason: 'Another institutional lane is already moving for packet normalization.',
    },
  }),
  medical: buildPhotoIdInstitutionTarget({
    key: 'medical',
    label: 'Medical providers / insurance cards',
    recommendedFormCode: NAME_CHANGE_MEDICAL_PACKET_CONTRACT.formCode,
    formBuilderKey: 'medical',
    supportKey: 'medical-support-doc',
    supportLabel: 'Medical-provider-supporting document intake',
    supportDocumentKinds: ['current_drivers_license', 'current_passport', 'proof_of_address'],
    primaryRule: {
      key: 'primary-photo-id-progress',
      label: 'Primary photo ID underway before medical record rollout',
      required: true,
      requiredStepId: 'state-dmv',
      requiredStatuses: ['in_progress', 'complete'],
      missingReason: 'Medical/provider record updates usually go smoother once your primary photo ID is moving or already updated.',
      attentionReason: 'Primary photo ID is moving, which supports medical/provider follow-through.',
      satisfiedReason: 'Primary photo ID is already moving or complete for medical/provider follow-through.',
    },
    secondaryRule: {
      key: 'insurance-rollout-progress',
      label: 'Insurance rollout already moving',
      required: false,
      requiredStepId: 'institution-insurance',
      requiredStatuses: ['in_progress', 'complete'],
      missingReason: 'Insurance rollout is not moving yet, so provider records may be the first healthcare lane to start.',
      attentionReason: 'Insurance rollout is already moving, which helps member records and provider rosters stay aligned.',
      satisfiedReason: 'Insurance rollout is already moving for healthcare record coordination.',
    },
  }),
  utilities: buildPhotoIdInstitutionTarget({
    key: 'utilities',
    label: 'Utilities / lease / landlord records',
    recommendedFormCode: NAME_CHANGE_UTILITIES_PACKET_CONTRACT.formCode,
    formBuilderKey: 'utilities',
    supportKey: 'utilities-support-doc',
    supportLabel: 'Utilities/lease-supporting document intake',
    supportDocumentKinds: ['current_drivers_license', 'proof_of_address'],
    primaryRule: {
      key: 'primary-photo-id-progress',
      label: 'Primary photo ID underway before utilities/lease rollout',
      required: true,
      requiredStepId: 'state-dmv',
      requiredStatuses: ['in_progress', 'complete'],
      missingReason: 'Utilities/lease record updates usually go smoother once your primary photo ID is moving or already updated.',
      attentionReason: 'Primary photo ID is moving, which supports utilities/lease follow-through.',
      satisfiedReason: 'Primary photo ID is already moving or complete for utilities/lease follow-through.',
    },
    secondaryRule: {
      key: 'bank-rollout-progress',
      label: 'Bank rollout already moving',
      required: false,
      requiredStepId: 'institution-banks',
      requiredStatuses: ['in_progress', 'complete'],
      missingReason: 'Bank rollout is not moving yet, so utilities/lease updates may be the first household admin lane to start.',
      attentionReason: 'Bank rollout is already moving, which helps household account records stay coordinated.',
      satisfiedReason: 'Bank rollout is already moving for household record coordination.',
    },
  }),
  courtesy: {
    key: 'courtesy',
    label: 'Courtesy / social identity sync',
    lane: 'state',
    recommendedFormCode: NAME_CHANGE_COURTESY_PACKET_CONTRACT.formCode,
    formBuilderKey: 'courtesy',
    sequenceProfile: 'courtesy',
    prerequisiteRules: [
      {
        key: 'banks-or-utilities-progress',
        label: 'At least one downstream admin lane is moving',
        required: false,
        requiredStepId: 'institution-banks',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'No downstream admin lane is moving yet, so courtesy/social sync may be premature.',
        attentionReason: 'A downstream admin lane is already moving, which makes courtesy/social sync easier to do at the tail end.',
        satisfiedReason: 'A downstream admin lane is already moving for tail-end courtesy/social sync.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_first_name',
      'applicant.target_middle_name',
      'applicant.target_last_name',
      'applicant.county',
    ],
    checklistSpecs: [
      {
        key: 'current-legal-name',
        label: 'Current name available for courtesy sync',
        kind: 'field_presence',
        targetFields: ['applicant.current_first_name', 'applicant.current_last_name'],
        conditionalTargetFields: ['applicant.current_middle_name'],
        missingReason: 'Current name fields are still incomplete for courtesy/social sync.',
        satisfiedReason: 'Current legal name is available for courtesy/social sync.',
      },
      {
        key: 'target-legal-name',
        label: 'Target legal name available for courtesy sync',
        kind: 'field_presence',
        targetFields: ['applicant.target_first_name', 'applicant.target_last_name'],
        conditionalTargetFields: ['applicant.target_middle_name'],
        missingReason: 'Target legal name fields are still missing for courtesy/social sync.',
        satisfiedReason: 'Target legal name is available for courtesy/social sync.',
      },
      {
        key: 'courtesy-support-doc',
        label: 'Courtesy/social account context available',
        kind: 'document_support',
        documentKinds: ['current_drivers_license', 'current_passport'],
        missingReason: 'No current account-facing identity context is represented in intake yet for courtesy/social sync.',
        satisfiedReason: 'Current account-facing identity context exists in intake for courtesy/social sync.',
      },
    ],
  },
  voter: {
    key: 'voter',
    label: 'California voter registration',
    lane: 'state',
    recommendedFormCode: NAME_CHANGE_VOTER_PACKET_CONTRACT.formCode,
    formBuilderKey: 'voter',
    sequenceProfile: 'voter',
    prerequisiteRules: [
      {
        key: 'state-dmv-complete',
        label: 'DMV completed before voter registration update',
        required: true,
        requiredStepId: 'state-dmv',
        requiredStatuses: ['complete'],
        missingReason: 'California voter registration should wait until DMV is complete so the state record chain stays aligned.',
        attentionReason: 'DMV is moving, but voter registration should still wait for the California ID record to settle.',
        satisfiedReason: 'DMV is complete, so voter registration can be updated cleanly.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_first_name',
      'applicant.target_middle_name',
      'applicant.target_last_name',
      'applicant.county',
    ],
    checklistSpecs: [
      {
        key: 'county-context',
        label: 'California county context available',
        kind: 'requirement',
        requirementKey: 'county-context',
        missingReason: 'County context requirement not evaluated.',
        satisfiedReason: 'County context is available for voter registration prep.',
      },
      {
        key: 'canonical-extraction-alignment',
        label: 'Canonical vs extracted values aligned',
        kind: 'requirement',
        nextActionCategory: 'document',
        blocksReady: true,
        requirementKey: 'canonical-extraction-alignment',
        missingReason: 'Canonical/extracted alignment has not been evaluated yet.',
        attentionReason: 'Structured case truth and extracted document values still disagree for voter registration prep.',
        satisfiedReason: 'Structured case truth and extracted document values are aligned for voter registration prep.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for voter update',
        kind: 'field_presence',
        targetFields: ['applicant.current_first_name', 'applicant.current_last_name'],
        conditionalTargetFields: ['applicant.current_middle_name'],
        missingReason: 'Current legal name fields are still incomplete for voter update prep.',
        satisfiedReason: 'Current legal name is available for voter update prep.',
      },
      {
        key: 'target-legal-name-county',
        label: 'Target legal name + county available',
        kind: 'field_presence',
        targetFields: ['applicant.target_first_name', 'applicant.target_last_name', 'applicant.county'],
        conditionalTargetFields: ['applicant.target_middle_name'],
        missingReason: 'Target legal name fields and/or county are still missing for voter update prep.',
        satisfiedReason: 'Target legal name plus county is available for voter update prep.',
      },
      {
        key: 'voter-support-doc',
        label: 'California voter-supporting intake',
        kind: 'document_support',
        documentKinds: ['current_drivers_license', 'proof_of_address'],
        missingReason: 'No California voter-supporting ID/address document is represented in intake yet.',
        satisfiedReason: 'A California voter-supporting ID/address document exists in intake.',
      },
    ],
  },
  tsa: {
    key: 'tsa',
    label: 'TSA PreCheck / travel profiles',
    lane: 'federal',
    recommendedFormCode: NAME_CHANGE_TSA_PACKET_CONTRACT.formCode,
    formBuilderKey: 'tsa',
    sequenceProfile: 'tsa',
    prerequisiteRules: [
      {
        key: 'passport-progress',
        label: 'Passport underway before TSA/travel profile update',
        required: true,
        requiredStepId: 'federal-passport',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'TSA / travel profiles should wait until passport work is underway so bookings and identity records stay aligned.',
        attentionReason: 'Passport work is moving, which supports TSA / travel profile follow-through.',
        satisfiedReason: 'Passport work is already moving or complete for TSA / travel profile follow-through.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_first_name',
      'applicant.target_middle_name',
      'applicant.target_last_name',
      'identity.passport_issue_date',
    ],
    checklistSpecs: [
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for TSA / travel profile prep.',
      },
      {
        key: 'canonical-extraction-alignment',
        label: 'Canonical vs extracted values aligned',
        kind: 'requirement',
        nextActionCategory: 'document',
        blocksReady: true,
        requirementKey: 'canonical-extraction-alignment',
        missingReason: 'Canonical/extracted alignment has not been evaluated yet.',
        attentionReason: 'Structured case truth and extracted document values still disagree for TSA / travel profile prep.',
        satisfiedReason: 'Structured case truth and extracted document values are aligned for TSA / travel profile prep.',
      },
      {
        key: 'marriage-jurisdiction-alignment',
        label: 'Marriage jurisdiction alignment',
        kind: 'requirement',
        requirementKey: 'marriage-jurisdiction-alignment',
        missingReason: 'Marriage jurisdiction alignment has not been evaluated yet.',
        attentionReason: 'Marriage happened outside California, so TSA / travel-profile follow-through should keep the out-of-state certificate path in view.',
        satisfiedReason: 'Marriage jurisdiction is aligned for the modeled TSA / travel-profile flow.',
      },
      {
        key: 'out-of-state-marriage-certificate-grounding',
        label: 'Out-of-state marriage certificate grounding',
        kind: 'requirement',
        requirementKey: 'out-of-state-marriage-certificate-grounding',
        missingReason: 'Out-of-state marriage certificate grounding has not been evaluated yet.',
        attentionReason: 'TSA / travel-profile follow-through still needs grounded certificate reference fields from the out-of-state marriage certificate.',
        satisfiedReason: 'Out-of-state marriage certificate grounding is ready for TSA / travel-profile follow-through.',
      },
      {
        key: 'passport-timing-risk',
        label: 'Passport timing risk reviewed',
        kind: 'requirement',
        requirementKey: 'passport-timing-risk',
        missingReason: 'Passport timing review has not been evaluated yet.',
        attentionReason: 'Travel is already booked and passport timing still needs careful sequencing.',
        satisfiedReason: 'Passport timing risk has been reviewed for TSA / travel profile prep.',
      },
      {
        key: 'expedited-travel-sequencing',
        label: 'Expedited travel sequencing ready',
        kind: 'requirement',
        requirementKey: 'expedited-travel-sequencing',
        missingReason: 'Expedited travel sequencing has not been evaluated yet.',
        attentionReason: 'Expedited travel is in play, so TSA / travel profile updates should stay on the fast path.',
        satisfiedReason: 'Expedited travel sequencing is ready for TSA / travel profile prep.',
      },
      {
        key: 'passport-eligibility-path',
        label: 'Passport eligibility path is clear',
        kind: 'requirement',
        requirementKey: 'passport-eligibility-path',
        missingReason: 'Passport eligibility path has not been evaluated yet.',
        satisfiedReason: 'Passport eligibility path is clear for TSA / travel profile follow-through.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for TSA update',
        kind: 'field_presence',
        targetFields: ['applicant.current_first_name', 'applicant.current_last_name'],
        conditionalTargetFields: ['applicant.current_middle_name'],
        missingReason: 'Current legal name fields are still incomplete for TSA / travel profile prep.',
        satisfiedReason: 'Current legal name is available for TSA / travel profile prep.',
      },
      {
        key: 'target-legal-name',
        label: 'Target legal name available for TSA update',
        kind: 'field_presence',
        targetFields: ['applicant.target_first_name', 'applicant.target_last_name'],
        conditionalTargetFields: ['applicant.target_middle_name'],
        missingReason: 'Target legal name fields are still missing for TSA / travel profile prep.',
        satisfiedReason: 'Target legal name is available for TSA / travel profile prep.',
      },
      {
        key: 'tsa-support-doc',
        label: 'Travel-profile-supporting document intake',
        kind: 'document_support',
        documentKinds: ['current_passport', 'current_drivers_license'],
        missingReason: 'No passport or Real ID support document is represented in intake yet for travel-profile updates.',
        satisfiedReason: 'A passport or Real ID support document exists in intake for travel-profile updates.',
      },
    ],
  },
  licenses: {
    key: 'licenses',
    label: 'Professional licenses / certifications',
    lane: 'state',
    recommendedFormCode: NAME_CHANGE_LICENSE_PACKET_CONTRACT.formCode,
    formBuilderKey: 'licenses',
    sequenceProfile: 'licenses',
    prerequisiteRules: [
      {
        key: 'primary-photo-id-progress',
        label: 'Primary photo ID underway before license updates',
        required: true,
        requiredStepId: 'state-dmv',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'Professional license updates usually go smoother once your primary photo ID is moving or already updated.',
        attentionReason: 'Primary photo ID is moving, which supports professional license follow-through.',
        satisfiedReason: 'Primary photo ID is already moving or complete for professional license follow-through.',
      },
      {
        key: 'employer-rollout-progress',
        label: 'Employer / payroll rollout already moving',
        required: false,
        requiredStepId: 'institution-irs-employer',
        requiredStatuses: ['in_progress', 'complete'],
        missingReason: 'Employer / payroll rollout is not moving yet, so professional-license updates may be starting first.',
        attentionReason: 'Employer / payroll rollout is already moving, which helps work-related identity changes stay coordinated.',
        satisfiedReason: 'Employer / payroll rollout is already moving for work-related identity coordination.',
      },
    ],
    autofillTargetFields: [
      'applicant.current_first_name',
      'applicant.current_middle_name',
      'applicant.current_last_name',
      'applicant.target_first_name',
      'applicant.target_middle_name',
      'applicant.target_last_name',
      'applicant.county',
    ],
    checklistSpecs: [
      {
        key: 'identity-document-coverage',
        label: 'Identity document coverage',
        kind: 'requirement',
        requirementKey: 'identity-document-coverage',
        missingReason: 'Identity coverage requirement not evaluated.',
        satisfiedReason: 'Identity document coverage is ready for professional license prep.',
      },
      {
        key: 'canonical-extraction-alignment',
        label: 'Canonical vs extracted values aligned',
        kind: 'requirement',
        nextActionCategory: 'document',
        blocksReady: true,
        requirementKey: 'canonical-extraction-alignment',
        missingReason: 'Canonical/extracted alignment has not been evaluated yet.',
        attentionReason: 'Structured case truth and extracted document values still disagree for professional license prep.',
        satisfiedReason: 'Structured case truth and extracted document values are aligned for professional license prep.',
      },
      {
        key: 'current-legal-name',
        label: 'Current legal name available for license update',
        kind: 'field_presence',
        targetFields: ['applicant.current_first_name', 'applicant.current_last_name'],
        conditionalTargetFields: ['applicant.current_middle_name'],
        missingReason: 'Current legal name fields are still incomplete for professional license prep.',
        satisfiedReason: 'Current legal name is available for professional license prep.',
      },
      {
        key: 'target-legal-name',
        label: 'Target legal name available for license update',
        kind: 'field_presence',
        targetFields: ['applicant.target_first_name', 'applicant.target_last_name'],
        conditionalTargetFields: ['applicant.target_middle_name'],
        missingReason: 'Target legal name fields are still missing for professional license prep.',
        satisfiedReason: 'Target legal name is available for professional license prep.',
      },
      {
        key: 'license-support-doc',
        label: 'Professional-license-supporting intake',
        kind: 'document_support',
        documentKinds: ['current_drivers_license', 'current_passport'],
        missingReason: 'No current ID document is represented in intake yet for professional license updates.',
        satisfiedReason: 'A current ID document exists in intake for professional license updates.',
      },
    ],
  },
};
