#!/usr/bin/env node
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const registryPage = readFileSync(resolve(process.cwd(), 'src/pages/dashboard/Registry.tsx'), 'utf8');
const registryTypes = readFileSync(resolve(process.cwd(), 'src/pages/dashboard/registry/registryTypes.ts'), 'utf8');
const repairState = readFileSync(resolve(process.cwd(), 'src/pages/dashboard/registry/repairState.ts'), 'utf8');
const duplicateRegistryItems = readFileSync(resolve(process.cwd(), 'src/pages/dashboard/registry/duplicateRegistryItems.ts'), 'utf8');
const registryItemCard = readFileSync(resolve(process.cwd(), 'src/pages/dashboard/registry/RegistryItemCard.tsx'), 'utf8');
const registryItemForm = readFileSync(resolve(process.cwd(), 'src/pages/dashboard/registry/RegistryItemForm.tsx'), 'utf8');
const sectionRegistry = readFileSync(resolve(process.cwd(), 'src/sections/registry.ts'), 'utf8');
const canonicalSectionRegistry = readFileSync(resolve(process.cwd(), 'src/lib/canonicalSectionRegistry.ts'), 'utf8');
const registryCardsSection = readFileSync(resolve(process.cwd(), 'src/sections/variants/registry/cards.tsx'), 'utf8');
const registryFeaturedSection = readFileSync(resolve(process.cwd(), 'src/sections/variants/registry/featured.tsx'), 'utf8');
const registrySectionComponent = readFileSync(resolve(process.cwd(), 'src/sections/components/RegistrySection.tsx'), 'utf8');
const sectionManifests = readFileSync(resolve(process.cwd(), 'src/builder/registry/sectionManifests.ts'), 'utf8');
const templateRegistry = readFileSync(resolve(process.cwd(), 'src/templates/registry.ts'), 'utf8');
const sectionVariantCompatibility = readFileSync(resolve(process.cwd(), 'src/lib/sectionVariantCompatibility.ts'), 'utf8');
const builderV2Lab = readFileSync(resolve(process.cwd(), 'src/pages/BuilderV2Lab.tsx'), 'utf8');
const legacySectionRegistry = readFileSync(resolve(process.cwd(), 'src/sections/sectionRegistry.tsx'), 'utf8');
const builderInspectorPanel = readFileSync(resolve(process.cwd(), 'src/builder/components/BuilderInspectorPanel.tsx'), 'utf8');
const builderSectionRail = readFileSync(resolve(process.cwd(), 'src/builder/components/BuilderSectionRail.tsx'), 'utf8');
const builderSidebarLibrary = readFileSync(resolve(process.cwd(), 'src/builder/components/BuilderSidebarLibrary.tsx'), 'utf8');
const variantPreviewSource = readFileSync(resolve(process.cwd(), 'src/builder/registry/variantPreviewSource.ts'), 'utf8');
const siteView = readFileSync(resolve(process.cwd(), 'src/pages/SiteView.tsx'), 'utf8');
const registryProof = readFileSync(resolve(process.cwd(), 'scripts/v1-proof-registry.mjs'), 'utf8');

const checks = [
  { name: 'dashboard uses sanitizeRegistryQuantityState', ok: registryPage.includes('sanitizeRegistryQuantityState') },
  { name: 'dashboard loads duplicate registry groups', ok: registryPage.includes('findDuplicateRegistryGroups') },
  { name: 'dashboard demo creates preserve canonical registry metadata', ok: registryPage.includes('canonical_url: fields.canonical_url ?? null') && registryPage.includes('metadata_fetch_status: fields.metadata_fetch_status ?? \'manual\'') },
  { name: 'dashboard repair queue includes unavailable registry imports', ok: registryPage.includes('product unavailable') },
  { name: 'dashboard refresh syncs merchant into store_name', ok: registryPage.includes('fields.store_name = (preview.merchant ?? preview.brand)!;') },
  { name: 'dashboard auto-refresh syncs merchant into store_name', ok: registryPage.includes('if (preview.merchant ?? preview.brand) {\n          fields.merchant = (preview.merchant ?? preview.brand)!;\n          fields.store_name = (preview.merchant ?? preview.brand)!;\n        }') },
  { name: 'section registry keeps strict alias fallbacks for template-backed registry variants', ok: sectionRegistry.includes('const def = strictVariant') && sectionRegistry.includes('VARIANT_FALLBACKS[type]?.[normalizedVariant] ? getDefinition(normalizedType, VARIANT_FALLBACKS[type][normalizedVariant]) : null') },
  { name: 'section registry normalizes malformed persisted registry variants before public render fallback', ok: sectionRegistry.includes('function normalizeRegistryVariantKey(variant: unknown): string {') && sectionRegistry.includes("return typeof variant === 'string'") && sectionRegistry.includes('const normalizedVariant = resolveRegistryVariant(type, variant);') && sectionRegistry.includes('normalizeRegistryVariantKey(aliasVariant) === normalizedVariantKey') },
  { name: 'builder registry manifest exposes template-backed and legacy registry variants', ok: sectionManifests.includes("supportedVariants: ['default', 'cards', 'grid', 'fundHighlight', 'featured', 'minimal', 'honeymoon', 'tabs', 'illustrated', 'classic', 'luxury', 'experiences', 'modern', 'playful']") && sectionManifests.includes("variantMeta: [\n      { id: 'cards'") && sectionManifests.includes("{ id: 'default', label: 'Default'") && sectionManifests.includes("{ id: 'grid', label: 'Grid'") && sectionManifests.includes("'classic'") && sectionManifests.includes("'luxury'") && sectionManifests.includes("'experiences'") && sectionManifests.includes("'modern'") && sectionManifests.includes("'playful'") },
  { name: 'shipped templates only use builder-supported registry variants', ok: templateRegistry.includes("variant: 'classic'") && templateRegistry.includes("variant: 'luxury'") && templateRegistry.includes("variant: 'experiences'") && sectionManifests.includes("'classic'") && sectionManifests.includes("'luxury'") && sectionManifests.includes("'experiences'") },
  { name: 'template registry import surfaces deep-clone and normalize definitions before owner edits mutate them', ok: templateRegistry.includes('const REGISTRY_VARIANT_ALIASES: Record<string, string> = {') && templateRegistry.includes('function cloneTemplateValue<T>(value: T): T {') && templateRegistry.includes("templateRegistry.map((template) => [template.id, cloneTemplateDefinition(template)])") && templateRegistry.includes("base: cloneTemplateDefinition(templateById['timeless-classic'] ?? templateRegistry[0]),") && templateRegistry.includes("variant: section.type === 'registry' && typeof section.variant === 'string'") && templateRegistry.includes('bindings: cloneTemplateValue(section.bindings ?? {}),') && templateRegistry.includes('settings: cloneTemplateValue(section.settings ?? {}),') && templateRegistry.includes('overrides: cloneTemplateValue(section.overrides ?? undefined),') && templateRegistry.includes('function cloneTemplateDefinition(template: TemplateDefinition): TemplateDefinition {') && templateRegistry.includes('return cloneTemplateDefinition(TEMPLATE_REGISTRY[templateId] || TEMPLATE_REGISTRY.base || templateRegistry[0]);') && templateRegistry.includes('return templateRegistry.map(cloneTemplateDefinition);') },
  { name: 'shipped templates only use legacy-renderable registry variants', ok: templateRegistry.includes("variant: 'classic'") && templateRegistry.includes("variant: 'luxury'") && templateRegistry.includes("variant: 'experiences'") && legacySectionRegistry.includes("classic: RegistryGrid") && legacySectionRegistry.includes("luxury: RegistryFundHighlight") && legacySectionRegistry.includes("experiences: RegistryFundHighlight") },
  { name: 'builder registry variant compatibility preserves shipped public variants', ok: sectionVariantCompatibility.includes("registry: ['default', 'cards', 'grid', 'fundHighlight', 'featured', 'minimal', 'honeymoon', 'tabs', 'illustrated', 'classic', 'luxury', 'experiences', 'modern', 'playful']") && sectionVariantCompatibility.includes("luxury: 'fundHighlight'") && sectionVariantCompatibility.includes("experiences: 'fundHighlight'") },
  { name: 'builder registry variant compatibility tolerates trim casing punctuation and malformed fallback drift', ok: sectionVariantCompatibility.includes('export function resolveBuilderVariant(type: SectionType, variant: unknown): string {') && sectionVariantCompatibility.includes("function getPreferredBuilderFallbackVariant(type: SectionType, supported: string[]): string {") && sectionVariantCompatibility.includes("if (type === 'registry') return supported.includes('cards') ? 'cards' : supported[0] ?? 'default';") && sectionVariantCompatibility.includes("const normalizeVariantKey = (value: unknown) => typeof value === 'string'") && sectionVariantCompatibility.includes("const normalizedVariant = typeof variant === 'string' ? variant.trim() : '';") && sectionVariantCompatibility.includes('const supportedByKey = new Map') && sectionVariantCompatibility.includes('const canonicalVariant = supportedByKey.get(normalizedVariantKey) ?? normalizedVariant;') && sectionVariantCompatibility.includes("Object.entries(aliases).find(([aliasVariant]) => normalizeVariantKey(aliasVariant) === normalizedVariantKey)?.[1]") && sectionVariantCompatibility.includes("if (!alias) return fallbackVariant;") },
  { name: 'builder lab registry picker exposes shipped template variants', ok: builderV2Lab.includes("registry: ['default', 'cards', 'grid', 'fundHighlight', 'featured', 'minimal', 'honeymoon', 'tabs', 'illustrated', 'classic', 'luxury', 'experiences', 'modern', 'playful']") },
  { name: 'builder lab registry commands expose shipped template variants', ok: builderV2Lab.includes("['default', 'countdown', 'timeline', 'dayTabs', 'localGuide', 'iconGrid', 'cards', 'grid', 'fundHighlight', 'featured', 'minimal', 'honeymoon', 'tabs', 'illustrated', 'classic', 'luxury', 'experiences', 'modern', 'playful']") },
  { name: 'legacy section registry preserves public registry aliases', ok: legacySectionRegistry.includes("component: RegistryGrid") && legacySectionRegistry.includes("variants: {\n      cards: RegistryGrid,") && legacySectionRegistry.includes("default: RegistryGrid") && legacySectionRegistry.includes("classic: RegistryGrid") && legacySectionRegistry.includes("luxury: RegistryFundHighlight") && legacySectionRegistry.includes("cards: RegistryGrid") && legacySectionRegistry.includes("minimal: RegistryGrid") && legacySectionRegistry.includes("featured: RegistryFundHighlight") },
  { name: 'legacy section registry keeps every builder registry variant renderable', ok: legacySectionRegistry.includes("fundHighlight: RegistryFundHighlight") && legacySectionRegistry.includes("grid: RegistryGrid") && sectionManifests.includes("supportedVariants: ['default', 'cards', 'grid', 'fundHighlight', 'featured', 'minimal', 'honeymoon', 'tabs', 'illustrated', 'classic', 'luxury', 'experiences', 'modern', 'playful']") },
  { name: 'legacy section registry orders registry variants by builder-first public layouts', ok: legacySectionRegistry.includes("variants: {\n      cards: RegistryGrid,\n      fundHighlight: RegistryFundHighlight,\n      featured: RegistryFundHighlight,\n      minimal: RegistryGrid") && sectionManifests.includes("variantMeta: [\n      { id: 'cards'") },
  { name: 'site view registry fallback normalization stays aligned with public registry aliases', ok: siteView.includes("registry: {") && siteView.includes("default: 'cards'") && siteView.includes("fundHighlight: 'featured'") && siteView.includes("luxury: 'featured'") && siteView.includes("modern: 'cards'") && siteView.includes("const nextVariant = fallbackMap[section.type]?.[section.variant] ?? supported[0] ?? 'default';") },
  { name: 'legacy public registry surfaces keep empty live loads from falling back to stale links', ok: registrySectionComponent.includes('export function shouldUseLiveRegistryItems(items: RegistryItem[] | null): items is RegistryItem[] {') && registrySectionComponent.includes('if (shouldUseLiveRegistryItems(items)) {') },
  { name: 'public registry purchaser labels stay aligned with owner purchase state truth', ok: registrySectionComponent.includes("export function getRegistryPurchaserStatusLabel(item: Pick<RegistryItem, 'purchase_status' | 'purchaser_name'>): string | null {") && registrySectionComponent.includes("if (!item.purchaser_name || item.purchase_status === 'available') return null;") && registrySectionComponent.includes("? `Purchased by ${item.purchaser_name}`") },
  { name: 'registry proof output encodes remaining runtime truth gaps', ok: registryProof.includes("status: 'manual-proof-pending'") && registryProof.includes("highestRiskTrustGap: 'runtime_registry_truth_after_real_edits'") && registryProof.includes("secondaryTrustGap: 'registry_repair_and_import_persistence_manual_verification_missing'") && registryProof.includes('manualProofRequired: true') && registryProof.includes("truthGateSummary: 'automation_green_manual_truth_red'") && registryProof.includes("'owner_manage_import_persistence_runtime_pass'") && registryProof.includes("'owner_repair_cleanup_runtime_pass'") && registryProof.includes("'guest_visible_purchase_truth_runtime_pass'") },
  { name: 'builder registry previews map aliases onto guest-visible layouts', ok: variantPreviewSource.includes("case 'classic':") && variantPreviewSource.includes("case 'default':") && variantPreviewSource.includes("return 'cards';") && variantPreviewSource.includes("case 'luxury':") && variantPreviewSource.includes("return 'featured';") && builderInspectorPanel.includes('getVariantPreviewSource(selectedSection.type, v.id)') && builderSectionRail.includes('getVariantPreviewSource(addTypeManifest.type, v.id)') && builderSidebarLibrary.includes('PREVIEW_FIXTURES_BY_VARIANT[`${sectionType}:${previewVariantId}`]') },
  { name: 'canonical registry validation accepts template-backed registry aliases', ok: canonicalSectionRegistry.includes("luxury: 'featured'") && canonicalSectionRegistry.includes("experiences: 'featured'") && canonicalSectionRegistry.includes("classic: 'cards'") },
  { name: 'public registry cards keep canonical-only store links usable', ok: registryCardsSection.includes("return item.item_url ?? item.canonical_url ?? null;") && registryCardsSection.includes('url: existing.url ?? publicUrl') },
  { name: 'public registry cards separate partial and claimed store counts', ok: registryCardsSection.includes("partial: existing.partial + (item.purchase_status === 'partial' ? 1 : 0)") && registryCardsSection.includes("group.purchased > 0 ? ` · ${group.purchased} claimed` : ''") },
  { name: 'public registry cards do not fall back to template links after empty live loads', ok: registryCardsSection.includes('return liveItems !== null;') && registryCardsSection.includes('const shouldUseLiveStoreGroups = shouldUseLiveRegistryStoreGroups(liveItems);') },
  { name: 'public registry featured links derive live store urls from canonical items', ok: registryFeaturedSection.includes("return item.item_url ?? item.canonical_url ?? '';") && registryFeaturedSection.includes('const displayStoreLinks = shouldUseLiveData ? groupRegistryStoreLinks(liveItems) : safeStoreLinks;') },
  { name: 'public registry featured view does not fall back after empty live loads', ok: registryFeaturedSection.includes('return liveItems !== null;') && registryFeaturedSection.includes('const shouldUseLiveData = shouldUseLiveRegistryFeaturedData(liveItems);') },
  { name: 'public registry featured cards expose partial purchase truth', ok: registryFeaturedSection.includes("isPartiallyClaimed: item.purchase_status === 'partial'") && registryFeaturedSection.includes("{gift.isPartiallyClaimed ? 'Gift remaining' : 'Gift this'}") },
  { name: 'public registry hero featured cards expose partial purchase truth', ok: registryFeaturedSection.includes('heroGift.isPartiallyClaimed && !heroGift.isClaimed') && registryFeaturedSection.includes("heroGift.isPartiallyClaimed ? 'View remaining gift' : 'View gift'") },
  { name: 'public registry detail cards expose partial purchase cta truth', ok: registrySectionComponent.includes("return item.purchase_status === 'partial' ? 'Buy remaining' : 'Mark as purchasing';") },
  { name: 'public registry detail sorting keeps partial items ahead of purchased ones', ok: registrySectionComponent.includes("item.purchase_status === 'partial'") && registrySectionComponent.includes('const scoreA = getRegistryDisplayPriority(a);') },
  { name: 'public registry purchase dialog copy matches partial purchase truth', ok: registrySectionComponent.includes("title: 'Buy remaining gift'") && registrySectionComponent.includes("confirmLabel: 'Confirm remaining purchase'") },
  { name: 'public registry empty state does not overclaim purchased truth under filters', ok: registrySectionComponent.includes("return 'No items match this filter right now.';") },
  { name: 'registry types expose itemNeedsAttention', ok: registryTypes.includes('export function itemNeedsAttention') },
  { name: 'registry types expose blocked retailer messaging', ok: registryTypes.includes('Amazon blocks automated product lookups') },
  { name: 'registry types expose quantity sanitation', ok: registryTypes.includes('export function sanitizeRegistryQuantityState') },
  { name: 'registry types expose comparison URL normalization', ok: registryTypes.includes('export function normalizeRegistryComparisonUrl') },
  { name: 'registry types expose title normalization', ok: registryTypes.includes('export function normalizeRegistryTitleForComparison') },
  { name: 'repair state exposes getRegistryRepairStates', ok: repairState.includes('export function getRegistryRepairStates') },
  { name: 'duplicate grouping normalizes title-only items', ok: duplicateRegistryItems.includes('normalizeRegistryTitleForComparison') },
  { name: 'registry cards fall back to canonical page preview URLs', ok: registryItemCard.includes('const pagePreviewSourceUrl = item.item_url ?? item.canonical_url ?? null;') },
  { name: 'owner registry purchaser labels stay aligned with purchase state truth', ok: registryItemCard.includes("export function getOwnerRegistryPurchaserLabel(item: Pick<RegistryItem, 'purchase_status' | 'purchaser_name'>): string | null {") && registryItemCard.includes("? `Purchased by ${item.purchaser_name}`") },
  { name: 'registry form seeds canonical links into editable product URLs', ok: registryItemForm.includes("const [urlInput, setUrlInput] = useState(initial?.item_url ?? initial?.canonical_url ?? '');") && registryItemForm.includes('canonical_url: nextUrl,') },
];

const failures = checks.filter((check) => !check.ok);
if (failures.length) {
  console.error('registry guard failed');
  failures.forEach((failure) => console.error(`- ${failure.name}`));
  process.exit(1);
}

console.log(JSON.stringify({ ok: true, checks: checks.map((check) => check.name) }, null, 2));
