import { BuilderTemplateDefinition } from '../../types/builder/template';

export const BUILDER_TEMPLATE_PACKS: Record<string, BuilderTemplateDefinition> = {
  'modern-luxe': {
    id: 'modern-luxe',
    displayName: 'Modern Luxe',
    description: 'Clean lines, bold typography, and editorial photography with a sophisticated luxury feel.',
    moodTags: ['modern', 'luxe', 'editorial'],
    previewThumbnailPath: '/templates/modern-luxe/preview.jpg',
    defaultThemeId: 'elegant',
    sectionComposition: [
      { type: 'hero', variant: 'fullbleed', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'story', variant: 'split', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'venue', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'schedule', variant: 'timeline', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'travel', variant: 'cards', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'registry', variant: 'grid', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'gallery', variant: 'masonry', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'faq', variant: 'accordion', enabled: false, locked: false, settings: { showTitle: true } },
      { type: 'rsvp', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
    ],
    sectionVariantMap: {
      hero: 'fullbleed',
      story: 'split',
      venue: 'default',
      schedule: 'timeline',
      travel: 'cards',
      registry: 'grid',
      gallery: 'masonry',
      faq: 'accordion',
      rsvp: 'default',
    },
    suggestedFonts: { heading: 'Playfair Display', body: 'Inter' },
    spacingProfile: 'spacious',
    isNew: true,
    isPremium: true,
  },

  'editorial-romance': {
    id: 'editorial-romance',
    displayName: 'Editorial Romance',
    description: 'Film-inspired layouts with moody photography, expressive typography, and intimate warmth.',
    moodTags: ['editorial', 'romantic', 'modern'],
    previewThumbnailPath: '/templates/editorial-romance/preview.jpg',
    defaultThemeId: 'romantic',
    sectionComposition: [
      { type: 'hero', variant: 'fullbleed', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'story', variant: 'centered', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'gallery', variant: 'masonry', enabled: true, locked: false, settings: { showTitle: false } },
      { type: 'venue', variant: 'card', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'schedule', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'registry', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'rsvp', variant: 'inline', enabled: true, locked: false, settings: { showTitle: true } },
    ],
    sectionVariantMap: {
      hero: 'fullbleed',
      story: 'centered',
      gallery: 'masonry',
      venue: 'card',
      schedule: 'default',
      registry: 'default',
      rsvp: 'inline',
    },
    suggestedFonts: { heading: 'Cormorant Garamond', body: 'Lato' },
    spacingProfile: 'balanced',
    isPremium: true,
  },

  'timeless-classic': {
    id: 'timeless-classic',
    displayName: 'Timeless Classic',
    description: 'Ivory, navy, and gold with refined structure and traditional elegance.',
    moodTags: ['classic', 'romantic', 'luxe'],
    previewThumbnailPath: '/templates/timeless-classic/preview.jpg',
    defaultThemeId: 'classic',
    sectionComposition: [
      { type: 'hero', variant: 'minimal', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'story', variant: 'split', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'venue', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'schedule', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'travel', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'faq', variant: 'accordion', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'registry', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'rsvp', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
    ],
    sectionVariantMap: {
      hero: 'minimal',
      story: 'split',
      venue: 'default',
      schedule: 'default',
      travel: 'default',
      faq: 'accordion',
      registry: 'default',
      rsvp: 'default',
    },
    suggestedFonts: { heading: 'EB Garamond', body: 'Source Sans Pro' },
    spacingProfile: 'balanced',
  },

  'destination-minimal': {
    id: 'destination-minimal',
    displayName: 'Destination Minimal',
    description: 'Clean whitespace, understated typography, and map-forward layouts for the modern destination wedding.',
    moodTags: ['minimal', 'destination', 'modern'],
    previewThumbnailPath: '/templates/destination-minimal/preview.jpg',
    defaultThemeId: 'ocean',
    sectionComposition: [
      { type: 'hero', variant: 'minimal', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'venue', variant: 'card', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'travel', variant: 'cards', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'schedule', variant: 'timeline', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'story', variant: 'centered', enabled: false, locked: false, settings: { showTitle: true } },
      { type: 'faq', variant: 'accordion', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'rsvp', variant: 'inline', enabled: true, locked: false, settings: { showTitle: true } },
    ],
    sectionVariantMap: {
      hero: 'minimal',
      venue: 'card',
      travel: 'cards',
      schedule: 'timeline',
      story: 'centered',
      faq: 'accordion',
      rsvp: 'inline',
    },
    suggestedFonts: { heading: 'DM Serif Display', body: 'DM Sans' },
    spacingProfile: 'spacious',
  },

  'floral-garden': {
    id: 'floral-garden',
    displayName: 'Floral Garden',
    description: 'Lush botanical accents, soft greens, and an organic warmth perfect for garden weddings.',
    moodTags: ['floral', 'garden', 'romantic'],
    previewThumbnailPath: '/templates/floral-garden/preview.jpg',
    defaultThemeId: 'garden',
    sectionComposition: [
      { type: 'hero', variant: 'fullbleed', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'story', variant: 'split', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'gallery', variant: 'default', enabled: true, locked: false, settings: { showTitle: false } },
      { type: 'venue', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'schedule', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'travel', variant: 'default', enabled: false, locked: false, settings: { showTitle: true } },
      { type: 'registry', variant: 'grid', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'faq', variant: 'accordion', enabled: false, locked: false, settings: { showTitle: true } },
      { type: 'rsvp', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
    ],
    sectionVariantMap: {
      hero: 'fullbleed',
      story: 'split',
      gallery: 'default',
      venue: 'default',
      schedule: 'default',
      travel: 'default',
      registry: 'grid',
      faq: 'accordion',
      rsvp: 'default',
    },
    suggestedFonts: { heading: 'Gilda Display', body: 'Nunito' },
    spacingProfile: 'balanced',
  },
};

export function getAllTemplatePacks(): BuilderTemplateDefinition[] {
  return Object.values(BUILDER_TEMPLATE_PACKS);
}

export function getTemplatePack(id: string): BuilderTemplateDefinition | null {
  return BUILDER_TEMPLATE_PACKS[id] ?? null;
}
