import { BuilderTemplateDefinition } from '../../types/builder/template';

export const BUILDER_TEMPLATE_PACKS: Record<string, BuilderTemplateDefinition> = {
  'modern-luxe': {
    id: 'modern-luxe',
    displayName: 'Modern Luxe',
    description: 'Editorial photography, razor-sharp typography, and a sophisticated black-and-gold palette. Built for couples who want their wedding site to feel like a luxury brand.',
    moodTags: ['modern', 'luxe', 'editorial'],
    previewThumbnailPath: '/templates/modern-luxe/preview.jpg',
    defaultThemeId: 'elegant',
    sectionComposition: [
      { type: 'hero', variant: 'fullbleed', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'story', variant: 'split', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'gallery', variant: 'filmStrip', enabled: true, locked: false, settings: { showTitle: false } },
      { type: 'venue', variant: 'splitMap', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'schedule', variant: 'timeline', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'registry', variant: 'featured', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'travel', variant: 'hotelBlock', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'faq', variant: 'accordion', enabled: false, locked: false, settings: { showTitle: true } },
      { type: 'rsvp', variant: 'card', enabled: true, locked: false, settings: { showTitle: true } },
    ],
    sectionVariantMap: {
      hero: 'fullbleed',
      story: 'split',
      gallery: 'filmStrip',
      venue: 'splitMap',
      schedule: 'timeline',
      registry: 'featured',
      travel: 'hotelBlock',
      faq: 'accordion',
      rsvp: 'card',
    },
    suggestedFonts: { heading: 'Playfair Display', body: 'Inter' },
    spacingProfile: 'spacious',
    isNew: true,
    isPremium: true,
  },

  'editorial-romance': {
    id: 'editorial-romance',
    displayName: 'Editorial Romance',
    description: 'Film-grain warmth meets fashion-magazine typography. Moody photography, generous white space, and a story-first layout that puts your love narrative front and center.',
    moodTags: ['editorial', 'romantic', 'modern'],
    previewThumbnailPath: '/templates/editorial-romance/preview.jpg',
    defaultThemeId: 'editorial',
    sectionComposition: [
      { type: 'hero', variant: 'fullbleed', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'story', variant: 'centered', enabled: true, locked: false, settings: { showTitle: false } },
      { type: 'gallery', variant: 'masonry', enabled: true, locked: false, settings: { showTitle: false } },
      { type: 'venue', variant: 'card', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'schedule', variant: 'agendaCards', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'travel', variant: 'list', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'registry', variant: 'minimal', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'rsvp', variant: 'inline', enabled: true, locked: false, settings: { showTitle: true } },
    ],
    sectionVariantMap: {
      hero: 'fullbleed',
      story: 'centered',
      gallery: 'masonry',
      venue: 'card',
      schedule: 'agendaCards',
      travel: 'list',
      registry: 'minimal',
      rsvp: 'inline',
    },
    suggestedFonts: { heading: 'Cormorant Garamond', body: 'Lato' },
    spacingProfile: 'spacious',
    isPremium: true,
  },

  'timeless-classic': {
    id: 'timeless-classic',
    displayName: 'Timeless Classic',
    description: 'Deep navy, heirloom ivory, and 22-karat gold filigree. Formal invitation energy from the first scroll. The standard for traditional elegance.',
    moodTags: ['classic', 'romantic', 'luxe'],
    previewThumbnailPath: '/templates/timeless-classic/preview.jpg',
    defaultThemeId: 'classic',
    sectionComposition: [
      { type: 'hero', variant: 'minimal', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'story', variant: 'split', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'venue', variant: 'detailsFirst', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'schedule', variant: 'agendaCards', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'travel', variant: 'hotelBlock', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'faq', variant: 'accordion', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'gallery', variant: 'grid', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'registry', variant: 'cards', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'rsvp', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
    ],
    sectionVariantMap: {
      hero: 'minimal',
      story: 'split',
      venue: 'detailsFirst',
      schedule: 'agendaCards',
      travel: 'hotelBlock',
      faq: 'accordion',
      gallery: 'grid',
      registry: 'cards',
      rsvp: 'default',
    },
    suggestedFonts: { heading: 'EB Garamond', body: 'Source Sans Pro' },
    spacingProfile: 'balanced',
  },

  'destination-minimal': {
    id: 'destination-minimal',
    displayName: 'Destination Escape',
    description: 'Coastal blues, map-forward layouts, and breezy white space. Purpose-built for destination weddings — venue and travel logistics lead the experience.',
    moodTags: ['minimal', 'destination', 'modern'],
    previewThumbnailPath: '/templates/destination-minimal/preview.jpg',
    defaultThemeId: 'ocean',
    sectionComposition: [
      { type: 'hero', variant: 'fullbleed', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'venue', variant: 'mapFirst', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'travel', variant: 'cards', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'story', variant: 'centered', enabled: true, locked: false, settings: { showTitle: false } },
      { type: 'schedule', variant: 'timeline', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'accommodations', variant: 'cards', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'faq', variant: 'accordion', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'rsvp', variant: 'inline', enabled: true, locked: false, settings: { showTitle: true } },
    ],
    sectionVariantMap: {
      hero: 'fullbleed',
      venue: 'mapFirst',
      travel: 'cards',
      story: 'centered',
      schedule: 'timeline',
      accommodations: 'cards',
      faq: 'accordion',
      rsvp: 'inline',
    },
    suggestedFonts: { heading: 'DM Serif Display', body: 'DM Sans' },
    spacingProfile: 'spacious',
  },

  'bold-contemporary': {
    id: 'bold-contemporary',
    displayName: 'Bold Contemporary',
    description: 'Supersized type, sharp contrast, and asymmetric grid energy. For couples who refuse to blend in. A fearlessly modern statement.',
    moodTags: ['bold', 'modern', 'editorial'],
    previewThumbnailPath: '/templates/bold-contemporary/preview.jpg',
    defaultThemeId: 'elegant',
    sectionComposition: [
      { type: 'hero', variant: 'fullbleed', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'schedule', variant: 'dayTabs', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'gallery', variant: 'filmStrip', enabled: true, locked: false, settings: { showTitle: false } },
      { type: 'story', variant: 'split', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'venue', variant: 'splitMap', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'registry', variant: 'featured', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'travel', variant: 'list', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'faq', variant: 'twoColumn', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'rsvp', variant: 'multiEvent', enabled: true, locked: false, settings: { showTitle: true } },
    ],
    sectionVariantMap: {
      hero: 'fullbleed',
      schedule: 'dayTabs',
      gallery: 'filmStrip',
      story: 'split',
      venue: 'splitMap',
      registry: 'featured',
      travel: 'list',
      faq: 'twoColumn',
      rsvp: 'multiEvent',
    },
    suggestedFonts: { heading: 'Syne', body: 'Instrument Sans' },
    spacingProfile: 'spacious',
    isNew: true,
    isPremium: true,
  },

  'photo-storytelling': {
    id: 'photo-storytelling',
    displayName: 'Photo Storytelling',
    description: 'Every pixel is framed around your photography. Masonry galleries, full-bleed moments, and minimal text so your images do the talking.',
    moodTags: ['photo', 'romantic', 'editorial'],
    previewThumbnailPath: '/templates/photo-storytelling/preview.jpg',
    defaultThemeId: 'romantic',
    sectionComposition: [
      { type: 'hero', variant: 'fullbleed', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'gallery', variant: 'masonry', enabled: true, locked: false, settings: { showTitle: false } },
      { type: 'story', variant: 'centered', enabled: true, locked: false, settings: { showTitle: false } },
      { type: 'gallery', variant: 'filmStrip', enabled: false, locked: false, settings: { showTitle: false } },
      { type: 'venue', variant: 'mapFirst', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'schedule', variant: 'agendaCards', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'travel', variant: 'list', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'rsvp', variant: 'card', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'registry', variant: 'cards', enabled: true, locked: false, settings: { showTitle: true } },
    ],
    sectionVariantMap: {
      hero: 'fullbleed',
      gallery: 'masonry',
      story: 'centered',
      venue: 'mapFirst',
      schedule: 'agendaCards',
      travel: 'list',
      rsvp: 'card',
      registry: 'cards',
    },
    suggestedFonts: { heading: 'Libre Baskerville', body: 'Karla' },
    spacingProfile: 'balanced',
  },

  'floral-garden': {
    id: 'floral-garden',
    displayName: 'Floral Garden',
    description: 'Lush botanical energy, sage and terracotta, and hand-crafted warmth. Perfect for garden, greenhouse, or outdoor weddings with a romantic, natural spirit.',
    moodTags: ['floral', 'garden', 'romantic'],
    previewThumbnailPath: '/templates/floral-garden/preview.jpg',
    defaultThemeId: 'garden',
    sectionComposition: [
      { type: 'hero', variant: 'fullbleed', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'story', variant: 'split', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'gallery', variant: 'polaroid', enabled: true, locked: false, settings: { showTitle: false } },
      { type: 'venue', variant: 'card', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'dress-code', variant: 'moodBoard', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'schedule', variant: 'agendaCards', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'travel', variant: 'list', enabled: false, locked: false, settings: { showTitle: true } },
      { type: 'registry', variant: 'cards', enabled: true, locked: false, settings: { showTitle: true } },
      { type: 'faq', variant: 'accordion', enabled: false, locked: false, settings: { showTitle: true } },
      { type: 'rsvp', variant: 'default', enabled: true, locked: false, settings: { showTitle: true } },
    ],
    sectionVariantMap: {
      hero: 'fullbleed',
      story: 'split',
      gallery: 'polaroid',
      venue: 'card',
      'dress-code': 'moodBoard',
      schedule: 'agendaCards',
      travel: 'list',
      registry: 'cards',
      faq: 'accordion',
      rsvp: 'default',
    },
    suggestedFonts: { heading: 'Gilda Display', body: 'Nunito' },
    spacingProfile: 'balanced',
  },
};

export function getAllTemplatePacks(): BuilderTemplateDefinition[] {
  return Object.values(BUILDER_TEMPLATE_PACKS);
}

export function getTemplatePack(id: string): BuilderTemplateDefinition | null {
  return BUILDER_TEMPLATE_PACKS[id] ?? null;
}
